<?php

namespace garethp\ews\API\Message;

/**
 * Class representing AddTagType
 *
 *
 * XSD Type: AddTagType
 */
class AddTagType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $tag = null;

    /**
     * @var string
     */
    protected $appName = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AddTagType
     */
    public function setTag($value)
    {
        $this->tag = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAppName()
    {
        return $this->appName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AddTagType
     */
    public function setAppName($value)
    {
        $this->appName = $value;
        return $this;
    }
}
