<?php

namespace garethp\ews\API\Message;

/**
 * Class representing CreateManagedFolderRequestType
 *
 *
 * XSD Type: CreateManagedFolderRequestType
 *
 * @method CreateManagedFolderRequestType addFolderNames(string $folderNames)
 */
class CreateManagedFolderRequestType extends BaseRequestType
{

    /**
     * @var string[]
     */
    protected $folderNames = null;

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $mailbox = null;

    /**
     * @return string[]
     */
    public function getFolderNames()
    {
        return $this->folderNames;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return CreateManagedFolderRequestType
     */
    public function setFolderNames(array $value)
    {
        $this->folderNames = $this->castValueIfNeeded("folderNames", $value);
        return $this;
    }

    /**
     * @return \garethp\ews\API\Type\EmailAddressType
     */
    public function getMailbox()
    {
        return $this->mailbox;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EmailAddressType
     * @return CreateManagedFolderRequestType
     */
    public function setMailbox(\garethp\ews\API\Type\EmailAddressType $value)
    {
        $this->mailbox = $this->castValueIfNeeded("mailbox", $value);
        return $this;
    }
}
