<?php

namespace garethp\ews\API\Message;

/**
 * Class representing CreateFolderPathType
 *
 *
 * XSD Type: CreateFolderPathType
 */
class CreateFolderPathType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\TargetFolderIdType
     */
    protected $parentFolderId = null;

    /**
     * @var \garethp\ews\API\Type\NonEmptyArrayOfFoldersType
     */
    protected $relativeFolderPath = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\TargetFolderIdType
     */
    public function getParentFolderId()
    {
        return $this->parentFolderId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\TargetFolderIdType
     * @return CreateFolderPathType
     */
    public function setParentFolderId(\garethp\ews\API\Type\TargetFolderIdType $value)
    {
        $this->parentFolderId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\NonEmptyArrayOfFoldersType
     */
    public function getRelativeFolderPath()
    {
        return $this->relativeFolderPath;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\NonEmptyArrayOfFoldersType
     * @return CreateFolderPathType
     */
    public function setRelativeFolderPath(\garethp\ews\API\Type\NonEmptyArrayOfFoldersType $value)
    {
        $this->relativeFolderPath = $value;
        return $this;
    }
}
