<?php

namespace garethp\ews\API\Message;

/**
 * Class representing CreateMeetingInstanceResponseMessageType
 *
 *
 * XSD Type: CreateMeetingInstanceResponseMessageType
 */
class CreateMeetingInstanceResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\MeetingInstanceType
     */
    protected $meetingInstance = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\MeetingInstanceType
     */
    public function getMeetingInstance()
    {
        return $this->meetingInstance;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\MeetingInstanceType
     * @return CreateMeetingInstanceResponseMessageType
     */
    public function setMeetingInstance(\garethp\ews\API\Type\MeetingInstanceType $value)
    {
        $this->meetingInstance = $value;
        return $this;
    }
}
