<?php

namespace garethp\ews\API\Message;

/**
 * Class representing CreateMeetingSpaceType
 *
 *
 * XSD Type: CreateMeetingSpaceType
 */
class CreateMeetingSpaceType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\MeetingSpaceType
     */
    protected $meetingSpace = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\MeetingSpaceType
     */
    public function getMeetingSpace()
    {
        return $this->meetingSpace;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\MeetingSpaceType
     * @return CreateMeetingSpaceType
     */
    public function setMeetingSpace(\garethp\ews\API\Type\MeetingSpaceType $value)
    {
        $this->meetingSpace = $value;
        return $this;
    }
}
