<?php

namespace garethp\ews\API\Message;

/**
 * Class representing EndInstantSearchSessionRequestType
 *
 *
 * XSD Type: EndInstantSearchSessionRequest
 */
class EndInstantSearchSessionRequestType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $sessionId = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSessionId()
    {
        return $this->sessionId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return EndInstantSearchSessionRequestType
     */
    public function setSessionId($value)
    {
        $this->sessionId = $value;
        return $this;
    }
}
