<?php

namespace garethp\ews\API\Message;

/**
 * Class representing ExecuteSearchType
 *
 *
 * XSD Type: ExecuteSearch
 */
class ExecuteSearchType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $applicationId = null;

    /**
     * @var string
     */
    protected $scenario = null;

    /**
     * @var string
     */
    protected $searchSessionId = null;

    /**
     * @var \garethp\ews\API\Type\ArrayOfSearchScopeType
     */
    protected $searchScope = null;

    /**
     * @var string
     */
    protected $query = null;

    /**
     * @var \garethp\ews\API\Type\AnalyzedQueryType
     */
    protected $analyzedQuery = null;

    /**
     * @var integer
     */
    protected $resultRowCount = null;

    /**
     * @var integer
     */
    protected $resultRowOffset = null;

    /**
     * @var integer
     */
    protected $maxResultsCountHint = null;

    /**
     * @var integer
     */
    protected $maxPreviewLength = null;

    /**
     * @var \garethp\ews\API\Type\DynamicRefinerQueryType[]
     */
    protected $searchRefiners = null;

    /**
     * @var \garethp\ews\API\Type\ExtendedKeywordDefinitionType[]
     */
    protected $extendedKeywords = null;

    /**
     * @var boolean
     */
    protected $retrieveRefiners = null;

    /**
     * @var integer
     */
    protected $maxRefinersCountPerRefinerType = null;

    /**
     * @var string
     */
    protected $idFormat = null;

    /**
     * @var string[]
     */
    protected $itemTypes = null;

    /**
     * @var string
     */
    protected $propertySetName = null;

    /**
     * @var \garethp\ews\API\Type\RestrictionType
     */
    protected $searchRestrictions = null;

    /**
     * @var boolean
     */
    protected $includeDeleted = null;

    /**
     * @var string
     */
    protected $sortOrder = null;

    /**
     * @var string
     */
    protected $keywordMatchOption = null;

    /**
     * @var boolean
     */
    protected $returnAdditionalIds = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getApplicationId()
    {
        return $this->applicationId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setApplicationId($value)
    {
        $this->applicationId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getScenario()
    {
        return $this->scenario;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setScenario($value)
    {
        $this->scenario = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSearchSessionId()
    {
        return $this->searchSessionId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setSearchSessionId($value)
    {
        $this->searchSessionId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ArrayOfSearchScopeType
     */
    public function getSearchScope()
    {
        return $this->searchScope;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ArrayOfSearchScopeType
     * @return ExecuteSearchType
     */
    public function setSearchScope(\garethp\ews\API\Type\ArrayOfSearchScopeType $value)
    {
        $this->searchScope = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setQuery($value)
    {
        $this->query = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\AnalyzedQueryType
     */
    public function getAnalyzedQuery()
    {
        return $this->analyzedQuery;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\AnalyzedQueryType
     * @return ExecuteSearchType
     */
    public function setAnalyzedQuery(\garethp\ews\API\Type\AnalyzedQueryType $value)
    {
        $this->analyzedQuery = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getResultRowCount()
    {
        return $this->resultRowCount;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ExecuteSearchType
     */
    public function setResultRowCount($value)
    {
        $this->resultRowCount = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getResultRowOffset()
    {
        return $this->resultRowOffset;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ExecuteSearchType
     */
    public function setResultRowOffset($value)
    {
        $this->resultRowOffset = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getMaxResultsCountHint()
    {
        return $this->maxResultsCountHint;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ExecuteSearchType
     */
    public function setMaxResultsCountHint($value)
    {
        $this->maxResultsCountHint = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getMaxPreviewLength()
    {
        return $this->maxPreviewLength;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ExecuteSearchType
     */
    public function setMaxPreviewLength($value)
    {
        $this->maxPreviewLength = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\DynamicRefinerQueryType
     * @return ExecuteSearchType
     */
    public function addSearchRefiners(\garethp\ews\API\Type\DynamicRefinerQueryType $value)
    {
        if ($this->searchRefiners === null) {
                        $this->searchRefiners = array();
        }

        if (!is_array($this->searchRefiners)) {
            $this->searchRefiners = array($this->searchRefiners);
        }

        $this->searchRefiners[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\DynamicRefinerQueryType[]
     */
    public function getSearchRefiners()
    {
        return $this->searchRefiners;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value
     * \garethp\ews\API\Type\DynamicRefinerQueryType[]|\garethp\ews\API\Type\DynamicRefinerQueryType
     * @return ExecuteSearchType
     */
    public function setSearchRefiners(array|\garethp\ews\API\Type\DynamicRefinerQueryType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->searchRefiners = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ExtendedKeywordDefinitionType
     * @return ExecuteSearchType
     */
    public function addExtendedKeywords(\garethp\ews\API\Type\ExtendedKeywordDefinitionType $value)
    {
        if ($this->extendedKeywords === null) {
                        $this->extendedKeywords = array();
        }

        if (!is_array($this->extendedKeywords)) {
            $this->extendedKeywords = array($this->extendedKeywords);
        }

        $this->extendedKeywords[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ExtendedKeywordDefinitionType[]
     */
    public function getExtendedKeywords()
    {
        return $this->extendedKeywords;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value
     * \garethp\ews\API\Type\ExtendedKeywordDefinitionType[]|\garethp\ews\API\Type\ExtendedKeywordDefinitionType
     * @return ExecuteSearchType
     */
    public function setExtendedKeywords(array|\garethp\ews\API\Type\ExtendedKeywordDefinitionType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->extendedKeywords = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isRetrieveRefiners()
    {
        return ((bool) $this->retrieveRefiners);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getRetrieveRefiners()
    {
        return $this->retrieveRefiners;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ExecuteSearchType
     */
    public function setRetrieveRefiners($value)
    {
        $this->retrieveRefiners = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getMaxRefinersCountPerRefinerType()
    {
        return $this->maxRefinersCountPerRefinerType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ExecuteSearchType
     */
    public function setMaxRefinersCountPerRefinerType($value)
    {
        $this->maxRefinersCountPerRefinerType = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getIdFormat()
    {
        return $this->idFormat;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setIdFormat($value)
    {
        $this->idFormat = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function addItemTypes($value)
    {
        if ($this->itemTypes === null) {
                        $this->itemTypes = array();
        }

        if (!is_array($this->itemTypes)) {
            $this->itemTypes = array($this->itemTypes);
        }

        $this->itemTypes[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getItemTypes()
    {
        return $this->itemTypes;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return ExecuteSearchType
     */
    public function setItemTypes(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->itemTypes = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPropertySetName()
    {
        return $this->propertySetName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setPropertySetName($value)
    {
        $this->propertySetName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\RestrictionType
     */
    public function getSearchRestrictions()
    {
        return $this->searchRestrictions;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\RestrictionType
     * @return ExecuteSearchType
     */
    public function setSearchRestrictions(\garethp\ews\API\Type\RestrictionType $value)
    {
        $this->searchRestrictions = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isIncludeDeleted()
    {
        return ((bool) $this->includeDeleted);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIncludeDeleted()
    {
        return $this->includeDeleted;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ExecuteSearchType
     */
    public function setIncludeDeleted($value)
    {
        $this->includeDeleted = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSortOrder()
    {
        return $this->sortOrder;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setSortOrder($value)
    {
        $this->sortOrder = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getKeywordMatchOption()
    {
        return $this->keywordMatchOption;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ExecuteSearchType
     */
    public function setKeywordMatchOption($value)
    {
        $this->keywordMatchOption = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isReturnAdditionalIds()
    {
        return ((bool) $this->returnAdditionalIds);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getReturnAdditionalIds()
    {
        return $this->returnAdditionalIds;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ExecuteSearchType
     */
    public function setReturnAdditionalIds($value)
    {
        $this->returnAdditionalIds = $value;
        return $this;
    }
}
