<?php

namespace garethp\ews\API\Message;

/**
 * Class representing FindConversationResponseMessageType
 *
 *
 * XSD Type: FindConversationResponseMessageType
 *
 * @method FindConversationResponseMessageType addConversations(\garethp\ews\API\Type\ConversationType $conversations)
 */
class FindConversationResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\ConversationType[]
     */
    protected $conversations = null;

    /**
     * @return \garethp\ews\API\Type\ConversationType[]
     */
    public function getConversations()
    {
        return $this->conversations;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ConversationType[]
     * @return FindConversationResponseMessageType
     */
    public function setConversations(array $value)
    {
        $this->conversations = $this->castValueIfNeeded("conversations", $value);
        return $this;
    }
}
