<?php

namespace garethp\ews\API\Message;

/**
 * Class representing FindMessageTrackingReportRequestType
 *
 *
 * XSD Type: FindMessageTrackingReportRequestType
 *
 * @method FindMessageTrackingReportRequestType addProperties(\garethp\ews\API\Type\TrackingPropertyType $properties)
 */
class FindMessageTrackingReportRequestType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $scope = null;

    /**
     * @var string
     */
    protected $domain = null;

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $sender = null;

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $purportedSender = null;

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $recipient = null;

    /**
     * @var string
     */
    protected $subject = null;

    /**
     * @var \DateTime
     */
    protected $startDateTime = null;

    protected $_typeMap = array(
        'startDateTime' => 'dateTime',
        'endDateTime' => 'dateTime',
    );

    /**
     * @var \DateTime
     */
    protected $endDateTime = null;

    /**
     * @var string
     */
    protected $messageId = null;

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $federatedDeliveryMailbox = null;

    /**
     * @var string
     */
    protected $diagnosticsLevel = null;

    /**
     * @var string
     */
    protected $serverHint = null;

    /**
     * @var \garethp\ews\API\Type\TrackingPropertyType[]
     */
    protected $properties = null;

    /**
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * @return \garethp\ews\API\Type\EmailAddressType
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * @return \garethp\ews\API\Type\EmailAddressType
     */
    public function getPurportedSender()
    {
        return $this->purportedSender;
    }

    /**
     * @return \garethp\ews\API\Type\EmailAddressType
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * @return \DateTime
     */
    public function getStartDateTime()
    {
        return $this->startDateTime;
    }

    /**
     * @return \DateTime
     */
    public function getEndDateTime()
    {
        return $this->endDateTime;
    }

    /**
     * @return string
     */
    public function getMessageId()
    {
        return $this->messageId;
    }

    /**
     * @return \garethp\ews\API\Type\EmailAddressType
     */
    public function getFederatedDeliveryMailbox()
    {
        return $this->federatedDeliveryMailbox;
    }

    /**
     * @return string
     */
    public function getDiagnosticsLevel()
    {
        return $this->diagnosticsLevel;
    }

    /**
     * @return string
     */
    public function getServerHint()
    {
        return $this->serverHint;
    }

    /**
     * @return \garethp\ews\API\Type\TrackingPropertyType[]
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindMessageTrackingReportRequestType
     */
    public function setScope($value)
    {
        $this->scope = $this->castValueIfNeeded("scope", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindMessageTrackingReportRequestType
     */
    public function setDomain($value)
    {
        $this->domain = $this->castValueIfNeeded("domain", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EmailAddressType
     * @return FindMessageTrackingReportRequestType
     */
    public function setSender(\garethp\ews\API\Type\EmailAddressType $value)
    {
        $this->sender = $this->castValueIfNeeded("sender", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EmailAddressType
     * @return FindMessageTrackingReportRequestType
     */
    public function setPurportedSender(\garethp\ews\API\Type\EmailAddressType $value)
    {
        $this->purportedSender = $this->castValueIfNeeded("purportedSender", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EmailAddressType
     * @return FindMessageTrackingReportRequestType
     */
    public function setRecipient(\garethp\ews\API\Type\EmailAddressType $value)
    {
        $this->recipient = $this->castValueIfNeeded("recipient", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindMessageTrackingReportRequestType
     */
    public function setSubject($value)
    {
        $this->subject = $this->castValueIfNeeded("subject", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return FindMessageTrackingReportRequestType
     */
    public function setStartDateTime(\DateTime|string $value)
    {
        $this->startDateTime = $this->castValueIfNeeded("startDateTime", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return FindMessageTrackingReportRequestType
     */
    public function setEndDateTime(\DateTime|string $value)
    {
        $this->endDateTime = $this->castValueIfNeeded("endDateTime", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindMessageTrackingReportRequestType
     */
    public function setMessageId($value)
    {
        $this->messageId = $this->castValueIfNeeded("messageId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EmailAddressType
     * @return FindMessageTrackingReportRequestType
     */
    public function setFederatedDeliveryMailbox(\garethp\ews\API\Type\EmailAddressType $value)
    {
        $this->federatedDeliveryMailbox = $this->castValueIfNeeded("federatedDeliveryMailbox", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindMessageTrackingReportRequestType
     */
    public function setDiagnosticsLevel($value)
    {
        $this->diagnosticsLevel = $this->castValueIfNeeded("diagnosticsLevel", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindMessageTrackingReportRequestType
     */
    public function setServerHint($value)
    {
        $this->serverHint = $this->castValueIfNeeded("serverHint", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\TrackingPropertyType[]
     * @return FindMessageTrackingReportRequestType
     */
    public function setProperties(array $value)
    {
        $this->properties = $this->castValueIfNeeded("properties", $value);
        return $this;
    }
}
