<?php

namespace garethp\ews\API\Message;

/**
 * Class representing FindConversationType
 *
 *
 * XSD Type: FindConversationType
 *
 * @method FindConversationType addSortOrder(\garethp\ews\API\Type\FieldOrderType $sortOrder)
 */
class FindConversationType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\IndexedPageViewType
     */
    protected $indexedPageItemView = null;

    /**
     * @var \garethp\ews\API\Type\FieldOrderType[]
     */
    protected $sortOrder = null;

    /**
     * @var \garethp\ews\API\Type\TargetFolderIdType
     */
    protected $parentFolderId = null;

    /**
     * @return \garethp\ews\API\Type\IndexedPageViewType
     */
    public function getIndexedPageItemView()
    {
        return $this->indexedPageItemView;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\IndexedPageViewType
     * @return FindConversationType
     */
    public function setIndexedPageItemView(\garethp\ews\API\Type\IndexedPageViewType $value)
    {
        $this->indexedPageItemView = $this->castValueIfNeeded("indexedPageItemView", $value);
        return $this;
    }

    /**
     * @return \garethp\ews\API\Type\FieldOrderType[]
     */
    public function getSortOrder()
    {
        return $this->sortOrder;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\FieldOrderType[]
     * @return FindConversationType
     */
    public function setSortOrder(array $value)
    {
        $this->sortOrder = $this->castValueIfNeeded("sortOrder", $value);
        return $this;
    }

    /**
     * @return \garethp\ews\API\Type\TargetFolderIdType
     */
    public function getParentFolderId()
    {
        return $this->parentFolderId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\TargetFolderIdType
     * @return FindConversationType
     */
    public function setParentFolderId(\garethp\ews\API\Type\TargetFolderIdType $value)
    {
        $this->parentFolderId = $this->castValueIfNeeded("parentFolderId", $value);
        return $this;
    }
}
