<?php

namespace garethp\ews\API\Message;

/**
 * Class representing FindTagsType
 *
 *
 * XSD Type: FindTagsType
 */
class FindTagsType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\IndexedPageViewType
     */
    protected $indexedPageItemView = null;

    /**
     * @var \garethp\ews\API\Type\FieldOrderType[]
     */
    protected $sortOrder = null;

    /**
     * @var string
     */
    protected $queryString = null;

    /**
     * @var \garethp\ews\API\Type\ContextPropertyType[]
     */
    protected $context = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\IndexedPageViewType
     */
    public function getIndexedPageItemView()
    {
        return $this->indexedPageItemView;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\IndexedPageViewType
     * @return FindTagsType
     */
    public function setIndexedPageItemView(\garethp\ews\API\Type\IndexedPageViewType $value)
    {
        $this->indexedPageItemView = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\FieldOrderType
     * @return FindTagsType
     */
    public function addSortOrder(\garethp\ews\API\Type\FieldOrderType $value)
    {
        if ($this->sortOrder === null) {
                        $this->sortOrder = array();
        }

        if (!is_array($this->sortOrder)) {
            $this->sortOrder = array($this->sortOrder);
        }

        $this->sortOrder[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\FieldOrderType[]
     */
    public function getSortOrder()
    {
        return $this->sortOrder;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value
     * \garethp\ews\API\Type\FieldOrderType[]|\garethp\ews\API\Type\FieldOrderType
     * @return FindTagsType
     */
    public function setSortOrder(array|\garethp\ews\API\Type\FieldOrderType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->sortOrder = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getQueryString()
    {
        return $this->queryString;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindTagsType
     */
    public function setQueryString($value)
    {
        $this->queryString = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ContextPropertyType
     * @return FindTagsType
     */
    public function addContext(\garethp\ews\API\Type\ContextPropertyType $value)
    {
        if ($this->context === null) {
                        $this->context = array();
        }

        if (!is_array($this->context)) {
            $this->context = array($this->context);
        }

        $this->context[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ContextPropertyType[]
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value
     * \garethp\ews\API\Type\ContextPropertyType[]|\garethp\ews\API\Type\ContextPropertyType
     * @return FindTagsType
     */
    public function setContext(array|\garethp\ews\API\Type\ContextPropertyType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->context = $value;
        return $this;
    }
}
