<?php

namespace garethp\ews\API\Message;

/**
 * Class representing FindMeetingSpaceByJoinUrlType
 *
 *
 * XSD Type: FindMeetingSpaceByJoinUrlType
 */
class FindMeetingSpaceByJoinUrlType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $joinUrl = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getJoinUrl()
    {
        return $this->joinUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FindMeetingSpaceByJoinUrlType
     */
    public function setJoinUrl($value)
    {
        $this->joinUrl = $value;
        return $this;
    }
}
