<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetAppMarketplaceUrlResponseMessageType
 *
 *
 * XSD Type: GetAppMarketplaceUrlResponseMessageType
 */
class GetAppMarketplaceUrlResponseMessageType extends ResponseMessageType
{

    /**
     * @var string
     */
    protected $appMarketplaceUrl = null;

    /**
     * @var string
     */
    protected $connectorsManagementUrl = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAppMarketplaceUrl()
    {
        return $this->appMarketplaceUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetAppMarketplaceUrlResponseMessageType
     */
    public function setAppMarketplaceUrl($value)
    {
        $this->appMarketplaceUrl = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getConnectorsManagementUrl()
    {
        return $this->connectorsManagementUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetAppMarketplaceUrlResponseMessageType
     */
    public function setConnectorsManagementUrl($value)
    {
        $this->connectorsManagementUrl = $value;
        return $this;
    }
}
