<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetDiscoverySearchConfigurationType
 *
 * Request type for the GetDiscoverySearchConfiguration web method.
 * XSD Type: GetDiscoverySearchConfigurationType
 */
class GetDiscoverySearchConfigurationType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $searchId = null;

    /**
     * @var boolean
     */
    protected $expandGroupMembership = null;

    /**
     * @var boolean
     */
    protected $inPlaceHoldConfigurationOnly = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSearchId()
    {
        return $this->searchId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetDiscoverySearchConfigurationType
     */
    public function setSearchId($value)
    {
        $this->searchId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isExpandGroupMembership()
    {
        return ((bool) $this->expandGroupMembership);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getExpandGroupMembership()
    {
        return $this->expandGroupMembership;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return GetDiscoverySearchConfigurationType
     */
    public function setExpandGroupMembership($value)
    {
        $this->expandGroupMembership = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isInPlaceHoldConfigurationOnly()
    {
        return ((bool) $this->inPlaceHoldConfigurationOnly);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getInPlaceHoldConfigurationOnly()
    {
        return $this->inPlaceHoldConfigurationOnly;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return GetDiscoverySearchConfigurationType
     */
    public function setInPlaceHoldConfigurationOnly($value)
    {
        $this->inPlaceHoldConfigurationOnly = $value;
        return $this;
    }
}
