<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetHoldOnMailboxesResponseMessageType
 *
 * Response message type for the GetHoldOnMailboxes web method.
 * XSD Type: GetHoldOnMailboxesResponseMessageType
 */
class GetHoldOnMailboxesResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\MailboxHoldResultType
     */
    protected $mailboxHoldResult = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\MailboxHoldResultType
     */
    public function getMailboxHoldResult()
    {
        return $this->mailboxHoldResult;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\MailboxHoldResultType
     * @return GetHoldOnMailboxesResponseMessageType
     */
    public function setMailboxHoldResult(\garethp\ews\API\Type\MailboxHoldResultType $value)
    {
        $this->mailboxHoldResult = $value;
        return $this;
    }
}
