<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetImItemListResponseMessageType
 *
 *
 * XSD Type: GetImItemListResponseMessageType
 */
class GetImItemListResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\ImItemListType
     */
    protected $imItemList = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ImItemListType
     */
    public function getImItemList()
    {
        return $this->imItemList;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ImItemListType
     * @return GetImItemListResponseMessageType
     */
    public function setImItemList(\garethp\ews\API\Type\ImItemListType $value)
    {
        $this->imItemList = $value;
        return $this;
    }
}
