<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetInboxRulesResponseType
 *
 *
 * XSD Type: GetInboxRulesResponseType
 *
 * @method GetInboxRulesResponseType addInboxRules(\garethp\ews\API\Type\RuleType $inboxRules)
 */
class GetInboxRulesResponseType extends ResponseMessageType
{

    /**
     * @var boolean
     */
    protected $outlookRuleBlobExists = null;

    /**
     * @var \garethp\ews\API\Type\RuleType[]
     */
    protected $inboxRules = null;

    /**
     * @returns bool
     */
    public function isOutlookRuleBlobExists()
    {
        return ((bool) $this->outlookRuleBlobExists);
    }

    /**
     * @return boolean
     */
    public function getOutlookRuleBlobExists()
    {
        return $this->outlookRuleBlobExists;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return GetInboxRulesResponseType
     */
    public function setOutlookRuleBlobExists($value)
    {
        $this->outlookRuleBlobExists = $this->castValueIfNeeded("outlookRuleBlobExists", $value);
        return $this;
    }

    /**
     * @return \garethp\ews\API\Type\RuleType[]
     */
    public function getInboxRules()
    {
        return $this->inboxRules;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\RuleType[]
     * @return GetInboxRulesResponseType
     */
    public function setInboxRules(array $value)
    {
        $this->inboxRules = $this->castValueIfNeeded("inboxRules", $value);
        return $this;
    }
}
