<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetLastPrivateCatalogUpdateResponseType
 *
 *
 * XSD Type: GetLastPrivateCatalogUpdateResponseType
 */
class GetLastPrivateCatalogUpdateResponseType extends ResponseMessageType
{

    /**
     * @var \DateTime
     */
    protected $lastUpdate = null;

    /**
     * @var string
     */
    protected $catalogHash = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getLastUpdate()
    {
        return $this->lastUpdate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return GetLastPrivateCatalogUpdateResponseType
     */
    public function setLastUpdate(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->lastUpdate = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getCatalogHash()
    {
        return $this->catalogHash;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetLastPrivateCatalogUpdateResponseType
     */
    public function setCatalogHash($value)
    {
        $this->catalogHash = $value;
        return $this;
    }
}
