<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetMessageTrackingReportResponseMessageType
 *
 *
 * XSD Type: GetMessageTrackingReportResponseMessageType
 *
 * @method GetMessageTrackingReportResponseMessageType addDiagnostics(string $diagnostics)
 * @method GetMessageTrackingReportResponseMessageType addErrors(\garethp\ews\API\Type\ArrayOfTrackingPropertiesType $errors)
 * @method GetMessageTrackingReportResponseMessageType addProperties(\garethp\ews\API\Type\TrackingPropertyType $properties)
 */
class GetMessageTrackingReportResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\MessageTrackingReportType
     */
    protected $messageTrackingReport = null;

    /**
     * @var string[]
     */
    protected $diagnostics = null;

    /**
     * @var \garethp\ews\API\Type\ArrayOfTrackingPropertiesType[]
     */
    protected $errors = null;

    /**
     * @var \garethp\ews\API\Type\TrackingPropertyType[]
     */
    protected $properties = null;

    /**
     * @return \garethp\ews\API\Type\MessageTrackingReportType
     */
    public function getMessageTrackingReport()
    {
        return $this->messageTrackingReport;
    }

    /**
     * @return string[]
     */
    public function getDiagnostics()
    {
        return $this->diagnostics;
    }

    /**
     * @return \garethp\ews\API\Type\ArrayOfTrackingPropertiesType[]
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * @return \garethp\ews\API\Type\TrackingPropertyType[]
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\MessageTrackingReportType
     * @return GetMessageTrackingReportResponseMessageType
     */
    public function setMessageTrackingReport(\garethp\ews\API\Type\MessageTrackingReportType $value)
    {
        $this->messageTrackingReport = $this->castValueIfNeeded("messageTrackingReport", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return GetMessageTrackingReportResponseMessageType
     */
    public function setDiagnostics(array $value)
    {
        $this->diagnostics = $this->castValueIfNeeded("diagnostics", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ArrayOfTrackingPropertiesType[]
     * @return GetMessageTrackingReportResponseMessageType
     */
    public function setErrors(array $value)
    {
        $this->errors = $this->castValueIfNeeded("errors", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\TrackingPropertyType[]
     * @return GetMessageTrackingReportResponseMessageType
     */
    public function setProperties(array $value)
    {
        $this->properties = $this->castValueIfNeeded("properties", $value);
        return $this;
    }
}
