<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetNonIndexableItemDetailsResponseMessageType
 *
 * Response message type for the GetNonIndexableItemDetails web method.
 * XSD Type: GetNonIndexableItemDetailsResponseMessageType
 */
class GetNonIndexableItemDetailsResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\NonIndexableItemDetailResultType
     */
    protected $nonIndexableItemDetailsResult = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\NonIndexableItemDetailResultType
     */
    public function getNonIndexableItemDetailsResult()
    {
        return $this->nonIndexableItemDetailsResult;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\NonIndexableItemDetailResultType
     * @return GetNonIndexableItemDetailsResponseMessageType
     */
    public function setNonIndexableItemDetailsResult(\garethp\ews\API\Type\NonIndexableItemDetailResultType $value)
    {
        $this->nonIndexableItemDetailsResult = $value;
        return $this;
    }
}
