<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetPasswordExpirationDateResponseMessageType
 *
 *
 * XSD Type: GetPasswordExpirationDateResponseMessageType
 */
class GetPasswordExpirationDateResponseMessageType extends ResponseMessageType
{

    /**
     * @var \DateTime
     */
    protected $passwordExpirationDate = null;

    protected $_typeMap = array(
        'passwordExpirationDate' => 'dateTime',
    );

    /**
     * @return \DateTime
     */
    public function getPasswordExpirationDate()
    {
        return $this->passwordExpirationDate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return GetPasswordExpirationDateResponseMessageType
     */
    public function setPasswordExpirationDate(\DateTime|string $value)
    {
        $this->passwordExpirationDate = $this->castValueIfNeeded("passwordExpirationDate", $value);
        return $this;
    }
}
