<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetRoomsType
 *
 *
 * XSD Type: GetRoomsType
 */
class GetRoomsType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $roomList = null;

    /**
     * @return \garethp\ews\API\Type\EmailAddressType
     */
    public function getRoomList()
    {
        return $this->roomList;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EmailAddressType
     * @return GetRoomsType
     */
    public function setRoomList(\garethp\ews\API\Type\EmailAddressType $value)
    {
        $this->roomList = $this->castValueIfNeeded("roomList", $value);
        return $this;
    }
}
