<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetSharingMetadataResponseMessageType
 *
 *
 * XSD Type: GetSharingMetadataResponseMessageType
 *
 * @method GetSharingMetadataResponseMessageType addEncryptedSharedFolderDataCollection(\garethp\ews\API\Type\EncryptedSharedFolderDataType $encryptedSharedFolderDataCollection)
 * @method GetSharingMetadataResponseMessageType addInvalidRecipients(\garethp\ews\API\Type\InvalidRecipientType $invalidRecipients)
 */
class GetSharingMetadataResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\EncryptedSharedFolderDataType[]
     */
    protected $encryptedSharedFolderDataCollection = null;

    /**
     * @var \garethp\ews\API\Type\InvalidRecipientType[]
     */
    protected $invalidRecipients = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\EncryptedSharedFolderDataType[]
     */
    public function getEncryptedSharedFolderDataCollection()
    {
        return $this->encryptedSharedFolderDataCollection;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EncryptedSharedFolderDataType[]
     * @return GetSharingMetadataResponseMessageType
     */
    public function setEncryptedSharedFolderDataCollection(array $value)
    {
        $this->encryptedSharedFolderDataCollection = $this->castValueIfNeeded("encryptedSharedFolderDataCollection", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\InvalidRecipientType[]
     */
    public function getInvalidRecipients()
    {
        return $this->invalidRecipients;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\InvalidRecipientType[]
     * @return GetSharingMetadataResponseMessageType
     */
    public function setInvalidRecipients(array $value)
    {
        $this->invalidRecipients = $this->castValueIfNeeded("invalidRecipients", $value);
        return $this;
    }
}
