<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetServiceConfigurationType
 *
 *
 * XSD Type: GetServiceConfigurationType
 *
 * @method GetServiceConfigurationType addRequestedConfiguration(\garethp\ews\API\Enumeration\ServiceConfigurationType $requestedConfiguration)
 */
class GetServiceConfigurationType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $actingAs = null;

    /**
     * @var \garethp\ews\API\Enumeration\ServiceConfigurationType[]
     */
    protected $requestedConfiguration = null;

    /**
     * @return \garethp\ews\API\Type\EmailAddressType
     */
    public function getActingAs()
    {
        return $this->actingAs;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\EmailAddressType
     * @return GetServiceConfigurationType
     */
    public function setActingAs(\garethp\ews\API\Type\EmailAddressType $value)
    {
        $this->actingAs = $this->castValueIfNeeded("actingAs", $value);
        return $this;
    }

    /**
     * @return \garethp\ews\API\Enumeration\ServiceConfigurationType[]
     */
    public function getRequestedConfiguration()
    {
        return $this->requestedConfiguration;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Enumeration\ServiceConfigurationType[]
     * @return GetServiceConfigurationType
     */
    public function setRequestedConfiguration(array $value)
    {
        $this->requestedConfiguration = $this->castValueIfNeeded("requestedConfiguration", $value);
        return $this;
    }
}
