<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetStreamingEventsResponseMessageType
 *
 *
 * XSD Type: GetStreamingEventsResponseMessageType
 *
 * @method GetStreamingEventsResponseMessageType addNotifications(\garethp\ews\API\Type\NotificationType $notifications)
 * @method GetStreamingEventsResponseMessageType addErrorSubscriptionIds(string $errorSubscriptionIds)
 */
class GetStreamingEventsResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\NotificationType[]
     */
    protected $notifications = null;

    /**
     * @var string[]
     */
    protected $errorSubscriptionIds = null;

    /**
     * @var string
     */
    protected $connectionStatus = null;

    /**
     * @return \garethp\ews\API\Type\NotificationType[]
     */
    public function getNotifications()
    {
        return $this->notifications;
    }

    /**
     * @return string[]
     */
    public function getErrorSubscriptionIds()
    {
        return $this->errorSubscriptionIds;
    }

    /**
     * @return string
     */
    public function getConnectionStatus()
    {
        return $this->connectionStatus;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\NotificationType[]
     * @return GetStreamingEventsResponseMessageType
     */
    public function setNotifications(array $value)
    {
        $this->notifications = $this->castValueIfNeeded("notifications", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return GetStreamingEventsResponseMessageType
     */
    public function setErrorSubscriptionIds(array $value)
    {
        $this->errorSubscriptionIds = $this->castValueIfNeeded("errorSubscriptionIds", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetStreamingEventsResponseMessageType
     */
    public function setConnectionStatus($value)
    {
        $this->connectionStatus = $this->castValueIfNeeded("connectionStatus", $value);
        return $this;
    }
}
