<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetServiceConfigurationResponseMessageType
 *
 *
 * XSD Type: GetServiceConfigurationResponseMessageType
 */
class GetServiceConfigurationResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Message\ServiceConfigurationResponseMessageType[]
     */
    protected $responseMessages = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value ServiceConfigurationResponseMessageType
     * @return GetServiceConfigurationResponseMessageType
     */
    public function addResponseMessages(ServiceConfigurationResponseMessageType $value)
    {
        $value = $this->castValueIfNeeded("responseMessages", $value);

        if ($this->responseMessages === null) {
            $this->responseMessages = array();
        }

        if (!is_array($this->responseMessages)) {
            $this->responseMessages = array($this->responseMessages);
        }

        $this->responseMessages[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ServiceConfigurationResponseMessageType[]
     */
    public function getResponseMessages()
    {
        return $this->responseMessages;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ServiceConfigurationResponseMessageType[]
     * @return GetServiceConfigurationResponseMessageType
     */
    public function setResponseMessages(array $value)
    {
        $this->responseMessages = $this->castValueIfNeeded("responseMessages", $value);
        return $this;
    }
}
