<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetUserPhotoResponseMessageType
 *
 *
 * XSD Type: GetUserPhotoResponseMessageType
 */
class GetUserPhotoResponseMessageType extends ResponseMessageType
{

    /**
     * @var boolean
     */
    protected $hasChanged = null;

    /**
     * @var string
     */
    protected $pictureData = null;

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isHasChanged()
    {
        return ((bool) $this->hasChanged);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getHasChanged()
    {
        return $this->hasChanged;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return GetUserPhotoResponseMessageType
     */
    public function setHasChanged($value)
    {
        $this->hasChanged = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPictureData()
    {
        return $this->pictureData;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetUserPhotoResponseMessageType
     */
    public function setPictureData($value)
    {
        $this->pictureData = $value;
        return $this;
    }
}
