<?php

namespace garethp\ews\API\Message;

/**
 * Class representing GetUserPhotoType
 *
 *
 * XSD Type: GetUserPhotoType
 */
class GetUserPhotoType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $email = null;

    /**
     * @var string
     */
    protected $sizeRequested = null;

    /**
     * @var string
     */
    protected $typeRequested = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetUserPhotoType
     */
    public function setEmail($value)
    {
        $this->email = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSizeRequested()
    {
        return $this->sizeRequested;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetUserPhotoType
     */
    public function setSizeRequested($value)
    {
        $this->sizeRequested = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTypeRequested()
    {
        return $this->typeRequested;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return GetUserPhotoType
     */
    public function setTypeRequested($value)
    {
        $this->typeRequested = $value;
        return $this;
    }
}
