<?php

namespace garethp\ews\API\Message;

/**
 * Class representing InstallAppResponseType
 *
 *
 * XSD Type: InstallAppResponseType
 */
class InstallAppResponseType extends ResponseMessageType
{

    /**
     * @var boolean
     */
    protected $wasFirstInstall = null;

    /**
     * @var \garethp\ews\API\Type\InstalledAppType
     */
    protected $extension = null;

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isWasFirstInstall()
    {
        return ((bool) $this->wasFirstInstall);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getWasFirstInstall()
    {
        return $this->wasFirstInstall;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return InstallAppResponseType
     */
    public function setWasFirstInstall($value)
    {
        $this->wasFirstInstall = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\InstalledAppType
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\InstalledAppType
     * @return InstallAppResponseType
     */
    public function setExtension(\garethp\ews\API\Type\InstalledAppType $value)
    {
        $this->extension = $value;
        return $this;
    }
}
