<?php

namespace garethp\ews\API\Message;

/**
 * Class representing MarkAsJunkResponseMessageType
 *
 *
 * XSD Type: MarkAsJunkResponseMessageType
 */
class MarkAsJunkResponseMessageType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $movedItemId = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ItemIdType
     */
    public function getMovedItemId()
    {
        return $this->movedItemId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemIdType
     * @return MarkAsJunkResponseMessageType
     */
    public function setMovedItemId(\garethp\ews\API\Type\ItemIdType $value)
    {
        $this->movedItemId = $value;
        return $this;
    }
}
