<?php

namespace garethp\ews\API\Message;

/**
 * Class representing OMEConfigurationResponseType
 *
 *
 * XSD Type: OMEConfigurationResponseType
 */
class OMEConfigurationResponseType extends ResponseMessageType
{

    /**
     * @var string
     */
    protected $xml = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getXml()
    {
        return $this->xml;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return OMEConfigurationResponseType
     */
    public function setXml($value)
    {
        $this->xml = $value;
        return $this;
    }
}
