<?php

namespace garethp\ews\API\Message;

use garethp\ews\API\Message;

/**
 * Class representing PrivateCatalogAddInStoreInfoType
 *
 *
 * XSD Type: PrivateCatalogAddInStoreInfoType
 */
class PrivateCatalogAddInStoreInfoType extends Message
{

    /**
     * @var string
     */
    protected $assetId = null;

    /**
     * @var string
     */
    protected $contentMarket = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAssetId()
    {
        return $this->assetId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PrivateCatalogAddInStoreInfoType
     */
    public function setAssetId($value)
    {
        $this->assetId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getContentMarket()
    {
        return $this->contentMarket;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PrivateCatalogAddInStoreInfoType
     */
    public function setContentMarket($value)
    {
        $this->contentMarket = $value;
        return $this;
    }
}
