<?php

namespace garethp\ews\API\Message;

/**
 * Class representing RemoveImGroupType
 *
 *
 * XSD Type: RemoveImGroupType
 */
class RemoveImGroupType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $groupId = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ItemIdType
     */
    public function getGroupId()
    {
        return $this->groupId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemIdType
     * @return RemoveImGroupType
     */
    public function setGroupId(\garethp\ews\API\Type\ItemIdType $value)
    {
        $this->groupId = $value;
        return $this;
    }
}
