<?php

namespace garethp\ews\API\Message;

/**
 * Class representing RemoveContactFromImListType
 *
 *
 * XSD Type: RemoveContactFromImListType
 */
class RemoveContactFromImListType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $contactId = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ItemIdType
     */
    public function getContactId()
    {
        return $this->contactId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemIdType
     * @return RemoveContactFromImListType
     */
    public function setContactId(\garethp\ews\API\Type\ItemIdType $value)
    {
        $this->contactId = $value;
        return $this;
    }
}
