<?php

namespace garethp\ews\API\Message;

use garethp\ews\API\Message;

/**
 * Class representing ResponseMessageType
 *
 *
 * XSD Type: ResponseMessageType
 */
class ResponseMessageType extends Message
{

    /**
     * @var string
     */
    protected $responseClass = null;

    /**
     * @var string
     */
    protected $messageText = null;

    /**
     * @var string
     */
    protected $responseCode = null;

    /**
     * @var integer
     */
    protected $descriptiveLinkKey = null;

    /**
     * @var \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     */
    protected $messageXml = null;

    /**
     * @return string
     */
    public function getResponseClass()
    {
        return $this->responseClass;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setResponseClass($value)
    {
        $this->responseClass = $this->castValueIfNeeded("responseClass", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getMessageText()
    {
        return $this->messageText;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setMessageText($value)
    {
        $this->messageText = $this->castValueIfNeeded("messageText", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getResponseCode()
    {
        return $this->responseCode;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setResponseCode($value)
    {
        $this->responseCode = $this->castValueIfNeeded("responseCode", $value);
        return $this;
    }

    /**
     * @return integer
     */
    public function getDescriptiveLinkKey()
    {
        return $this->descriptiveLinkKey;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ResponseMessageType
     */
    public function setDescriptiveLinkKey($value)
    {
        $this->descriptiveLinkKey = $this->castValueIfNeeded("descriptiveLinkKey", $value);
        return $this;
    }

    /**
     * @return \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     */
    public function getMessageXml()
    {
        return $this->messageXml;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     * @return ResponseMessageType
     */
    public function setMessageXml(\garethp\ews\API\Message\ResponseMessageType\MessageXmlAType $value)
    {
        $this->messageXml = $this->castValueIfNeeded("messageXml", $value);
        return $this;
    }
}
