<?php

namespace garethp\ews\API\Message;

/**
 * Class representing StartSearchSessionType
 *
 *
 * XSD Type: StartSearchSession
 */
class StartSearchSessionType extends BaseRequestType
{

    /**
     * @var string
     */
    protected $searchSessionId = null;

    /**
     * @var string[]
     */
    protected $warmupOptions = null;

    /**
     * @var string[]
     */
    protected $suggestionTypes = null;

    /**
     * @var \garethp\ews\API\Type\ArrayOfSearchScopeType
     */
    protected $searchScope = null;

    /**
     * @var string
     */
    protected $idFormat = null;

    /**
     * @var string
     */
    protected $applicationId = null;

    /**
     * @var string
     */
    protected $scenario = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSearchSessionId()
    {
        return $this->searchSessionId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return StartSearchSessionType
     */
    public function setSearchSessionId($value)
    {
        $this->searchSessionId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return StartSearchSessionType
     */
    public function addWarmupOptions($value)
    {
        if ($this->warmupOptions === null) {
                        $this->warmupOptions = array();
        }

        if (!is_array($this->warmupOptions)) {
            $this->warmupOptions = array($this->warmupOptions);
        }

        $this->warmupOptions[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getWarmupOptions()
    {
        return $this->warmupOptions;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return StartSearchSessionType
     */
    public function setWarmupOptions(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->warmupOptions = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return StartSearchSessionType
     */
    public function addSuggestionTypes($value)
    {
        if ($this->suggestionTypes === null) {
                        $this->suggestionTypes = array();
        }

        if (!is_array($this->suggestionTypes)) {
            $this->suggestionTypes = array($this->suggestionTypes);
        }

        $this->suggestionTypes[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getSuggestionTypes()
    {
        return $this->suggestionTypes;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return StartSearchSessionType
     */
    public function setSuggestionTypes(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->suggestionTypes = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ArrayOfSearchScopeType
     */
    public function getSearchScope()
    {
        return $this->searchScope;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ArrayOfSearchScopeType
     * @return StartSearchSessionType
     */
    public function setSearchScope(\garethp\ews\API\Type\ArrayOfSearchScopeType $value)
    {
        $this->searchScope = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getIdFormat()
    {
        return $this->idFormat;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return StartSearchSessionType
     */
    public function setIdFormat($value)
    {
        $this->idFormat = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getApplicationId()
    {
        return $this->applicationId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return StartSearchSessionType
     */
    public function setApplicationId($value)
    {
        $this->applicationId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getScenario()
    {
        return $this->scenario;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return StartSearchSessionType
     */
    public function setScenario($value)
    {
        $this->scenario = $value;
        return $this;
    }
}
