<?php

namespace garethp\ews\API\Message;

/**
 * Class representing SyncFolderItemsType
 *
 *
 * XSD Type: SyncFolderItemsType
 *
 * @method SyncFolderItemsType addIgnore(\garethp\ews\API\Type\ItemIdType $ignore)
 */
class SyncFolderItemsType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\ItemResponseShapeType
     */
    protected $itemShape = null;

    /**
     * @var \garethp\ews\API\Type\TargetFolderIdType
     */
    protected $syncFolderId = null;

    /**
     * @var string
     */
    protected $syncState = null;

    /**
     * @var \garethp\ews\API\Type\ItemIdType[]
     */
    protected $ignore = null;

    /**
     * @var integer
     */
    protected $maxChangesReturned = null;

    /**
     * @var string
     */
    protected $syncScope = null;

    /**
     * @return \garethp\ews\API\Type\ItemResponseShapeType
     */
    public function getItemShape()
    {
        return $this->itemShape;
    }

    /**
     * @return \garethp\ews\API\Type\TargetFolderIdType
     */
    public function getSyncFolderId()
    {
        return $this->syncFolderId;
    }

    /**
     * @return string
     */
    public function getSyncState()
    {
        return $this->syncState;
    }

    /**
     * @return \garethp\ews\API\Type\ItemIdType[]
     */
    public function getIgnore()
    {
        return $this->ignore;
    }

    /**
     * @return integer
     */
    public function getMaxChangesReturned()
    {
        return $this->maxChangesReturned;
    }

    /**
     * @return string
     */
    public function getSyncScope()
    {
        return $this->syncScope;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemResponseShapeType
     * @return SyncFolderItemsType
     */
    public function setItemShape(\garethp\ews\API\Type\ItemResponseShapeType $value)
    {
        $this->itemShape = $this->castValueIfNeeded("itemShape", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\TargetFolderIdType
     * @return SyncFolderItemsType
     */
    public function setSyncFolderId(\garethp\ews\API\Type\TargetFolderIdType $value)
    {
        $this->syncFolderId = $this->castValueIfNeeded("syncFolderId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SyncFolderItemsType
     */
    public function setSyncState($value)
    {
        $this->syncState = $this->castValueIfNeeded("syncState", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemIdType[]
     * @return SyncFolderItemsType
     */
    public function setIgnore(array $value)
    {
        $this->ignore = $this->castValueIfNeeded("ignore", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return SyncFolderItemsType
     */
    public function setMaxChangesReturned($value)
    {
        $this->maxChangesReturned = $this->castValueIfNeeded("maxChangesReturned", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SyncFolderItemsType
     */
    public function setSyncScope($value)
    {
        $this->syncScope = $this->castValueIfNeeded("syncScope", $value);
        return $this;
    }
}
