<?php

namespace garethp\ews\API\Message;

/**
 * Class representing UpdateInboxRulesResponseType
 *
 *
 * XSD Type: UpdateInboxRulesResponseType
 *
 * @method UpdateInboxRulesResponseType addRuleOperationErrors(\garethp\ews\API\Type\RuleOperationErrorType $ruleOperationErrors)
 */
class UpdateInboxRulesResponseType extends ResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\RuleOperationErrorType[]
     */
    protected $ruleOperationErrors = null;

    /**
     * @return \garethp\ews\API\Type\RuleOperationErrorType[]
     */
    public function getRuleOperationErrors()
    {
        return $this->ruleOperationErrors;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\RuleOperationErrorType[]
     * @return UpdateInboxRulesResponseType
     */
    public function setRuleOperationErrors(array $value)
    {
        $this->ruleOperationErrors = $this->castValueIfNeeded("ruleOperationErrors", $value);
        return $this;
    }
}
