<?php

namespace garethp\ews\API\Message;

/**
 * Class representing UpdateItemInRecoverableItemsType
 *
 *
 * XSD Type: UpdateItemInRecoverableItemsType
 */
class UpdateItemInRecoverableItemsType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $itemId = null;

    /**
     * @var \garethp\ews\API\Type\NonEmptyArrayOfItemChangeDescriptionsType
     */
    protected $updates = null;

    /**
     * @var \garethp\ews\API\Type\NonEmptyArrayOfAttachmentsType
     */
    protected $attachments = null;

    /**
     * @var boolean
     */
    protected $makeItemImmutable = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ItemIdType
     */
    public function getItemId()
    {
        return $this->itemId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemIdType
     * @return UpdateItemInRecoverableItemsType
     */
    public function setItemId(\garethp\ews\API\Type\ItemIdType $value)
    {
        $this->itemId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\NonEmptyArrayOfItemChangeDescriptionsType
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\NonEmptyArrayOfItemChangeDescriptionsType
     * @return UpdateItemInRecoverableItemsType
     */
    public function setUpdates(\garethp\ews\API\Type\NonEmptyArrayOfItemChangeDescriptionsType $value)
    {
        $this->updates = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\NonEmptyArrayOfAttachmentsType
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\NonEmptyArrayOfAttachmentsType
     * @return UpdateItemInRecoverableItemsType
     */
    public function setAttachments(\garethp\ews\API\Type\NonEmptyArrayOfAttachmentsType $value)
    {
        $this->attachments = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isMakeItemImmutable()
    {
        return ((bool) $this->makeItemImmutable);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getMakeItemImmutable()
    {
        return $this->makeItemImmutable;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return UpdateItemInRecoverableItemsType
     */
    public function setMakeItemImmutable($value)
    {
        $this->makeItemImmutable = $value;
        return $this;
    }
}
