<?php

namespace garethp\ews\API\Message;

/**
 * Class representing UpdateMeetingInstanceRequestType
 *
 *
 * XSD Type: UpdateMeetingInstanceRequestType
 */
class UpdateMeetingInstanceRequestType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $itemId = null;

    /**
     * @var \garethp\ews\API\Type\MeetingInstanceType
     */
    protected $meetingInstance = null;

    /**
     * @var \garethp\ews\API\Type\ContentActivityType[]
     */
    protected $contentActivitiesToAdd = null;

    /**
     * @var \garethp\ews\API\Type\ParticipantActivityType[]
     */
    protected $participantActivitiesToAdd = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ItemIdType
     */
    public function getItemId()
    {
        return $this->itemId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemIdType
     * @return UpdateMeetingInstanceRequestType
     */
    public function setItemId(\garethp\ews\API\Type\ItemIdType $value)
    {
        $this->itemId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\MeetingInstanceType
     */
    public function getMeetingInstance()
    {
        return $this->meetingInstance;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\MeetingInstanceType
     * @return UpdateMeetingInstanceRequestType
     */
    public function setMeetingInstance(\garethp\ews\API\Type\MeetingInstanceType $value)
    {
        $this->meetingInstance = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ContentActivityType
     * @return UpdateMeetingInstanceRequestType
     */
    public function addContentActivitiesToAdd(\garethp\ews\API\Type\ContentActivityType $value)
    {
        if ($this->contentActivitiesToAdd === null) {
                        $this->contentActivitiesToAdd = array();
        }

        if (!is_array($this->contentActivitiesToAdd)) {
            $this->contentActivitiesToAdd = array($this->contentActivitiesToAdd);
        }

        $this->contentActivitiesToAdd[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ContentActivityType[]
     */
    public function getContentActivitiesToAdd()
    {
        return $this->contentActivitiesToAdd;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value
     * \garethp\ews\API\Type\ContentActivityType[]|\garethp\ews\API\Type\ContentActivityType
     * @return UpdateMeetingInstanceRequestType
     */
    public function setContentActivitiesToAdd(array|\garethp\ews\API\Type\ContentActivityType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->contentActivitiesToAdd = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ParticipantActivityType
     * @return UpdateMeetingInstanceRequestType
     */
    public function addParticipantActivitiesToAdd(\garethp\ews\API\Type\ParticipantActivityType $value)
    {
        if ($this->participantActivitiesToAdd === null) {
                        $this->participantActivitiesToAdd = array();
        }

        if (!is_array($this->participantActivitiesToAdd)) {
            $this->participantActivitiesToAdd = array($this->participantActivitiesToAdd);
        }

        $this->participantActivitiesToAdd[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ParticipantActivityType[]
     */
    public function getParticipantActivitiesToAdd()
    {
        return $this->participantActivitiesToAdd;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value
     * \garethp\ews\API\Type\ParticipantActivityType[]|\garethp\ews\API\Type\ParticipantActivityType
     * @return UpdateMeetingInstanceRequestType
     */
    public function setParticipantActivitiesToAdd(array|\garethp\ews\API\Type\ParticipantActivityType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->participantActivitiesToAdd = $value;
        return $this;
    }
}
