<?php

namespace garethp\ews\API\Message;

/**
 * Class representing UpdateItemInRecoverableItemsResponseMessageType
 *
 *
 * XSD Type: UpdateItemInRecoverableItemsResponseMessageType
 */
class UpdateItemInRecoverableItemsResponseMessageType extends ItemInfoResponseMessageType
{

    /**
     * @var \garethp\ews\API\Type\ArrayOfAttachmentsType
     */
    protected $attachments = null;

    /**
     * @var \garethp\ews\API\Type\ConflictResultsType
     */
    protected $conflictResults = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ArrayOfAttachmentsType
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ArrayOfAttachmentsType
     * @return UpdateItemInRecoverableItemsResponseMessageType
     */
    public function setAttachments(\garethp\ews\API\Type\ArrayOfAttachmentsType $value)
    {
        $this->attachments = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ConflictResultsType
     */
    public function getConflictResults()
    {
        return $this->conflictResults;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ConflictResultsType
     * @return UpdateItemInRecoverableItemsResponseMessageType
     */
    public function setConflictResults(\garethp\ews\API\Type\ConflictResultsType $value)
    {
        $this->conflictResults = $value;
        return $this;
    }
}
