<?php

namespace garethp\ews\API\Message;

/**
 * Class representing UpdateDelegateType
 *
 *
 * XSD Type: UpdateDelegateType
 *
 * @method UpdateDelegateType addDelegateUsers(\garethp\ews\API\Type\DelegateUserType $delegateUsers)
 */
class UpdateDelegateType extends BaseDelegateType
{

    /**
     * @var \garethp\ews\API\Type\DelegateUserType[]
     */
    protected $delegateUsers = null;

    /**
     * @var string
     */
    protected $deliverMeetingRequests = null;

    /**
     * @return \garethp\ews\API\Type\DelegateUserType[]
     */
    public function getDelegateUsers()
    {
        return $this->delegateUsers;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\DelegateUserType[]
     * @return UpdateDelegateType
     */
    public function setDelegateUsers(array $value)
    {
        $this->delegateUsers = $this->castValueIfNeeded("delegateUsers", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getDeliverMeetingRequests()
    {
        return $this->deliverMeetingRequests;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UpdateDelegateType
     */
    public function setDeliverMeetingRequests($value)
    {
        $this->deliverMeetingRequests = $this->castValueIfNeeded("deliverMeetingRequests", $value);
        return $this;
    }
}
