<?php

namespace garethp\ews\API\Message;

/**
 * Class representing UploadItemsType
 *
 *
 * XSD Type: UploadItemsType
 */
class UploadItemsType extends BaseRequestType
{

    /**
     * @var \garethp\ews\API\Type\UploadItemType[]
     */
    protected $items = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\UploadItemType
     * @return UploadItemsType
     */
    public function addItems(\garethp\ews\API\Type\UploadItemType $value)
    {
        $value = $this->castValueIfNeeded("items", $value);

        if ($this->items === null) {
            $this->items = array();
        }

        if (!is_array($this->items)) {
            $this->items = array($this->items);
        }

        $this->items[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\UploadItemType[]
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\UploadItemType[]
     * @return UploadItemsType
     */
    public function setItems(array $value)
    {
        $this->items = $this->castValueIfNeeded("items", $value);
        return $this;
    }
}
