<?php

namespace garethp\ews\API\Type\SearchResultsType;

use garethp\ews\API\Type\SearchResultsType;

/**
 * Class representing ItemsAType
 */
class ItemsAType extends SearchResultsType
{

    /**
     * @var \garethp\ews\API\Type\ItemType[]
     */
    protected $item = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemType
     * @return ItemsAType
     */
    public function addItem(\garethp\ews\API\Type\ItemType $value)
    {
        if ($this->item === null) {
                        $this->item = array();
        }

        if (!is_array($this->item)) {
            $this->item = array($this->item);
        }

        $this->item[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Type\ItemType[]
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Type\ItemType[]|\garethp\ews\API\Type\ItemType
     * @return ItemsAType
     */
    public function setItem(array|\garethp\ews\API\Type\ItemType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->item = $value;
        return $this;
    }
}
