<?php

namespace garethp\ews\API\Type\SearchDiagnosticsStepType;

/**
 * Class representing AdditionalEntriesAType
 */
class AdditionalEntriesAType
{

    /**
     * @var string[]
     */
    protected $entry = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AdditionalEntriesAType
     */
    public function addEntry($value)
    {
        if ($this->entry === null) {
                        $this->entry = array();
        }

        if (!is_array($this->entry)) {
            $this->entry = array($this->entry);
        }

        $this->entry[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getEntry()
    {
        return $this->entry;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return AdditionalEntriesAType
     */
    public function setEntry(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->entry = $value;
        return $this;
    }
}
