<?php

namespace garethp\ews\API\Type;

/**
 * Class representing AlternateIdType
 *
 * Represents an alternate mailbox folder or item Id.
 * XSD Type: AlternateIdType
 */
class AlternateIdType extends AlternateIdBaseType
{

    /**
     * @var string
     */
    protected $id = null;

    /**
     * @var string
     */
    protected $mailbox = null;

    /**
     * @var boolean
     */
    protected $isArchive = null;

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AlternateIdType
     */
    public function setId($value)
    {
        $this->id = $this->castValueIfNeeded("id", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getMailbox()
    {
        return $this->mailbox;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AlternateIdType
     */
    public function setMailbox($value)
    {
        $this->mailbox = $this->castValueIfNeeded("mailbox", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isArchive()
    {
        return ((bool) $this->isArchive);
    }

    /**
     * @return boolean
     */
    public function getIsArchive()
    {
        return $this->isArchive;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return AlternateIdType
     */
    public function setIsArchive($value)
    {
        $this->isArchive = $this->castValueIfNeeded("isArchive", $value);
        return $this;
    }
}
