<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing AppType
 *
 *
 * XSD Type: AppType
 */
class AppType extends Type
{

    /**
     * @var \garethp\ews\API\Type\AppMetadataType
     */
    protected $metadata = null;

    /**
     * @var string
     */
    protected $manifest = null;

    /**
     * @autogenerated This method is safe to replace
     * @return AppMetadataType
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AppMetadataType
     * @return AppType
     */
    public function setMetadata(AppMetadataType $value)
    {
        $this->metadata = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getManifest()
    {
        return $this->manifest;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AppType
     */
    public function setManifest($value)
    {
        $this->manifest = $value;
        return $this;
    }
}
