<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ArrayOfAttendeeConflictDataType
 *
 *
 * XSD Type: ArrayOfAttendeeConflictData
 *
 * @method ArrayOfAttendeeConflictDataType addUnknownAttendeeConflictData(UnknownAttendeeConflictDataType $unknownAttendeeConflictData)
 * @method ArrayOfAttendeeConflictDataType addIndividualAttendeeConflictData(IndividualAttendeeConflictDataType $individualAttendeeConflictData)
 * @method ArrayOfAttendeeConflictDataType addTooBigGroupAttendeeConflictData(TooBigGroupAttendeeConflictDataType $tooBigGroupAttendeeConflictData)
 * @method ArrayOfAttendeeConflictDataType addGroupAttendeeConflictData(GroupAttendeeConflictDataType $groupAttendeeConflictData)
 */
class ArrayOfAttendeeConflictDataType extends Type
{

    /**
     * @var \garethp\ews\API\Type\UnknownAttendeeConflictDataType[]
     */
    protected $unknownAttendeeConflictData = null;

    /**
     * @var \garethp\ews\API\Type\IndividualAttendeeConflictDataType[]
     */
    protected $individualAttendeeConflictData = null;

    /**
     * @var \garethp\ews\API\Type\TooBigGroupAttendeeConflictDataType[]
     */
    protected $tooBigGroupAttendeeConflictData = null;

    /**
     * @var \garethp\ews\API\Type\GroupAttendeeConflictDataType[]
     */
    protected $groupAttendeeConflictData = null;

    /**
     * @return UnknownAttendeeConflictDataType[]
     */
    public function getUnknownAttendeeConflictData()
    {
        return $this->unknownAttendeeConflictData;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value UnknownAttendeeConflictDataType[]
     * @return ArrayOfAttendeeConflictDataType
     */
    public function setUnknownAttendeeConflictData(array $value)
    {
        $this->unknownAttendeeConflictData = $this->castValueIfNeeded("unknownAttendeeConflictData", $value);
        return $this;
    }

    /**
     * @return IndividualAttendeeConflictDataType[]
     */
    public function getIndividualAttendeeConflictData()
    {
        return $this->individualAttendeeConflictData;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value IndividualAttendeeConflictDataType[]
     * @return ArrayOfAttendeeConflictDataType
     */
    public function setIndividualAttendeeConflictData(array $value)
    {
        $this->individualAttendeeConflictData = $this->castValueIfNeeded("individualAttendeeConflictData", $value);
        return $this;
    }

    /**
     * @return TooBigGroupAttendeeConflictDataType[]
     */
    public function getTooBigGroupAttendeeConflictData()
    {
        return $this->tooBigGroupAttendeeConflictData;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TooBigGroupAttendeeConflictDataType[]
     * @return ArrayOfAttendeeConflictDataType
     */
    public function setTooBigGroupAttendeeConflictData(array $value)
    {
        $this->tooBigGroupAttendeeConflictData = $this->castValueIfNeeded("tooBigGroupAttendeeConflictData", $value);
        return $this;
    }

    /**
     * @return GroupAttendeeConflictDataType[]
     */
    public function getGroupAttendeeConflictData()
    {
        return $this->groupAttendeeConflictData;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value GroupAttendeeConflictDataType[]
     * @return ArrayOfAttendeeConflictDataType
     */
    public function setGroupAttendeeConflictData(array $value)
    {
        $this->groupAttendeeConflictData = $this->castValueIfNeeded("groupAttendeeConflictData", $value);
        return $this;
    }
}
