<?php

namespace garethp\ews\API\Type;

use Countable;
use ArrayAccess;
use IteratorAggregate;
use garethp\ews\API\Type;

/**
 * Class representing ArrayOfFoldersType
 *
 *
 * XSD Type: ArrayOfFoldersType
 *
 * @method ArrayOfFoldersType addFolder(FolderType $folder)
 * @method ArrayOfFoldersType addCalendarFolder(CalendarFolderType $calendarFolder)
 * @method ArrayOfFoldersType addContactsFolder(ContactsFolderType $contactsFolder)
 * @method ArrayOfFoldersType addSearchFolder(SearchFolderType $searchFolder)
 * @method ArrayOfFoldersType addTasksFolder(TasksFolderType $tasksFolder)
 */
class ArrayOfFoldersType extends Type implements Countable, ArrayAccess, IteratorAggregate
{

    protected $allFolders = null;

    /**
     * @var \garethp\ews\API\Type\FolderType[]
     */
    protected $folder = null;

    /**
     * @var \garethp\ews\API\Type\CalendarFolderType[]
     */
    protected $calendarFolder = null;

    /**
     * @var \garethp\ews\API\Type\ContactsFolderType[]
     */
    protected $contactsFolder = null;

    /**
     * @var \garethp\ews\API\Type\SearchFolderType[]
     */
    protected $searchFolder = null;

    /**
     * @var \garethp\ews\API\Type\TasksFolderType[]
     */
    protected $tasksFolder = null;

    public function getAllFolders()
    {
        if ($this->allFolders !== null) {
            return $this->allFolders;
        }

        $folders = array();
        if ($this->folder !== null) {
            $folders = array_merge($folders, (is_array($this->folder) ? $this->folder : array($this->folder)));
        }

        if ($this->calendarFolder !== null) {
            $folders = array_merge(
                $folders,
                (is_array($this->calendarFolder) ? $this->calendarFolder : array($this->calendarFolder))
            );
        }

        if ($this->contactsFolder !== null) {
            $folders = array_merge(
                $folders,
                (is_array($this->contactsFolder) ? $this->contactsFolder : array($this->contactsFolder))
            );
        }

        if ($this->searchFolder !== null) {
            $folders = array_merge(
                $folders,
                (is_array($this->searchFolder) ? $this->searchFolder : array($this->searchFolder))
            );
        }

        if ($this->tasksFolder !== null) {
            $folders = array_merge(
                $folders,
                (is_array($this->tasksFolder) ? $this->tasksFolder : array($this->tasksFolder))
            );
        }

        $this->allFolders = $folders;
        return $this->allFolders;
    }

    #[\ReturnTypeWillChange]
    public function count()
    {
        return count($this->getAllFolders());
    }

    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->getAllFolders()[$offset]);
    }

    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        $this->getAllFolders();
        return isset($this->allFolders[$offset]) ? $this->allFolders[$offset] : null;
    }

    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        $this->getAllFolders();

        if (is_null($offset)) {
            $this->allFolders[] = $value;
        } else {
            $this->allFolders[$offset] = $value;
        }
    }

    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        $this->getAllFolders();
        unset($this->allFolders[$offset]);
    }

    #[\ReturnTypeWillChange]
    public function getIterator()
    {
        $this->getAllFolders();
        return new \ArrayIterator($this->allFolders);
    }

    /**
     * @return FolderType[]
     */
    public function getFolder()
    {
        return $this->folder;
    }

    /**
     * @return CalendarFolderType[]
     */
    public function getCalendarFolder()
    {
        return $this->calendarFolder;
    }

    /**
     * @return ContactsFolderType[]
     */
    public function getContactsFolder()
    {
        return $this->contactsFolder;
    }

    /**
     * @return SearchFolderType[]
     */
    public function getSearchFolder()
    {
        return $this->searchFolder;
    }

    /**
     * @return TasksFolderType[]
     */
    public function getTasksFolder()
    {
        return $this->tasksFolder;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value FolderType[]
     * @return ArrayOfFoldersType
     */
    public function setFolder(array $value)
    {
        $this->folder = $this->castValueIfNeeded("folder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CalendarFolderType[]
     * @return ArrayOfFoldersType
     */
    public function setCalendarFolder(array $value)
    {
        $this->calendarFolder = $this->castValueIfNeeded("calendarFolder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ContactsFolderType[]
     * @return ArrayOfFoldersType
     */
    public function setContactsFolder(array $value)
    {
        $this->contactsFolder = $this->castValueIfNeeded("contactsFolder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SearchFolderType[]
     * @return ArrayOfFoldersType
     */
    public function setSearchFolder(array $value)
    {
        $this->searchFolder = $this->castValueIfNeeded("searchFolder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TasksFolderType[]
     * @return ArrayOfFoldersType
     */
    public function setTasksFolder(array $value)
    {
        $this->tasksFolder = $this->castValueIfNeeded("tasksFolder", $value);
        return $this;
    }
}
