<?php

namespace garethp\ews\API\Type;

use Countable;
use ArrayAccess;
use IteratorAggregate;
use garethp\ews\API\Type;

/**
 * Class representing ArrayOfRealItemsType
 *
 *
 * XSD Type: ArrayOfRealItemsType
 *
 * @method ArrayOfRealItemsType addItem(ItemType $item)
 * @method ArrayOfRealItemsType addMessage(MessageType $message)
 * @method ArrayOfRealItemsType addCalendarItem(CalendarItemType $calendarItem)
 * @method ArrayOfRealItemsType addContact(ContactItemType $contact)
 * @method ArrayOfRealItemsType addDistributionList(DistributionListType $distributionList)
 * @method ArrayOfRealItemsType addMeetingMessage(MeetingMessageType $meetingMessage)
 * @method ArrayOfRealItemsType addMeetingRequest(MeetingRequestMessageType $meetingRequest)
 * @method ArrayOfRealItemsType addMeetingResponse(MeetingResponseMessageType $meetingResponse)
 * @method ArrayOfRealItemsType addMeetingCancellation(MeetingCancellationMessageType $meetingCancellation)
 * @method ArrayOfRealItemsType addTask(TaskType $task)
 * @method ArrayOfRealItemsType addPostItem(PostItemType $postItem)
 */
class ArrayOfRealItemsType extends Type implements Countable, ArrayAccess, IteratorAggregate
{

    /**
     * @var \garethp\ews\API\Type\ItemType[]
     */
    protected $item = null;

    /**
     * @var \garethp\ews\API\Type\MessageType[]
     */
    protected $message = null;

    /**
     * @var \garethp\ews\API\Type\CalendarItemType[]
     */
    protected $calendarItem = null;

    /**
     * @var \garethp\ews\API\Type\ContactItemType[]
     */
    protected $contact = null;

    /**
     * @var \garethp\ews\API\Type\DistributionListType[]
     */
    protected $distributionList = null;

    /**
     * @var \garethp\ews\API\Type\MeetingMessageType[]
     */
    protected $meetingMessage = null;

    /**
     * @var \garethp\ews\API\Type\MeetingRequestMessageType[]
     */
    protected $meetingRequest = null;

    /**
     * @var \garethp\ews\API\Type\MeetingResponseMessageType[]
     */
    protected $meetingResponse = null;

    /**
     * @var \garethp\ews\API\Type\MeetingCancellationMessageType[]
     */
    protected $meetingCancellation = null;

    /**
     * @var \garethp\ews\API\Type\TaskType[]
     */
    protected $task = null;

    /**
     * @var \garethp\ews\API\Type\PostItemType[]
     */
    protected $postItem = null;

    private $itemsArray = null;

    public function getItems()
    {
        if ($this->itemsArray) {
            return $this->itemsArray;
        }

        $items = array();

        foreach (get_object_vars($this) as $key => $value) {
            if ($key == "itemsArray" || substr($key, 0, 1) == "_" || $value === null) {
                continue;
            }

            if (!is_array($value)) {
                $value = array($value);
            }

            $items = array_merge($items, $value);
        }

        $this->itemsArray = $items;
        return $this->itemsArray;
    }

    public function count()
    {
        return count($this->getItems());
    }

    public function offsetExists($offset)
    {
        return isset($this->getItems()[$offset]);
    }

    public function offsetGet($offset)
    {
        $this->getItems();
        return isset($this->itemsArray[$offset]) ? $this->itemsArray[$offset] : null;
    }

    public function offsetSet($offset, $value)
    {
        $this->getItems();

        if (is_null($offset)) {
            $this->itemsArray[] = $value;
        } else {
            $this->itemsArray[$offset] = $value;
        }
    }

    public function offsetUnset($offset)
    {
        $this->getItems();
        unset($this->itemsArray[$offset]);
    }

    public function getIterator()
    {
        $this->getItems();
        return new \ArrayIterator($this->itemsArray);
    }

    /**
     * @return ItemType[]
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ItemType[]
     * @return ArrayOfRealItemsType
     */
    public function setItem(array $value)
    {
        $this->item = $this->castValueIfNeeded("item", $value);
        return $this;
    }

    /**
     * @return MessageType[]
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MessageType[]
     * @return ArrayOfRealItemsType
     */
    public function setMessage(array $value)
    {
        $this->message = $this->castValueIfNeeded("message", $value);
        return $this;
    }

    /**
     * @return CalendarItemType[]
     */
    public function getCalendarItem()
    {
        return $this->calendarItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CalendarItemType[]
     * @return ArrayOfRealItemsType
     */
    public function setCalendarItem(array $value)
    {
        $this->calendarItem = $this->castValueIfNeeded("calendarItem", $value);
        return $this;
    }

    /**
     * @return ContactItemType[]
     */
    public function getContact()
    {
        return $this->contact;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ContactItemType[]
     * @return ArrayOfRealItemsType
     */
    public function setContact(array $value)
    {
        $this->contact = $this->castValueIfNeeded("contact", $value);
        return $this;
    }

    /**
     * @return DistributionListType[]
     */
    public function getDistributionList()
    {
        return $this->distributionList;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value DistributionListType[]
     * @return ArrayOfRealItemsType
     */
    public function setDistributionList(array $value)
    {
        $this->distributionList = $this->castValueIfNeeded("distributionList", $value);
        return $this;
    }

    /**
     * @return MeetingMessageType[]
     */
    public function getMeetingMessage()
    {
        return $this->meetingMessage;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MeetingMessageType[]
     * @return ArrayOfRealItemsType
     */
    public function setMeetingMessage(array $value)
    {
        $this->meetingMessage = $this->castValueIfNeeded("meetingMessage", $value);
        return $this;
    }

    /**
     * @return MeetingRequestMessageType[]
     */
    public function getMeetingRequest()
    {
        return $this->meetingRequest;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MeetingRequestMessageType[]
     * @return ArrayOfRealItemsType
     */
    public function setMeetingRequest(array $value)
    {
        $this->meetingRequest = $this->castValueIfNeeded("meetingRequest", $value);
        return $this;
    }

    /**
     * @return MeetingResponseMessageType[]
     */
    public function getMeetingResponse()
    {
        return $this->meetingResponse;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MeetingResponseMessageType[]
     * @return ArrayOfRealItemsType
     */
    public function setMeetingResponse(array $value)
    {
        $this->meetingResponse = $this->castValueIfNeeded("meetingResponse", $value);
        return $this;
    }

    /**
     * @return MeetingCancellationMessageType[]
     */
    public function getMeetingCancellation()
    {
        return $this->meetingCancellation;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MeetingCancellationMessageType[]
     * @return ArrayOfRealItemsType
     */
    public function setMeetingCancellation(array $value)
    {
        $this->meetingCancellation = $this->castValueIfNeeded("meetingCancellation", $value);
        return $this;
    }

    /**
     * @return TaskType[]
     */
    public function getTask()
    {
        return $this->task;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TaskType[]
     * @return ArrayOfRealItemsType
     */
    public function setTask(array $value)
    {
        $this->task = $this->castValueIfNeeded("task", $value);
        return $this;
    }

    /**
     * @return PostItemType[]
     */
    public function getPostItem()
    {
        return $this->postItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PostItemType[]
     * @return ArrayOfRealItemsType
     */
    public function setPostItem(array $value)
    {
        $this->postItem = $this->castValueIfNeeded("postItem", $value);
        return $this;
    }
}
