<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ArrayOfTrackingPropertiesType
 *
 *
 * XSD Type: ArrayOfTrackingPropertiesType
 *
 * @method ArrayOfTrackingPropertiesType addTrackingPropertyType(TrackingPropertyType $trackingPropertyType)
 */
class ArrayOfTrackingPropertiesType extends Type
{

    /**
     * @var \garethp\ews\API\Type\TrackingPropertyType[]
     */
    protected $trackingPropertyType = null;

    /**
     * @autogenerated This method is safe to replace
     * @return TrackingPropertyType[]
     */
    public function getTrackingPropertyType()
    {
        return $this->trackingPropertyType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TrackingPropertyType[]
     * @return ArrayOfTrackingPropertiesType
     */
    public function setTrackingPropertyType(array $value)
    {
        $this->trackingPropertyType = $this->castValueIfNeeded("trackingPropertyType", $value);
        return $this;
    }
}
