<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing AttachmentType
 *
 *
 * XSD Type: AttachmentType
 */
class AttachmentType extends Type
{

    /**
     * @var \garethp\ews\API\Type\AttachmentIdType
     */
    protected $attachmentId = null;

    /**
     * @var string
     */
    protected $name = null;

    /**
     * @var string
     */
    protected $contentType = null;

    /**
     * @var string
     */
    protected $contentId = null;

    /**
     * @var string
     */
    protected $contentLocation = null;

    /**
     * @var integer
     */
    protected $size = null;

    /**
     * @var \DateTime
     */
    protected $lastModifiedTime = null;

    protected $_typeMap = array(
        'lastModifiedTime' => 'dateTime',
    );

    /**
     * @var boolean
     */
    protected $isInline = null;

    /**
     * @return AttachmentIdType
     */
    public function getAttachmentId()
    {
        return $this->attachmentId;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getContentType()
    {
        return $this->contentType;
    }

    /**
     * @return string
     */
    public function getContentId()
    {
        return $this->contentId;
    }

    /**
     * @return string
     */
    public function getContentLocation()
    {
        return $this->contentLocation;
    }

    /**
     * @return integer
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * @return \DateTime
     */
    public function getLastModifiedTime()
    {
        return $this->lastModifiedTime;
    }

    /**
     * @return boolean
     */
    public function getIsInline()
    {
        return $this->isInline;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AttachmentIdType
     * @return AttachmentType
     */
    public function setAttachmentId(AttachmentIdType $value)
    {
        $this->attachmentId = $this->castValueIfNeeded("attachmentId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AttachmentType
     */
    public function setName($value)
    {
        $this->name = $this->castValueIfNeeded("name", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AttachmentType
     */
    public function setContentType($value)
    {
        $this->contentType = $this->castValueIfNeeded("contentType", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AttachmentType
     */
    public function setContentId($value)
    {
        $this->contentId = $this->castValueIfNeeded("contentId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return AttachmentType
     */
    public function setContentLocation($value)
    {
        $this->contentLocation = $this->castValueIfNeeded("contentLocation", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return AttachmentType
     */
    public function setSize($value)
    {
        $this->size = $this->castValueIfNeeded("size", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return AttachmentType
     */
    public function setLastModifiedTime(\DateTime|string $value)
    {
        $this->lastModifiedTime = $this->castValueIfNeeded("lastModifiedTime", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isInline()
    {
        return ((bool) $this->isInline);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return AttachmentType
     */
    public function setIsInline($value)
    {
        $this->isInline = $this->castValueIfNeeded("isInline", $value);
        return $this;
    }
}
