<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing BodyContentAttributedValueType
 *
 *
 * XSD Type: BodyContentAttributedValueType
 */
class BodyContentAttributedValueType extends Type
{

    /**
     * @var \garethp\ews\API\Type\BodyContentType
     */
    protected $value = null;

    /**
     * @var string[]
     */
    protected $attributions = null;

    /**
     * @autogenerated This method is safe to replace
     * @return BodyContentType
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value BodyContentType
     * @return BodyContentAttributedValueType
     */
    public function setValue(BodyContentType $value)
    {
        $this->value = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return BodyContentAttributedValueType
     */
    public function addAttributions($value)
    {
        if ($this->attributions === null) {
                        $this->attributions = array();
        }

        if (!is_array($this->attributions)) {
            $this->attributions = array($this->attributions);
        }

        $this->attributions[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getAttributions()
    {
        return $this->attributions;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return BodyContentAttributedValueType
     */
    public function setAttributions(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->attributions = $value;
        return $this;
    }
}
