<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ClientAccessTokenRequestType
 *
 *
 * XSD Type: ClientAccessTokenRequestType
 */
class ClientAccessTokenRequestType extends Type
{

    /**
     * @var string
     */
    protected $id = null;

    /**
     * @var string
     */
    protected $tokenType = null;

    /**
     * @var string
     */
    protected $scope = null;

    /**
     * @var string
     */
    protected $resourceUri = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ClientAccessTokenRequestType
     */
    public function setId($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTokenType()
    {
        return $this->tokenType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ClientAccessTokenRequestType
     */
    public function setTokenType($value)
    {
        $this->tokenType = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ClientAccessTokenRequestType
     */
    public function setScope($value)
    {
        $this->scope = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getResourceUri()
    {
        return $this->resourceUri;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ClientAccessTokenRequestType
     */
    public function setResourceUri($value)
    {
        $this->resourceUri = $value;
        return $this;
    }
}
