<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ClientAccessTokenType
 *
 *
 * XSD Type: ClientAccessTokenType
 */
class ClientAccessTokenType extends Type
{

    /**
     * @var string
     */
    protected $id = null;

    /**
     * @var string
     */
    protected $tokenType = null;

    /**
     * @var string
     */
    protected $tokenValue = null;

    /**
     * @var integer
     */
    protected $tTL = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ClientAccessTokenType
     */
    public function setId($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTokenType()
    {
        return $this->tokenType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ClientAccessTokenType
     */
    public function setTokenType($value)
    {
        $this->tokenType = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTokenValue()
    {
        return $this->tokenValue;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ClientAccessTokenType
     */
    public function setTokenValue($value)
    {
        $this->tokenValue = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getTTL()
    {
        return $this->tTL;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ClientAccessTokenType
     */
    public function setTTL($value)
    {
        $this->tTL = $value;
        return $this;
    }
}
