<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing CompleteNameType
 *
 *
 * XSD Type: CompleteNameType
 */
class CompleteNameType extends Type
{

    /**
     * @var string
     */
    protected $title = null;

    /**
     * @var string
     */
    protected $firstName = null;

    /**
     * @var string
     */
    protected $middleName = null;

    /**
     * @var string
     */
    protected $lastName = null;

    /**
     * @var string
     */
    protected $suffix = null;

    /**
     * @var string
     */
    protected $initials = null;

    /**
     * @var string
     */
    protected $fullName = null;

    /**
     * @var string
     */
    protected $nickname = null;

    /**
     * @var string
     */
    protected $yomiFirstName = null;

    /**
     * @var string
     */
    protected $yomiLastName = null;

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setTitle($value)
    {
        $this->title = $this->castValueIfNeeded("title", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setFirstName($value)
    {
        $this->firstName = $this->castValueIfNeeded("firstName", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getMiddleName()
    {
        return $this->middleName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setMiddleName($value)
    {
        $this->middleName = $this->castValueIfNeeded("middleName", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setLastName($value)
    {
        $this->lastName = $this->castValueIfNeeded("lastName", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getSuffix()
    {
        return $this->suffix;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setSuffix($value)
    {
        $this->suffix = $this->castValueIfNeeded("suffix", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getInitials()
    {
        return $this->initials;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setInitials($value)
    {
        $this->initials = $this->castValueIfNeeded("initials", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getFullName()
    {
        return $this->fullName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setFullName($value)
    {
        $this->fullName = $this->castValueIfNeeded("fullName", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setNickname($value)
    {
        $this->nickname = $this->castValueIfNeeded("nickname", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getYomiFirstName()
    {
        return $this->yomiFirstName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setYomiFirstName($value)
    {
        $this->yomiFirstName = $this->castValueIfNeeded("yomiFirstName", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getYomiLastName()
    {
        return $this->yomiLastName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return CompleteNameType
     */
    public function setYomiLastName($value)
    {
        $this->yomiLastName = $this->castValueIfNeeded("yomiLastName", $value);
        return $this;
    }
}
