<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ContactUrlDictionaryEntryType
 *
 *
 * XSD Type: ContactUrlDictionaryEntryType
 */
class ContactUrlDictionaryEntryType extends Type
{

    /**
     * @var string
     */
    protected $type = null;

    /**
     * @var string
     */
    protected $name = null;

    /**
     * @var string
     */
    protected $address = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ContactUrlDictionaryEntryType
     */
    public function setType($value)
    {
        $this->type = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ContactUrlDictionaryEntryType
     */
    public function setName($value)
    {
        $this->name = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ContactUrlDictionaryEntryType
     */
    public function setAddress($value)
    {
        $this->address = $value;
        return $this;
    }
}
