<?php

namespace garethp\ews\API\Type;

/**
 * Class representing ContactsFolderType
 *
 *
 * XSD Type: ContactsFolderType
 */
class ContactsFolderType extends BaseFolderType
{

    /**
     * @var string
     */
    protected $sharingEffectiveRights = null;

    /**
     * @var \garethp\ews\API\Type\PermissionSetType
     */
    protected $permissionSet = null;

    /**
     * @return string
     */
    public function getSharingEffectiveRights()
    {
        return $this->sharingEffectiveRights;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ContactsFolderType
     */
    public function setSharingEffectiveRights($value)
    {
        $this->sharingEffectiveRights = $this->castValueIfNeeded("sharingEffectiveRights", $value);
        return $this;
    }

    /**
     * @return PermissionSetType
     */
    public function getPermissionSet()
    {
        return $this->permissionSet;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PermissionSetType
     * @return ContactsFolderType
     */
    public function setPermissionSet(PermissionSetType $value)
    {
        $this->permissionSet = $this->castValueIfNeeded("permissionSet", $value);
        return $this;
    }
}
