<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ConversationActionType
 *
 *
 * XSD Type: ConversationActionType
 *
 * @method ConversationActionType addCategories(string $categories)
 */
class ConversationActionType extends Type
{

    /**
     * @var string
     */
    protected $action = null;

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $conversationId = null;

    /**
     * @var \garethp\ews\API\Type\TargetFolderIdType
     */
    protected $contextFolderId = null;

    /**
     * @var \DateTime
     */
    protected $conversationLastSyncTime = null;

    protected $_typeMap = array(
        'conversationLastSyncTime' => 'dateTime',
    );

    /**
     * @var boolean
     */
    protected $processRightAway = null;

    /**
     * @var \garethp\ews\API\Type\TargetFolderIdType
     */
    protected $destinationFolderId = null;

    /**
     * @var string[]
     */
    protected $categories = null;

    /**
     * @var boolean
     */
    protected $enableAlwaysDelete = null;

    /**
     * @var boolean
     */
    protected $isRead = null;

    /**
     * @var string
     */
    protected $deleteType = null;

    /**
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * @return ItemIdType
     */
    public function getConversationId()
    {
        return $this->conversationId;
    }

    /**
     * @return TargetFolderIdType
     */
    public function getContextFolderId()
    {
        return $this->contextFolderId;
    }

    /**
     * @return \DateTime
     */
    public function getConversationLastSyncTime()
    {
        return $this->conversationLastSyncTime;
    }

    /**
     * @return boolean
     */
    public function getProcessRightAway()
    {
        return $this->processRightAway;
    }

    /**
     * @return TargetFolderIdType
     */
    public function getDestinationFolderId()
    {
        return $this->destinationFolderId;
    }

    /**
     * @return string[]
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * @return boolean
     */
    public function getEnableAlwaysDelete()
    {
        return $this->enableAlwaysDelete;
    }

    /**
     * @return boolean
     */
    public function getIsRead()
    {
        return $this->isRead;
    }

    /**
     * @return string
     */
    public function getDeleteType()
    {
        return $this->deleteType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ConversationActionType
     */
    public function setAction($value)
    {
        $this->action = $this->castValueIfNeeded("action", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ItemIdType
     * @return ConversationActionType
     */
    public function setConversationId(ItemIdType $value)
    {
        $this->conversationId = $this->castValueIfNeeded("conversationId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TargetFolderIdType
     * @return ConversationActionType
     */
    public function setContextFolderId(TargetFolderIdType $value)
    {
        $this->contextFolderId = $this->castValueIfNeeded("contextFolderId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return ConversationActionType
     */
    public function setConversationLastSyncTime(\DateTime|string $value)
    {
        $this->conversationLastSyncTime = $this->castValueIfNeeded("conversationLastSyncTime", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isProcessRightAway()
    {
        return ((bool) $this->processRightAway);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ConversationActionType
     */
    public function setProcessRightAway($value)
    {
        $this->processRightAway = $this->castValueIfNeeded("processRightAway", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TargetFolderIdType
     * @return ConversationActionType
     */
    public function setDestinationFolderId(TargetFolderIdType $value)
    {
        $this->destinationFolderId = $this->castValueIfNeeded("destinationFolderId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return ConversationActionType
     */
    public function setCategories(array $value)
    {
        $this->categories = $this->castValueIfNeeded("categories", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isEnableAlwaysDelete()
    {
        return ((bool) $this->enableAlwaysDelete);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ConversationActionType
     */
    public function setEnableAlwaysDelete($value)
    {
        $this->enableAlwaysDelete = $this->castValueIfNeeded("enableAlwaysDelete", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isRead()
    {
        return ((bool) $this->isRead);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ConversationActionType
     */
    public function setIsRead($value)
    {
        $this->isRead = $this->castValueIfNeeded("isRead", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ConversationActionType
     */
    public function setDeleteType($value)
    {
        $this->deleteType = $this->castValueIfNeeded("deleteType", $value);
        return $this;
    }
}
