<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ConversationResponseShapeType
 *
 *
 * XSD Type: ConversationResponseShapeType
 */
class ConversationResponseShapeType extends Type
{

    /**
     * @var string
     */
    protected $baseShape = null;

    /**
     * @var \garethp\ews\API\Type\NonEmptyArrayOfPathsToElementType
     */
    protected $additionalProperties = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getBaseShape()
    {
        return $this->baseShape;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ConversationResponseShapeType
     */
    public function setBaseShape($value)
    {
        $this->baseShape = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return NonEmptyArrayOfPathsToElementType
     */
    public function getAdditionalProperties()
    {
        return $this->additionalProperties;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value NonEmptyArrayOfPathsToElementType
     * @return ConversationResponseShapeType
     */
    public function setAdditionalProperties(NonEmptyArrayOfPathsToElementType $value)
    {
        $this->additionalProperties = $value;
        return $this;
    }
}
