<?php

namespace garethp\ews\API\Type;

/**
 * Class representing DelveItemType
 *
 *
 * XSD Type: DelveItemType
 */
class DelveItemType extends ItemType
{

    /**
     * @var string
     */
    protected $graphNodeLogicalId = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getGraphNodeLogicalId()
    {
        return $this->graphNodeLogicalId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return DelveItemType
     */
    public function setGraphNodeLogicalId($value)
    {
        $this->graphNodeLogicalId = $value;
        return $this;
    }
}
