<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing DelveSearchScopeType
 *
 *
 * XSD Type: DelveSearchScopeType
 */
class DelveSearchScopeType extends Type
{

    /**
     * @var string[]
     */
    protected $delveView = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return DelveSearchScopeType
     */
    public function addDelveView($value)
    {
        if ($this->delveView === null) {
                        $this->delveView = array();
        }

        if (!is_array($this->delveView)) {
            $this->delveView = array($this->delveView);
        }

        $this->delveView[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getDelveView()
    {
        return $this->delveView;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return DelveSearchScopeType
     */
    public function setDelveView(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->delveView = $value;
        return $this;
    }
}
