<?php

namespace garethp\ews\API\Type;

/**
 * Class representing DistributionListType
 *
 *
 * XSD Type: DistributionListType
 *
 * @method DistributionListType addMembers(MemberType $members)
 */
class DistributionListType extends ItemType
{

    /**
     * @var string
     */
    protected $displayName = null;

    /**
     * @var string
     */
    protected $fileAs = null;

    /**
     * @var string
     */
    protected $contactSource = null;

    /**
     * @var \garethp\ews\API\Type\MemberType[]
     */
    protected $members = null;

    /**
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return DistributionListType
     */
    public function setDisplayName($value)
    {
        $this->displayName = $this->castValueIfNeeded("displayName", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getFileAs()
    {
        return $this->fileAs;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return DistributionListType
     */
    public function setFileAs($value)
    {
        $this->fileAs = $this->castValueIfNeeded("fileAs", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getContactSource()
    {
        return $this->contactSource;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return DistributionListType
     */
    public function setContactSource($value)
    {
        $this->contactSource = $this->castValueIfNeeded("contactSource", $value);
        return $this;
    }

    /**
     * @return MemberType[]
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MemberType[]
     * @return DistributionListType
     */
    public function setMembers(array $value)
    {
        $this->members = $this->castValueIfNeeded("members", $value);
        return $this;
    }
}
