<?php

namespace garethp\ews\API\Type;

/**
 * Class representing EmailAddressExtendedType
 *
 * Extends EmailAddress by adding the external object id
 * XSD Type: EmailAddressExtendedType
 */
class EmailAddressExtendedType extends EmailAddressType
{

    /**
     * @var string
     */
    protected $externalObjectId = null;

    /**
     * @var string
     */
    protected $primaryEmailAddress = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getExternalObjectId()
    {
        return $this->externalObjectId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return EmailAddressExtendedType
     */
    public function setExternalObjectId($value)
    {
        $this->externalObjectId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPrimaryEmailAddress()
    {
        return $this->primaryEmailAddress;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return EmailAddressExtendedType
     */
    public function setPrimaryEmailAddress($value)
    {
        $this->primaryEmailAddress = $value;
        return $this;
    }
}
