<?php

namespace garethp\ews\API\Type;

/**
 * Class representing FileItemType
 *
 *
 * XSD Type: FileItemType
 */
class FileItemType extends ItemType
{

    /**
     * @var string
     */
    protected $fileName = null;

    /**
     * @var string
     */
    protected $fileExtension = null;

    /**
     * @var integer
     */
    protected $fileSize = null;

    /**
     * @var string
     */
    protected $fileCreatedTime = null;

    /**
     * @var string
     */
    protected $fileModifiedTime = null;

    /**
     * @var string
     */
    protected $storageProviderContext = null;

    /**
     * @var string
     */
    protected $fileID = null;

    /**
     * @var string
     */
    protected $itemReferenceId = null;

    /**
     * @var string
     */
    protected $referenceId = null;

    /**
     * @var string
     */
    protected $sender = null;

    /**
     * @var string
     */
    protected $itemReceivedTime = null;

    /**
     * @var string
     */
    protected $itemPath = null;

    /**
     * @var string
     */
    protected $itemSentTime = null;

    /**
     * @var string[]
     */
    protected $fileContexts = null;

    /**
     * @var string
     */
    protected $visualizationContainerUrl = null;

    /**
     * @var string
     */
    protected $visualizationContainerTitle = null;

    /**
     * @var string
     */
    protected $visualizationAccessUrl = null;

    /**
     * @var string
     */
    protected $referenceAttachmentProviderEndpoint = null;

    /**
     * @var string
     */
    protected $referenceAttachmentProviderType = null;

    /**
     * @var string
     */
    protected $itemConversationId = null;

    /**
     * @var string
     */
    protected $sharepointItemListId = null;

    /**
     * @var string
     */
    protected $sharepointItemListItemId = null;

    /**
     * @var string
     */
    protected $sharepointItemSiteId = null;

    /**
     * @var string
     */
    protected $sharepointItemSitePath = null;

    /**
     * @var string
     */
    protected $sharepointItemWebId = null;

    /**
     * @var string
     */
    protected $attachmentId = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFileName()
    {
        return $this->fileName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setFileName($value)
    {
        $this->fileName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFileExtension()
    {
        return $this->fileExtension;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setFileExtension($value)
    {
        $this->fileExtension = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getFileSize()
    {
        return $this->fileSize;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return FileItemType
     */
    public function setFileSize($value)
    {
        $this->fileSize = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFileCreatedTime()
    {
        return $this->fileCreatedTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setFileCreatedTime($value)
    {
        $this->fileCreatedTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFileModifiedTime()
    {
        return $this->fileModifiedTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setFileModifiedTime($value)
    {
        $this->fileModifiedTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getStorageProviderContext()
    {
        return $this->storageProviderContext;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setStorageProviderContext($value)
    {
        $this->storageProviderContext = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFileID()
    {
        return $this->fileID;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setFileID($value)
    {
        $this->fileID = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getItemReferenceId()
    {
        return $this->itemReferenceId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setItemReferenceId($value)
    {
        $this->itemReferenceId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getReferenceId()
    {
        return $this->referenceId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setReferenceId($value)
    {
        $this->referenceId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setSender($value)
    {
        $this->sender = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getItemReceivedTime()
    {
        return $this->itemReceivedTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setItemReceivedTime($value)
    {
        $this->itemReceivedTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getItemPath()
    {
        return $this->itemPath;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setItemPath($value)
    {
        $this->itemPath = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getItemSentTime()
    {
        return $this->itemSentTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setItemSentTime($value)
    {
        $this->itemSentTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function addFileContexts($value)
    {
        if ($this->fileContexts === null) {
                        $this->fileContexts = array();
        }

        if (!is_array($this->fileContexts)) {
            $this->fileContexts = array($this->fileContexts);
        }

        $this->fileContexts[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getFileContexts()
    {
        return $this->fileContexts;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return FileItemType
     */
    public function setFileContexts(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->fileContexts = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getVisualizationContainerUrl()
    {
        return $this->visualizationContainerUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setVisualizationContainerUrl($value)
    {
        $this->visualizationContainerUrl = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getVisualizationContainerTitle()
    {
        return $this->visualizationContainerTitle;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setVisualizationContainerTitle($value)
    {
        $this->visualizationContainerTitle = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getVisualizationAccessUrl()
    {
        return $this->visualizationAccessUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setVisualizationAccessUrl($value)
    {
        $this->visualizationAccessUrl = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getReferenceAttachmentProviderEndpoint()
    {
        return $this->referenceAttachmentProviderEndpoint;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setReferenceAttachmentProviderEndpoint($value)
    {
        $this->referenceAttachmentProviderEndpoint = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getReferenceAttachmentProviderType()
    {
        return $this->referenceAttachmentProviderType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setReferenceAttachmentProviderType($value)
    {
        $this->referenceAttachmentProviderType = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getItemConversationId()
    {
        return $this->itemConversationId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setItemConversationId($value)
    {
        $this->itemConversationId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSharepointItemListId()
    {
        return $this->sharepointItemListId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setSharepointItemListId($value)
    {
        $this->sharepointItemListId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSharepointItemListItemId()
    {
        return $this->sharepointItemListItemId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setSharepointItemListItemId($value)
    {
        $this->sharepointItemListItemId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSharepointItemSiteId()
    {
        return $this->sharepointItemSiteId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setSharepointItemSiteId($value)
    {
        $this->sharepointItemSiteId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSharepointItemSitePath()
    {
        return $this->sharepointItemSitePath;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setSharepointItemSitePath($value)
    {
        $this->sharepointItemSitePath = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSharepointItemWebId()
    {
        return $this->sharepointItemWebId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setSharepointItemWebId($value)
    {
        $this->sharepointItemWebId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAttachmentId()
    {
        return $this->attachmentId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileItemType
     */
    public function setAttachmentId($value)
    {
        $this->attachmentId = $value;
        return $this;
    }
}
