<?php

namespace garethp\ews\API\Type;

/**
 * Class representing FileAttachmentType
 *
 *
 * XSD Type: FileAttachmentType
 */
class FileAttachmentType extends AttachmentType
{

    /**
     * @var boolean
     */
    protected $isContactPhoto = null;

    /**
     * @var string
     */
    protected $content = null;

    /**
     * @returns bool
     */
    public function isContactPhoto()
    {
        return ((bool) $this->isContactPhoto);
    }

    /**
     * @return boolean
     */
    public function getIsContactPhoto()
    {
        return $this->isContactPhoto;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return FileAttachmentType
     */
    public function setIsContactPhoto($value)
    {
        $this->isContactPhoto = $this->castValueIfNeeded("isContactPhoto", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FileAttachmentType
     */
    public function setContent($value)
    {
        $this->content = $this->castValueIfNeeded("content", $value);
        return $this;
    }
}
