<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing FindMeetingTimesLocationConstraintsType
 *
 *
 * XSD Type: FindMeetingTimesLocationConstraints
 */
class FindMeetingTimesLocationConstraintsType extends Type
{

    /**
     * @var \garethp\ews\API\Type\LocationConstraintItemType[]
     */
    protected $locationEntries = null;

    /**
     * @var boolean
     */
    protected $isRequired = null;

    /**
     * @var boolean
     */
    protected $suggestLocation = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value LocationConstraintItemType
     * @return FindMeetingTimesLocationConstraintsType
     */
    public function addLocationEntries(LocationConstraintItemType $value)
    {
        if ($this->locationEntries === null) {
                        $this->locationEntries = array();
        }

        if (!is_array($this->locationEntries)) {
            $this->locationEntries = array($this->locationEntries);
        }

        $this->locationEntries[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return LocationConstraintItemType[]
     */
    public function getLocationEntries()
    {
        return $this->locationEntries;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value LocationConstraintItemType[]|LocationConstraintItemType
     * @return FindMeetingTimesLocationConstraintsType
     */
    public function setLocationEntries(array|LocationConstraintItemType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->locationEntries = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isRequired()
    {
        return ((bool) $this->isRequired);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIsRequired()
    {
        return $this->isRequired;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return FindMeetingTimesLocationConstraintsType
     */
    public function setIsRequired($value)
    {
        $this->isRequired = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isSuggestLocation()
    {
        return ((bool) $this->suggestLocation);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getSuggestLocation()
    {
        return $this->suggestLocation;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return FindMeetingTimesLocationConstraintsType
     */
    public function setSuggestLocation($value)
    {
        $this->suggestLocation = $value;
        return $this;
    }
}
