<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing FlagType
 *
 *
 * XSD Type: FlagType
 */
class FlagType extends Type
{

    /**
     * @var string
     */
    protected $flagStatus = null;

    /**
     * @var \DateTime
     */
    protected $startDate = null;

    /**
     * @var \DateTime
     */
    protected $dueDate = null;

    /**
     * @var \DateTime
     */
    protected $completeDate = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFlagStatus()
    {
        return $this->flagStatus;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return FlagType
     */
    public function setFlagStatus($value)
    {
        $this->flagStatus = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return FlagType
     */
    public function setStartDate(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->startDate = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return FlagType
     */
    public function setDueDate(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->dueDate = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getCompleteDate()
    {
        return $this->completeDate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return FlagType
     */
    public function setCompleteDate(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->completeDate = $value;
        return $this;
    }
}
