<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ImItemListType
 *
 * IM Contact List
 * XSD Type: ImItemListType
 */
class ImItemListType extends Type
{

    /**
     * @var \garethp\ews\API\Type\ImGroupType[]
     */
    protected $groups = null;

    /**
     * @var \garethp\ews\API\Type\PersonaType[]
     */
    protected $personas = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value ImGroupType
     * @return ImItemListType
     */
    public function addGroups(ImGroupType $value)
    {
        if ($this->groups === null) {
                        $this->groups = array();
        }

        if (!is_array($this->groups)) {
            $this->groups = array($this->groups);
        }

        $this->groups[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ImGroupType[]
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ImGroupType[]|ImGroupType
     * @return ImItemListType
     */
    public function setGroups(array|ImGroupType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->groups = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PersonaType
     * @return ImItemListType
     */
    public function addPersonas(PersonaType $value)
    {
        if ($this->personas === null) {
                        $this->personas = array();
        }

        if (!is_array($this->personas)) {
            $this->personas = array($this->personas);
        }

        $this->personas[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return PersonaType[]
     */
    public function getPersonas()
    {
        return $this->personas;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PersonaType[]|PersonaType
     * @return ImItemListType
     */
    public function setPersonas(array|PersonaType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->personas = $value;
        return $this;
    }
}
