<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing InsightType
 *
 *
 * XSD Type: Insight
 */
class InsightType extends Type
{

    /**
     * @var string
     */
    protected $insightType = null;

    /**
     * @var float
     */
    protected $rank = null;

    /**
     * @var \garethp\ews\API\Type\InsightContentType
     */
    protected $content = null;

    /**
     * @var string
     */
    protected $text = null;

    /**
     * @var \garethp\ews\API\Type\InsightValueType[]
     */
    protected $itemList = null;

    /**
     * @var boolean
     */
    protected $requiresToken = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getInsightType()
    {
        return $this->insightType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return InsightType
     */
    public function setInsightType($value)
    {
        $this->insightType = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return float
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value float
     * @return InsightType
     */
    public function setRank($value)
    {
        $this->rank = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return InsightContentType
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value InsightContentType
     * @return InsightType
     */
    public function setContent(InsightContentType $value)
    {
        $this->content = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return InsightType
     */
    public function setText($value)
    {
        $this->text = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value InsightValueType
     * @return InsightType
     */
    public function addItemList(InsightValueType $value)
    {
        if ($this->itemList === null) {
                        $this->itemList = array();
        }

        if (!is_array($this->itemList)) {
            $this->itemList = array($this->itemList);
        }

        $this->itemList[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return InsightValueType[]
     */
    public function getItemList()
    {
        return $this->itemList;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value InsightValueType[]|InsightValueType
     * @return InsightType
     */
    public function setItemList(array|InsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->itemList = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isRequiresToken()
    {
        return ((bool) $this->requiresToken);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getRequiresToken()
    {
        return $this->requiresToken;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return InsightType
     */
    public function setRequiresToken($value)
    {
        $this->requiresToken = $value;
        return $this;
    }
}
