<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing MailboxHoldResultType
 *
 * Mailbox hold result.
 * XSD Type: MailboxHoldResultType
 */
class MailboxHoldResultType extends Type
{

    /**
     * @var string
     */
    protected $holdId = null;

    /**
     * @var string
     */
    protected $query = null;

    /**
     * @var \garethp\ews\API\Type\MailboxHoldStatusType[]
     */
    protected $mailboxHoldStatuses = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getHoldId()
    {
        return $this->holdId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MailboxHoldResultType
     */
    public function setHoldId($value)
    {
        $this->holdId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MailboxHoldResultType
     */
    public function setQuery($value)
    {
        $this->query = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MailboxHoldStatusType
     * @return MailboxHoldResultType
     */
    public function addMailboxHoldStatuses(MailboxHoldStatusType $value)
    {
        if ($this->mailboxHoldStatuses === null) {
                        $this->mailboxHoldStatuses = array();
        }

        if (!is_array($this->mailboxHoldStatuses)) {
            $this->mailboxHoldStatuses = array($this->mailboxHoldStatuses);
        }

        $this->mailboxHoldStatuses[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return MailboxHoldStatusType[]
     */
    public function getMailboxHoldStatuses()
    {
        return $this->mailboxHoldStatuses;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value MailboxHoldStatusType[]|MailboxHoldStatusType
     * @return MailboxHoldResultType
     */
    public function setMailboxHoldStatuses(array|MailboxHoldStatusType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->mailboxHoldStatuses = $value;
        return $this;
    }
}
