<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing MailboxLocatorType
 *
 *
 * XSD Type: MailboxLocatorType
 */
class MailboxLocatorType extends Type
{

    /**
     * @var string
     */
    protected $externalDirectoryObjectId = null;

    /**
     * @var string
     */
    protected $legacyDn = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getExternalDirectoryObjectId()
    {
        return $this->externalDirectoryObjectId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MailboxLocatorType
     */
    public function setExternalDirectoryObjectId($value)
    {
        $this->externalDirectoryObjectId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getLegacyDn()
    {
        return $this->legacyDn;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MailboxLocatorType
     */
    public function setLegacyDn($value)
    {
        $this->legacyDn = $value;
        return $this;
    }
}
