<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ManagedFolderInformationType
 *
 * Compound property for Managed Folder related information for Managed Folders.
 * XSD Type: ManagedFolderInformationType
 */
class ManagedFolderInformationType extends Type
{

    /**
     * @var boolean
     */
    protected $canDelete = null;

    /**
     * @var boolean
     */
    protected $canRenameOrMove = null;

    /**
     * @var boolean
     */
    protected $mustDisplayComment = null;

    /**
     * @var boolean
     */
    protected $hasQuota = null;

    /**
     * @var boolean
     */
    protected $isManagedFoldersRoot = null;

    /**
     * @var string
     */
    protected $managedFolderId = null;

    /**
     * @var string
     */
    protected $comment = null;

    /**
     * @var integer
     */
    protected $storageQuota = null;

    /**
     * @var integer
     */
    protected $folderSize = null;

    /**
     * @var string
     */
    protected $homePage = null;

    /**
     * @return boolean
     */
    public function getCanDelete()
    {
        return $this->canDelete;
    }

    /**
     * @return boolean
     */
    public function getCanRenameOrMove()
    {
        return $this->canRenameOrMove;
    }

    /**
     * @return boolean
     */
    public function getMustDisplayComment()
    {
        return $this->mustDisplayComment;
    }

    /**
     * @return boolean
     */
    public function getHasQuota()
    {
        return $this->hasQuota;
    }

    /**
     * @return boolean
     */
    public function getIsManagedFoldersRoot()
    {
        return $this->isManagedFoldersRoot;
    }

    /**
     * @return string
     */
    public function getManagedFolderId()
    {
        return $this->managedFolderId;
    }

    /**
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @return integer
     */
    public function getStorageQuota()
    {
        return $this->storageQuota;
    }

    /**
     * @return integer
     */
    public function getFolderSize()
    {
        return $this->folderSize;
    }

    /**
     * @return string
     */
    public function getHomePage()
    {
        return $this->homePage;
    }

    /**
     * @returns bool
     */
    public function isCanDelete()
    {
        return ((bool) $this->canDelete);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ManagedFolderInformationType
     */
    public function setCanDelete($value)
    {
        $this->canDelete = $this->castValueIfNeeded("canDelete", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isCanRenameOrMove()
    {
        return ((bool) $this->canRenameOrMove);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ManagedFolderInformationType
     */
    public function setCanRenameOrMove($value)
    {
        $this->canRenameOrMove = $this->castValueIfNeeded("canRenameOrMove", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isMustDisplayComment()
    {
        return ((bool) $this->mustDisplayComment);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ManagedFolderInformationType
     */
    public function setMustDisplayComment($value)
    {
        $this->mustDisplayComment = $this->castValueIfNeeded("mustDisplayComment", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isHasQuota()
    {
        return ((bool) $this->hasQuota);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ManagedFolderInformationType
     */
    public function setHasQuota($value)
    {
        $this->hasQuota = $this->castValueIfNeeded("hasQuota", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isManagedFoldersRoot()
    {
        return ((bool) $this->isManagedFoldersRoot);
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ManagedFolderInformationType
     */
    public function setIsManagedFoldersRoot($value)
    {
        $this->isManagedFoldersRoot = $this->castValueIfNeeded("isManagedFoldersRoot", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ManagedFolderInformationType
     */
    public function setManagedFolderId($value)
    {
        $this->managedFolderId = $this->castValueIfNeeded("managedFolderId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ManagedFolderInformationType
     */
    public function setComment($value)
    {
        $this->comment = $this->castValueIfNeeded("comment", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ManagedFolderInformationType
     */
    public function setStorageQuota($value)
    {
        $this->storageQuota = $this->castValueIfNeeded("storageQuota", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ManagedFolderInformationType
     */
    public function setFolderSize($value)
    {
        $this->folderSize = $this->castValueIfNeeded("folderSize", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ManagedFolderInformationType
     */
    public function setHomePage($value)
    {
        $this->homePage = $this->castValueIfNeeded("homePage", $value);
        return $this;
    }
}
