<?php

namespace garethp\ews\API\Type;

/**
 * Class representing MeetingSuggestionType
 *
 *
 * XSD Type: MeetingSuggestionType
 */
class MeetingSuggestionType extends EntityType
{

    /**
     * @var \garethp\ews\API\Type\EmailUserType[]
     */
    protected $attendees = null;

    /**
     * @var string
     */
    protected $location = null;

    /**
     * @var string
     */
    protected $subject = null;

    /**
     * @var string
     */
    protected $meetingString = null;

    /**
     * @var \DateTime
     */
    protected $startTime = null;

    /**
     * @var \DateTime
     */
    protected $endTime = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value EmailUserType
     * @return MeetingSuggestionType
     */
    public function addAttendees(EmailUserType $value)
    {
        if ($this->attendees === null) {
                        $this->attendees = array();
        }

        if (!is_array($this->attendees)) {
            $this->attendees = array($this->attendees);
        }

        $this->attendees[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return EmailUserType[]
     */
    public function getAttendees()
    {
        return $this->attendees;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value EmailUserType[]|EmailUserType
     * @return MeetingSuggestionType
     */
    public function setAttendees(array|EmailUserType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->attendees = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MeetingSuggestionType
     */
    public function setLocation($value)
    {
        $this->location = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MeetingSuggestionType
     */
    public function setSubject($value)
    {
        $this->subject = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getMeetingString()
    {
        return $this->meetingString;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MeetingSuggestionType
     */
    public function setMeetingString($value)
    {
        $this->meetingString = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return MeetingSuggestionType
     */
    public function setStartTime(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->startTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return MeetingSuggestionType
     */
    public function setEndTime(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->endTime = $value;
        return $this;
    }
}
