<?php

namespace garethp\ews\API\Type;

/**
 * Class representing MeetingInsightValueType
 *
 *
 * XSD Type: MeetingInsightValue
 */
class MeetingInsightValueType extends InsightValueType
{

    /**
     * @var string
     */
    protected $id = null;

    /**
     * @var string
     */
    protected $subject = null;

    /**
     * @var integer
     */
    protected $startUtcTicks = null;

    /**
     * @var integer
     */
    protected $endUtcTicks = null;

    /**
     * @var string
     */
    protected $location = null;

    /**
     * @var \garethp\ews\API\Type\ProfileInsightValueType
     */
    protected $organizer = null;

    /**
     * @var \garethp\ews\API\Type\ProfileInsightValueType[]
     */
    protected $attendees = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MeetingInsightValueType
     */
    public function setId($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MeetingInsightValueType
     */
    public function setSubject($value)
    {
        $this->subject = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getStartUtcTicks()
    {
        return $this->startUtcTicks;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return MeetingInsightValueType
     */
    public function setStartUtcTicks($value)
    {
        $this->startUtcTicks = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getEndUtcTicks()
    {
        return $this->endUtcTicks;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return MeetingInsightValueType
     */
    public function setEndUtcTicks($value)
    {
        $this->endUtcTicks = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MeetingInsightValueType
     */
    public function setLocation($value)
    {
        $this->location = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ProfileInsightValueType
     */
    public function getOrganizer()
    {
        return $this->organizer;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType
     * @return MeetingInsightValueType
     */
    public function setOrganizer(ProfileInsightValueType $value)
    {
        $this->organizer = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType
     * @return MeetingInsightValueType
     */
    public function addAttendees(ProfileInsightValueType $value)
    {
        if ($this->attendees === null) {
                        $this->attendees = array();
        }

        if (!is_array($this->attendees)) {
            $this->attendees = array($this->attendees);
        }

        $this->attendees[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ProfileInsightValueType[]
     */
    public function getAttendees()
    {
        return $this->attendees;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType[]|ProfileInsightValueType
     * @return MeetingInsightValueType
     */
    public function setAttendees(array|ProfileInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->attendees = $value;
        return $this;
    }
}
