<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing MessageTrackingReportType
 *
 *
 * XSD Type: MessageTrackingReportType
 *
 * @method MessageTrackingReportType addOriginalRecipients(EmailAddressType $originalRecipients)
 * @method MessageTrackingReportType addRecipientTrackingEvents(RecipientTrackingEventType $recipientTrackingEvents)
 * @method MessageTrackingReportType addProperties(TrackingPropertyType $properties)
 */
class MessageTrackingReportType extends Type
{

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $sender = null;

    /**
     * @var \garethp\ews\API\Type\EmailAddressType
     */
    protected $purportedSender = null;

    /**
     * @var string
     */
    protected $subject = null;

    /**
     * @var \DateTime
     */
    protected $submitTime = null;

    protected $_typeMap = array(
        'submitTime' => 'dateTime',
    );

    /**
     * @var \garethp\ews\API\Type\EmailAddressType[]
     */
    protected $originalRecipients = null;

    /**
     * @var \garethp\ews\API\Type\RecipientTrackingEventType[]
     */
    protected $recipientTrackingEvents = null;

    /**
     * @var \garethp\ews\API\Type\TrackingPropertyType[]
     */
    protected $properties = null;

    /**
     * @return EmailAddressType
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * @return EmailAddressType
     */
    public function getPurportedSender()
    {
        return $this->purportedSender;
    }

    /**
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * @return \DateTime
     */
    public function getSubmitTime()
    {
        return $this->submitTime;
    }

    /**
     * @return EmailAddressType[]
     */
    public function getOriginalRecipients()
    {
        return $this->originalRecipients;
    }

    /**
     * @return RecipientTrackingEventType[]
     */
    public function getRecipientTrackingEvents()
    {
        return $this->recipientTrackingEvents;
    }

    /**
     * @return TrackingPropertyType[]
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value EmailAddressType
     * @return MessageTrackingReportType
     */
    public function setSender(EmailAddressType $value)
    {
        $this->sender = $this->castValueIfNeeded("sender", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value EmailAddressType
     * @return MessageTrackingReportType
     */
    public function setPurportedSender(EmailAddressType $value)
    {
        $this->purportedSender = $this->castValueIfNeeded("purportedSender", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return MessageTrackingReportType
     */
    public function setSubject($value)
    {
        $this->subject = $this->castValueIfNeeded("subject", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return MessageTrackingReportType
     */
    public function setSubmitTime(\DateTime|string $value)
    {
        $this->submitTime = $this->castValueIfNeeded("submitTime", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value EmailAddressType[]
     * @return MessageTrackingReportType
     */
    public function setOriginalRecipients(array $value)
    {
        $this->originalRecipients = $this->castValueIfNeeded("originalRecipients", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value RecipientTrackingEventType[]
     * @return MessageTrackingReportType
     */
    public function setRecipientTrackingEvents(array $value)
    {
        $this->recipientTrackingEvents = $this->castValueIfNeeded("recipientTrackingEvents", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TrackingPropertyType[]
     * @return MessageTrackingReportType
     */
    public function setProperties(array $value)
    {
        $this->properties = $this->castValueIfNeeded("properties", $value);
        return $this;
    }
}
