<?php

namespace garethp\ews\API\Type;

/**
 * Class representing MultiValueInsightContentType
 *
 *
 * XSD Type: MultiValueInsightContent
 */
class MultiValueInsightContentType extends InsightContentType
{

    /**
     * @var \garethp\ews\API\Type\InsightValueType[]
     */
    protected $itemList = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value InsightValueType
     * @return MultiValueInsightContentType
     */
    public function addItemList(InsightValueType $value)
    {
        if ($this->itemList === null) {
                        $this->itemList = array();
        }

        if (!is_array($this->itemList)) {
            $this->itemList = array($this->itemList);
        }

        $this->itemList[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return InsightValueType[]
     */
    public function getItemList()
    {
        return $this->itemList;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value InsightValueType[]|InsightValueType
     * @return MultiValueInsightContentType
     */
    public function setItemList(array|InsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->itemList = $value;
        return $this;
    }
}
