<?php

namespace garethp\ews\API\Type;

/**
 * Class representing NearType
 *
 *
 * XSD Type: NearType
 */
class NearType extends MultipleOperandBooleanExpressionType
{

    /**
     * @var integer
     */
    protected $distance = null;

    /**
     * @var boolean
     */
    protected $ordered = null;

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return NearType
     */
    public function setDistance($value)
    {
        $this->distance = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isOrdered()
    {
        return ((bool) $this->ordered);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getOrdered()
    {
        return $this->ordered;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return NearType
     */
    public function setOrdered($value)
    {
        $this->ordered = $value;
        return $this;
    }
}
