<?php

namespace garethp\ews\API\Type;

/**
 * Class representing NetworkItemType
 *
 *
 * XSD Type: NetworkItemType
 */
class NetworkItemType extends ItemType
{

    /**
     * @var integer
     */
    protected $domainId = null;

    /**
     * @var string
     */
    protected $domainTag = null;

    /**
     * @var string
     */
    protected $userTileUrl = null;

    /**
     * @var string
     */
    protected $profileUrl = null;

    /**
     * @var integer
     */
    protected $settings = null;

    /**
     * @var boolean
     */
    protected $isDefault = null;

    /**
     * @var string
     */
    protected $autoLinkError = null;

    /**
     * @var string
     */
    protected $autoLinkSuccess = null;

    /**
     * @var string
     */
    protected $userEmail = null;

    /**
     * @var string
     */
    protected $clientPublishSecret = null;

    /**
     * @var string
     */
    protected $clientToken = null;

    /**
     * @var string
     */
    protected $clientToken2 = null;

    /**
     * @var string
     */
    protected $contactSyncError = null;

    /**
     * @var string
     */
    protected $contactSyncSuccess = null;

    /**
     * @var integer
     */
    protected $errorOffers = null;

    /**
     * @var string
     */
    protected $firstAuthErrorDates = null;

    /**
     * @var integer
     */
    protected $lastVersionSaved = null;

    /**
     * @var string
     */
    protected $lastWelcomeContact = null;

    /**
     * @var integer
     */
    protected $offers = null;

    /**
     * @var \DateTime
     */
    protected $psaLastChanged = null;

    /**
     * @var string
     */
    protected $refreshToken2 = null;

    /**
     * @var string
     */
    protected $refreshTokenExpiry2 = null;

    /**
     * @var string
     */
    protected $sessionHandle = null;

    /**
     * @var integer
     */
    protected $rejectedOffers = null;

    /**
     * @var boolean
     */
    protected $syncEnabled = null;

    /**
     * @var \DateTime
     */
    protected $tokenRefreshLastAttempted = null;

    /**
     * @var \DateTime
     */
    protected $tokenRefreshLastCompleted = null;

    /**
     * @var string
     */
    protected $psaState = null;

    /**
     * @var string
     */
    protected $sourceEntryID = null;

    /**
     * @var string
     */
    protected $accountName = null;

    /**
     * @var \DateTime
     */
    protected $lastSync = null;

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getDomainId()
    {
        return $this->domainId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return NetworkItemType
     */
    public function setDomainId($value)
    {
        $this->domainId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getDomainTag()
    {
        return $this->domainTag;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setDomainTag($value)
    {
        $this->domainTag = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getUserTileUrl()
    {
        return $this->userTileUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setUserTileUrl($value)
    {
        $this->userTileUrl = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProfileUrl()
    {
        return $this->profileUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setProfileUrl($value)
    {
        $this->profileUrl = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return NetworkItemType
     */
    public function setSettings($value)
    {
        $this->settings = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isDefault()
    {
        return ((bool) $this->isDefault);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIsDefault()
    {
        return $this->isDefault;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return NetworkItemType
     */
    public function setIsDefault($value)
    {
        $this->isDefault = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAutoLinkError()
    {
        return $this->autoLinkError;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setAutoLinkError($value)
    {
        $this->autoLinkError = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAutoLinkSuccess()
    {
        return $this->autoLinkSuccess;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setAutoLinkSuccess($value)
    {
        $this->autoLinkSuccess = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getUserEmail()
    {
        return $this->userEmail;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setUserEmail($value)
    {
        $this->userEmail = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getClientPublishSecret()
    {
        return $this->clientPublishSecret;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setClientPublishSecret($value)
    {
        $this->clientPublishSecret = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getClientToken()
    {
        return $this->clientToken;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setClientToken($value)
    {
        $this->clientToken = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getClientToken2()
    {
        return $this->clientToken2;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setClientToken2($value)
    {
        $this->clientToken2 = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getContactSyncError()
    {
        return $this->contactSyncError;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setContactSyncError($value)
    {
        $this->contactSyncError = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getContactSyncSuccess()
    {
        return $this->contactSyncSuccess;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setContactSyncSuccess($value)
    {
        $this->contactSyncSuccess = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getErrorOffers()
    {
        return $this->errorOffers;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return NetworkItemType
     */
    public function setErrorOffers($value)
    {
        $this->errorOffers = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFirstAuthErrorDates()
    {
        return $this->firstAuthErrorDates;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setFirstAuthErrorDates($value)
    {
        $this->firstAuthErrorDates = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getLastVersionSaved()
    {
        return $this->lastVersionSaved;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return NetworkItemType
     */
    public function setLastVersionSaved($value)
    {
        $this->lastVersionSaved = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getLastWelcomeContact()
    {
        return $this->lastWelcomeContact;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setLastWelcomeContact($value)
    {
        $this->lastWelcomeContact = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getOffers()
    {
        return $this->offers;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return NetworkItemType
     */
    public function setOffers($value)
    {
        $this->offers = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getPsaLastChanged()
    {
        return $this->psaLastChanged;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return NetworkItemType
     */
    public function setPsaLastChanged(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->psaLastChanged = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getRefreshToken2()
    {
        return $this->refreshToken2;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setRefreshToken2($value)
    {
        $this->refreshToken2 = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getRefreshTokenExpiry2()
    {
        return $this->refreshTokenExpiry2;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setRefreshTokenExpiry2($value)
    {
        $this->refreshTokenExpiry2 = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSessionHandle()
    {
        return $this->sessionHandle;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setSessionHandle($value)
    {
        $this->sessionHandle = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getRejectedOffers()
    {
        return $this->rejectedOffers;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return NetworkItemType
     */
    public function setRejectedOffers($value)
    {
        $this->rejectedOffers = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isSyncEnabled()
    {
        return ((bool) $this->syncEnabled);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getSyncEnabled()
    {
        return $this->syncEnabled;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return NetworkItemType
     */
    public function setSyncEnabled($value)
    {
        $this->syncEnabled = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getTokenRefreshLastAttempted()
    {
        return $this->tokenRefreshLastAttempted;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return NetworkItemType
     */
    public function setTokenRefreshLastAttempted(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->tokenRefreshLastAttempted = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getTokenRefreshLastCompleted()
    {
        return $this->tokenRefreshLastCompleted;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return NetworkItemType
     */
    public function setTokenRefreshLastCompleted(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->tokenRefreshLastCompleted = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPsaState()
    {
        return $this->psaState;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setPsaState($value)
    {
        $this->psaState = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSourceEntryID()
    {
        return $this->sourceEntryID;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setSourceEntryID($value)
    {
        $this->sourceEntryID = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAccountName()
    {
        return $this->accountName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return NetworkItemType
     */
    public function setAccountName($value)
    {
        $this->accountName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getLastSync()
    {
        return $this->lastSync;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return NetworkItemType
     */
    public function setLastSync(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->lastSync = $value;
        return $this;
    }
}
