<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing NonEmptyArrayOfFoldersType
 *
 *
 * XSD Type: NonEmptyArrayOfFoldersType
 *
 * @method NonEmptyArrayOfFoldersType addFolder(FolderType $folder)
 * @method NonEmptyArrayOfFoldersType addCalendarFolder(CalendarFolderType $calendarFolder)
 * @method NonEmptyArrayOfFoldersType addContactsFolder(ContactsFolderType $contactsFolder)
 * @method NonEmptyArrayOfFoldersType addSearchFolder(SearchFolderType $searchFolder)
 * @method NonEmptyArrayOfFoldersType addTasksFolder(TasksFolderType $tasksFolder)
 */
class NonEmptyArrayOfFoldersType extends Type
{

    /**
     * @var \garethp\ews\API\Type\FolderType[]
     */
    protected $folder = null;

    /**
     * @var \garethp\ews\API\Type\CalendarFolderType[]
     */
    protected $calendarFolder = null;

    /**
     * @var \garethp\ews\API\Type\ContactsFolderType[]
     */
    protected $contactsFolder = null;

    /**
     * @var \garethp\ews\API\Type\SearchFolderType[]
     */
    protected $searchFolder = null;

    /**
     * @var \garethp\ews\API\Type\TasksFolderType[]
     */
    protected $tasksFolder = null;

    /**
     * @return FolderType[]
     */
    public function getFolder()
    {
        return $this->folder;
    }

    /**
     * @return CalendarFolderType[]
     */
    public function getCalendarFolder()
    {
        return $this->calendarFolder;
    }

    /**
     * @return ContactsFolderType[]
     */
    public function getContactsFolder()
    {
        return $this->contactsFolder;
    }

    /**
     * @return SearchFolderType[]
     */
    public function getSearchFolder()
    {
        return $this->searchFolder;
    }

    /**
     * @return TasksFolderType[]
     */
    public function getTasksFolder()
    {
        return $this->tasksFolder;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value FolderType[]
     * @return NonEmptyArrayOfFoldersType
     */
    public function setFolder(array $value)
    {
        $this->folder = $this->castValueIfNeeded("folder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CalendarFolderType[]
     * @return NonEmptyArrayOfFoldersType
     */
    public function setCalendarFolder(array $value)
    {
        $this->calendarFolder = $this->castValueIfNeeded("calendarFolder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ContactsFolderType[]
     * @return NonEmptyArrayOfFoldersType
     */
    public function setContactsFolder(array $value)
    {
        $this->contactsFolder = $this->castValueIfNeeded("contactsFolder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SearchFolderType[]
     * @return NonEmptyArrayOfFoldersType
     */
    public function setSearchFolder(array $value)
    {
        $this->searchFolder = $this->castValueIfNeeded("searchFolder", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TasksFolderType[]
     * @return NonEmptyArrayOfFoldersType
     */
    public function setTasksFolder(array $value)
    {
        $this->tasksFolder = $this->castValueIfNeeded("tasksFolder", $value);
        return $this;
    }
}
