<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing NonEmptyArrayOfAlternateIdsType
 *
 * A non-empty array of alternate Ids.
 * XSD Type: NonEmptyArrayOfAlternateIdsType
 *
 * @method NonEmptyArrayOfAlternateIdsType addAlternateId(AlternateIdType $alternateId)
 * @method NonEmptyArrayOfAlternateIdsType addAlternatePublicFolderId(AlternatePublicFolderIdType $alternatePublicFolderId)
 * @method NonEmptyArrayOfAlternateIdsType addAlternatePublicFolderItemId(AlternatePublicFolderItemIdType $alternatePublicFolderItemId)
 */
class NonEmptyArrayOfAlternateIdsType extends Type
{

    /**
     * @var \garethp\ews\API\Type\AlternateIdType[]
     */
    protected $alternateId = null;

    /**
     * @var \garethp\ews\API\Type\AlternatePublicFolderIdType[]
     */
    protected $alternatePublicFolderId = null;

    /**
     * @var \garethp\ews\API\Type\AlternatePublicFolderItemIdType[]
     */
    protected $alternatePublicFolderItemId = null;

    /**
     * @return AlternateIdType[]
     */
    public function getAlternateId()
    {
        return $this->alternateId;
    }

    /**
     * @return AlternatePublicFolderIdType[]
     */
    public function getAlternatePublicFolderId()
    {
        return $this->alternatePublicFolderId;
    }

    /**
     * @return AlternatePublicFolderItemIdType[]
     */
    public function getAlternatePublicFolderItemId()
    {
        return $this->alternatePublicFolderItemId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AlternateIdType[]
     * @return NonEmptyArrayOfAlternateIdsType
     */
    public function setAlternateId(array $value)
    {
        $this->alternateId = $this->castValueIfNeeded("alternateId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AlternatePublicFolderIdType[]
     * @return NonEmptyArrayOfAlternateIdsType
     */
    public function setAlternatePublicFolderId(array $value)
    {
        $this->alternatePublicFolderId = $this->castValueIfNeeded("alternatePublicFolderId", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AlternatePublicFolderItemIdType[]
     * @return NonEmptyArrayOfAlternateIdsType
     */
    public function setAlternatePublicFolderItemId(array $value)
    {
        $this->alternatePublicFolderItemId = $this->castValueIfNeeded("alternatePublicFolderItemId", $value);
        return $this;
    }
}
