<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing NonEmptyArrayOfResponseObjectsType
 *
 *
 * XSD Type: NonEmptyArrayOfResponseObjectsType
 *
 * @method NonEmptyArrayOfResponseObjectsType addAcceptItem(AcceptItemType $acceptItem)
 * @method NonEmptyArrayOfResponseObjectsType addTentativelyAcceptItem(TentativelyAcceptItemType $tentativelyAcceptItem)
 * @method NonEmptyArrayOfResponseObjectsType addDeclineItem(DeclineItemType $declineItem)
 * @method NonEmptyArrayOfResponseObjectsType addReplyToItem(ReplyToItemType $replyToItem)
 * @method NonEmptyArrayOfResponseObjectsType addForwardItem(ForwardItemType $forwardItem)
 * @method NonEmptyArrayOfResponseObjectsType addReplyAllToItem(ReplyAllToItemType $replyAllToItem)
 * @method NonEmptyArrayOfResponseObjectsType addCancelCalendarItem(CancelCalendarItemType $cancelCalendarItem)
 * @method NonEmptyArrayOfResponseObjectsType addRemoveItem(RemoveItemType $removeItem)
 * @method NonEmptyArrayOfResponseObjectsType addSuppressReadReceipt(SuppressReadReceiptType $suppressReadReceipt)
 * @method NonEmptyArrayOfResponseObjectsType addPostReplyItem(PostReplyItemType $postReplyItem)
 * @method NonEmptyArrayOfResponseObjectsType addAcceptSharingInvitation(AcceptSharingInvitationType $acceptSharingInvitation)
 */
class NonEmptyArrayOfResponseObjectsType extends Type
{

    /**
     * @var \garethp\ews\API\Type\AcceptItemType[]
     */
    protected $acceptItem = null;

    /**
     * @var \garethp\ews\API\Type\TentativelyAcceptItemType[]
     */
    protected $tentativelyAcceptItem = null;

    /**
     * @var \garethp\ews\API\Type\DeclineItemType[]
     */
    protected $declineItem = null;

    /**
     * @var \garethp\ews\API\Type\ReplyToItemType[]
     */
    protected $replyToItem = null;

    /**
     * @var \garethp\ews\API\Type\ForwardItemType[]
     */
    protected $forwardItem = null;

    /**
     * @var \garethp\ews\API\Type\ReplyAllToItemType[]
     */
    protected $replyAllToItem = null;

    /**
     * @var \garethp\ews\API\Type\CancelCalendarItemType[]
     */
    protected $cancelCalendarItem = null;

    /**
     * @var \garethp\ews\API\Type\RemoveItemType[]
     */
    protected $removeItem = null;

    /**
     * @var \garethp\ews\API\Type\SuppressReadReceiptType[]
     */
    protected $suppressReadReceipt = null;

    /**
     * @var \garethp\ews\API\Type\PostReplyItemType[]
     */
    protected $postReplyItem = null;

    /**
     * @var \garethp\ews\API\Type\AcceptSharingInvitationType[]
     */
    protected $acceptSharingInvitation = null;

    /**
     * @return AcceptItemType[]
     */
    public function getAcceptItem()
    {
        return $this->acceptItem;
    }

    /**
     * @return TentativelyAcceptItemType[]
     */
    public function getTentativelyAcceptItem()
    {
        return $this->tentativelyAcceptItem;
    }

    /**
     * @return DeclineItemType[]
     */
    public function getDeclineItem()
    {
        return $this->declineItem;
    }

    /**
     * @return ReplyToItemType[]
     */
    public function getReplyToItem()
    {
        return $this->replyToItem;
    }

    /**
     * @return ForwardItemType[]
     */
    public function getForwardItem()
    {
        return $this->forwardItem;
    }

    /**
     * @return ReplyAllToItemType[]
     */
    public function getReplyAllToItem()
    {
        return $this->replyAllToItem;
    }

    /**
     * @return CancelCalendarItemType[]
     */
    public function getCancelCalendarItem()
    {
        return $this->cancelCalendarItem;
    }

    /**
     * @return RemoveItemType[]
     */
    public function getRemoveItem()
    {
        return $this->removeItem;
    }

    /**
     * @return SuppressReadReceiptType[]
     */
    public function getSuppressReadReceipt()
    {
        return $this->suppressReadReceipt;
    }

    /**
     * @return PostReplyItemType[]
     */
    public function getPostReplyItem()
    {
        return $this->postReplyItem;
    }

    /**
     * @return AcceptSharingInvitationType[]
     */
    public function getAcceptSharingInvitation()
    {
        return $this->acceptSharingInvitation;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AcceptItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setAcceptItem(array $value)
    {
        $this->acceptItem = $this->castValueIfNeeded("acceptItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TentativelyAcceptItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setTentativelyAcceptItem(array $value)
    {
        $this->tentativelyAcceptItem = $this->castValueIfNeeded("tentativelyAcceptItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value DeclineItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setDeclineItem(array $value)
    {
        $this->declineItem = $this->castValueIfNeeded("declineItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyToItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setReplyToItem(array $value)
    {
        $this->replyToItem = $this->castValueIfNeeded("replyToItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ForwardItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setForwardItem(array $value)
    {
        $this->forwardItem = $this->castValueIfNeeded("forwardItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyAllToItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setReplyAllToItem(array $value)
    {
        $this->replyAllToItem = $this->castValueIfNeeded("replyAllToItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CancelCalendarItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setCancelCalendarItem(array $value)
    {
        $this->cancelCalendarItem = $this->castValueIfNeeded("cancelCalendarItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value RemoveItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setRemoveItem(array $value)
    {
        $this->removeItem = $this->castValueIfNeeded("removeItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SuppressReadReceiptType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setSuppressReadReceipt(array $value)
    {
        $this->suppressReadReceipt = $this->castValueIfNeeded("suppressReadReceipt", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PostReplyItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setPostReplyItem(array $value)
    {
        $this->postReplyItem = $this->castValueIfNeeded("postReplyItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AcceptSharingInvitationType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setAcceptSharingInvitation(array $value)
    {
        $this->acceptSharingInvitation = $this->castValueIfNeeded("acceptSharingInvitation", $value);
        return $this;
    }
}
