<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing NonEmptyArrayOfResponseObjectsType
 *
 *
 * XSD Type: NonEmptyArrayOfResponseObjectsType
 */
class NonEmptyArrayOfResponseObjectsType extends Type
{

    /**
     * @var \garethp\ews\API\Type\AcceptItemType[]
     */
    protected $acceptItem = null;

    /**
     * @var \garethp\ews\API\Type\TentativelyAcceptItemType[]
     */
    protected $tentativelyAcceptItem = null;

    /**
     * @var \garethp\ews\API\Type\DeclineItemType[]
     */
    protected $declineItem = null;

    /**
     * @var \garethp\ews\API\Type\ReplyToItemType[]
     */
    protected $replyToItem = null;

    /**
     * @var \garethp\ews\API\Type\ForwardItemType[]
     */
    protected $forwardItem = null;

    /**
     * @var \garethp\ews\API\Type\ReplyAllToItemType[]
     */
    protected $replyAllToItem = null;

    /**
     * @var \garethp\ews\API\Type\CancelCalendarItemType[]
     */
    protected $cancelCalendarItem = null;

    /**
     * @var \garethp\ews\API\Type\RemoveItemType[]
     */
    protected $removeItem = null;

    /**
     * @var \garethp\ews\API\Type\SuppressReadReceiptType[]
     */
    protected $suppressReadReceipt = null;

    /**
     * @var \garethp\ews\API\Type\PostReplyItemType[]
     */
    protected $postReplyItem = null;

    /**
     * @var \garethp\ews\API\Type\AcceptSharingInvitationType[]
     */
    protected $acceptSharingInvitation = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value AcceptItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addAcceptItem(AcceptItemType $value)
    {
        $value = $this->castValueIfNeeded("acceptItem", $value);

        if ($this->acceptItem === null) {
            $this->acceptItem = array();
        }

        if (!is_array($this->acceptItem)) {
            $this->acceptItem = array($this->acceptItem);
        }

        $this->acceptItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return AcceptItemType[]
     */
    public function getAcceptItem()
    {
        return $this->acceptItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AcceptItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setAcceptItem(array $value)
    {
        $this->acceptItem = $this->castValueIfNeeded("acceptItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TentativelyAcceptItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addTentativelyAcceptItem(TentativelyAcceptItemType $value)
    {
        $value = $this->castValueIfNeeded("tentativelyAcceptItem", $value);

        if ($this->tentativelyAcceptItem === null) {
            $this->tentativelyAcceptItem = array();
        }

        if (!is_array($this->tentativelyAcceptItem)) {
            $this->tentativelyAcceptItem = array($this->tentativelyAcceptItem);
        }

        $this->tentativelyAcceptItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return TentativelyAcceptItemType[]
     */
    public function getTentativelyAcceptItem()
    {
        return $this->tentativelyAcceptItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TentativelyAcceptItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setTentativelyAcceptItem(array $value)
    {
        $this->tentativelyAcceptItem = $this->castValueIfNeeded("tentativelyAcceptItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value DeclineItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addDeclineItem(DeclineItemType $value)
    {
        $value = $this->castValueIfNeeded("declineItem", $value);

        if ($this->declineItem === null) {
            $this->declineItem = array();
        }

        if (!is_array($this->declineItem)) {
            $this->declineItem = array($this->declineItem);
        }

        $this->declineItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return DeclineItemType[]
     */
    public function getDeclineItem()
    {
        return $this->declineItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value DeclineItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setDeclineItem(array $value)
    {
        $this->declineItem = $this->castValueIfNeeded("declineItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyToItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addReplyToItem(ReplyToItemType $value)
    {
        $value = $this->castValueIfNeeded("replyToItem", $value);

        if ($this->replyToItem === null) {
            $this->replyToItem = array();
        }

        if (!is_array($this->replyToItem)) {
            $this->replyToItem = array($this->replyToItem);
        }

        $this->replyToItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ReplyToItemType[]
     */
    public function getReplyToItem()
    {
        return $this->replyToItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyToItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setReplyToItem(array $value)
    {
        $this->replyToItem = $this->castValueIfNeeded("replyToItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ForwardItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addForwardItem(ForwardItemType $value)
    {
        $value = $this->castValueIfNeeded("forwardItem", $value);

        if ($this->forwardItem === null) {
            $this->forwardItem = array();
        }

        if (!is_array($this->forwardItem)) {
            $this->forwardItem = array($this->forwardItem);
        }

        $this->forwardItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ForwardItemType[]
     */
    public function getForwardItem()
    {
        return $this->forwardItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ForwardItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setForwardItem(array $value)
    {
        $this->forwardItem = $this->castValueIfNeeded("forwardItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyAllToItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addReplyAllToItem(ReplyAllToItemType $value)
    {
        $value = $this->castValueIfNeeded("replyAllToItem", $value);

        if ($this->replyAllToItem === null) {
            $this->replyAllToItem = array();
        }

        if (!is_array($this->replyAllToItem)) {
            $this->replyAllToItem = array($this->replyAllToItem);
        }

        $this->replyAllToItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ReplyAllToItemType[]
     */
    public function getReplyAllToItem()
    {
        return $this->replyAllToItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyAllToItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setReplyAllToItem(array $value)
    {
        $this->replyAllToItem = $this->castValueIfNeeded("replyAllToItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CancelCalendarItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addCancelCalendarItem(CancelCalendarItemType $value)
    {
        $value = $this->castValueIfNeeded("cancelCalendarItem", $value);

        if ($this->cancelCalendarItem === null) {
            $this->cancelCalendarItem = array();
        }

        if (!is_array($this->cancelCalendarItem)) {
            $this->cancelCalendarItem = array($this->cancelCalendarItem);
        }

        $this->cancelCalendarItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return CancelCalendarItemType[]
     */
    public function getCancelCalendarItem()
    {
        return $this->cancelCalendarItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CancelCalendarItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setCancelCalendarItem(array $value)
    {
        $this->cancelCalendarItem = $this->castValueIfNeeded("cancelCalendarItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value RemoveItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addRemoveItem(RemoveItemType $value)
    {
        $value = $this->castValueIfNeeded("removeItem", $value);

        if ($this->removeItem === null) {
            $this->removeItem = array();
        }

        if (!is_array($this->removeItem)) {
            $this->removeItem = array($this->removeItem);
        }

        $this->removeItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return RemoveItemType[]
     */
    public function getRemoveItem()
    {
        return $this->removeItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value RemoveItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setRemoveItem(array $value)
    {
        $this->removeItem = $this->castValueIfNeeded("removeItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SuppressReadReceiptType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addSuppressReadReceipt(SuppressReadReceiptType $value)
    {
        $value = $this->castValueIfNeeded("suppressReadReceipt", $value);

        if ($this->suppressReadReceipt === null) {
            $this->suppressReadReceipt = array();
        }

        if (!is_array($this->suppressReadReceipt)) {
            $this->suppressReadReceipt = array($this->suppressReadReceipt);
        }

        $this->suppressReadReceipt[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return SuppressReadReceiptType[]
     */
    public function getSuppressReadReceipt()
    {
        return $this->suppressReadReceipt;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SuppressReadReceiptType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setSuppressReadReceipt(array $value)
    {
        $this->suppressReadReceipt = $this->castValueIfNeeded("suppressReadReceipt", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PostReplyItemType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addPostReplyItem(PostReplyItemType $value)
    {
        $value = $this->castValueIfNeeded("postReplyItem", $value);

        if ($this->postReplyItem === null) {
            $this->postReplyItem = array();
        }

        if (!is_array($this->postReplyItem)) {
            $this->postReplyItem = array($this->postReplyItem);
        }

        $this->postReplyItem[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return PostReplyItemType[]
     */
    public function getPostReplyItem()
    {
        return $this->postReplyItem;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PostReplyItemType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setPostReplyItem(array $value)
    {
        $this->postReplyItem = $this->castValueIfNeeded("postReplyItem", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AcceptSharingInvitationType
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function addAcceptSharingInvitation(AcceptSharingInvitationType $value)
    {
        $value = $this->castValueIfNeeded("acceptSharingInvitation", $value);

        if ($this->acceptSharingInvitation === null) {
            $this->acceptSharingInvitation = array();
        }

        if (!is_array($this->acceptSharingInvitation)) {
            $this->acceptSharingInvitation = array($this->acceptSharingInvitation);
        }

        $this->acceptSharingInvitation[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return AcceptSharingInvitationType[]
     */
    public function getAcceptSharingInvitation()
    {
        return $this->acceptSharingInvitation;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AcceptSharingInvitationType[]
     * @return NonEmptyArrayOfResponseObjectsType
     */
    public function setAcceptSharingInvitation(array $value)
    {
        $this->acceptSharingInvitation = $this->castValueIfNeeded("acceptSharingInvitation", $value);
        return $this;
    }
}
