<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing OccurrencesRangeType
 *
 *
 * XSD Type: OccurrencesRangeType
 */
class OccurrencesRangeType extends Type
{

    /**
     * @var \DateTime
     */
    protected $start = null;

    /**
     * @var \DateTime
     */
    protected $end = null;

    /**
     * @var integer
     */
    protected $count = null;

    /**
     * @var boolean
     */
    protected $compareOriginalStartTime = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return OccurrencesRangeType
     */
    public function setStart(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->start = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return OccurrencesRangeType
     */
    public function setEnd(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->end = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return OccurrencesRangeType
     */
    public function setCount($value)
    {
        $this->count = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isCompareOriginalStartTime()
    {
        return ((bool) $this->compareOriginalStartTime);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getCompareOriginalStartTime()
    {
        return $this->compareOriginalStartTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return OccurrencesRangeType
     */
    public function setCompareOriginalStartTime($value)
    {
        $this->compareOriginalStartTime = $value;
        return $this;
    }
}
