<?php

namespace garethp\ews\API\Type;

/**
 * Class representing OutOfOfficeInsightValueType
 *
 *
 * XSD Type: OutOfOfficeInsightValue
 */
class OutOfOfficeInsightValueType extends InsightValueType
{

    /**
     * @var \DateTime
     */
    protected $startTime = null;

    /**
     * @var \DateTime
     */
    protected $endTime = null;

    /**
     * @var string
     */
    protected $message = null;

    /**
     * @var string
     */
    protected $culture = null;

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return OutOfOfficeInsightValueType
     */
    public function setStartTime(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->startTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return OutOfOfficeInsightValueType
     */
    public function setEndTime(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->endTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return OutOfOfficeInsightValueType
     */
    public function setMessage($value)
    {
        $this->message = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getCulture()
    {
        return $this->culture;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return OutOfOfficeInsightValueType
     */
    public function setCulture($value)
    {
        $this->culture = $value;
        return $this;
    }
}
