<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ParcelDeliveryEntityType
 *
 *
 * XSD Type: ParcelDeliveryEntityType
 */
class ParcelDeliveryEntityType extends Type
{

    /**
     * @var string
     */
    protected $carrier = null;

    /**
     * @var string
     */
    protected $trackingNumber = null;

    /**
     * @var string
     */
    protected $trackingUrl = null;

    /**
     * @var string
     */
    protected $expectedArrivalFrom = null;

    /**
     * @var string
     */
    protected $expectedArrivalUntil = null;

    /**
     * @var string
     */
    protected $product = null;

    /**
     * @var string
     */
    protected $productUrl = null;

    /**
     * @var string
     */
    protected $productImage = null;

    /**
     * @var string
     */
    protected $productSku = null;

    /**
     * @var string
     */
    protected $productDescription = null;

    /**
     * @var string
     */
    protected $productBrand = null;

    /**
     * @var string
     */
    protected $productColor = null;

    /**
     * @var string
     */
    protected $orderNumber = null;

    /**
     * @var string
     */
    protected $seller = null;

    /**
     * @var string
     */
    protected $orderStatus = null;

    /**
     * @var string
     */
    protected $addressName = null;

    /**
     * @var string
     */
    protected $streetAddress = null;

    /**
     * @var string
     */
    protected $addressLocality = null;

    /**
     * @var string
     */
    protected $addressRegion = null;

    /**
     * @var string
     */
    protected $addressCountry = null;

    /**
     * @var string
     */
    protected $postalCode = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getCarrier()
    {
        return $this->carrier;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setCarrier($value)
    {
        $this->carrier = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->trackingNumber;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setTrackingNumber($value)
    {
        $this->trackingNumber = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTrackingUrl()
    {
        return $this->trackingUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setTrackingUrl($value)
    {
        $this->trackingUrl = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getExpectedArrivalFrom()
    {
        return $this->expectedArrivalFrom;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setExpectedArrivalFrom($value)
    {
        $this->expectedArrivalFrom = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getExpectedArrivalUntil()
    {
        return $this->expectedArrivalUntil;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setExpectedArrivalUntil($value)
    {
        $this->expectedArrivalUntil = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setProduct($value)
    {
        $this->product = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProductUrl()
    {
        return $this->productUrl;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setProductUrl($value)
    {
        $this->productUrl = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProductImage()
    {
        return $this->productImage;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setProductImage($value)
    {
        $this->productImage = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProductSku()
    {
        return $this->productSku;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setProductSku($value)
    {
        $this->productSku = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProductDescription()
    {
        return $this->productDescription;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setProductDescription($value)
    {
        $this->productDescription = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProductBrand()
    {
        return $this->productBrand;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setProductBrand($value)
    {
        $this->productBrand = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProductColor()
    {
        return $this->productColor;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setProductColor($value)
    {
        $this->productColor = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->orderNumber;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setOrderNumber($value)
    {
        $this->orderNumber = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSeller()
    {
        return $this->seller;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setSeller($value)
    {
        $this->seller = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOrderStatus()
    {
        return $this->orderStatus;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setOrderStatus($value)
    {
        $this->orderStatus = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAddressName()
    {
        return $this->addressName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setAddressName($value)
    {
        $this->addressName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getStreetAddress()
    {
        return $this->streetAddress;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setStreetAddress($value)
    {
        $this->streetAddress = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAddressLocality()
    {
        return $this->addressLocality;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setAddressLocality($value)
    {
        $this->addressLocality = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAddressRegion()
    {
        return $this->addressRegion;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setAddressRegion($value)
    {
        $this->addressRegion = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAddressCountry()
    {
        return $this->addressCountry;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setAddressCountry($value)
    {
        $this->addressCountry = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postalCode;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ParcelDeliveryEntityType
     */
    public function setPostalCode($value)
    {
        $this->postalCode = $value;
        return $this;
    }
}
