<?php

namespace garethp\ews\API\Type;

/**
 * Class representing PeopleRefinerType
 *
 *
 * XSD Type: PeopleRefinerType
 */
class PeopleRefinerType extends SearchRefinerType
{

    /**
     * @var string
     */
    protected $displayName = null;

    /**
     * @var string
     */
    protected $smtpAddress = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PeopleRefinerType
     */
    public function setDisplayName($value)
    {
        $this->displayName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSmtpAddress()
    {
        return $this->smtpAddress;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PeopleRefinerType
     */
    public function setSmtpAddress($value)
    {
        $this->smtpAddress = $value;
        return $this;
    }
}
