<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing PermissionSetType
 *
 * The set of permissions on a folder
 * XSD Type: PermissionSetType
 *
 * @method PermissionSetType addPermissions(PermissionType $permissions)
 * @method PermissionSetType addUnknownEntries(string $unknownEntries)
 */
class PermissionSetType extends Type
{

    /**
     * @var \garethp\ews\API\Type\PermissionType[]
     */
    protected $permissions = null;

    /**
     * @var string[]
     */
    protected $unknownEntries = null;

    /**
     * @autogenerated This method is safe to replace
     * @return PermissionType[]
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PermissionType[]
     * @return PermissionSetType
     */
    public function setPermissions(array $value)
    {
        $this->permissions = $this->castValueIfNeeded("permissions", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getUnknownEntries()
    {
        return $this->unknownEntries;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return PermissionSetType
     */
    public function setUnknownEntries(array $value)
    {
        $this->unknownEntries = $this->castValueIfNeeded("unknownEntries", $value);
        return $this;
    }
}
