<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing PersonType
 *
 *
 * XSD Type: PersonType
 */
class PersonType extends Type
{

    /**
     * @var string
     */
    protected $fullName = null;

    /**
     * @var string
     */
    protected $givenName = null;

    /**
     * @var string
     */
    protected $surname = null;

    /**
     * @var string
     */
    protected $phoneNumber = null;

    /**
     * @var string
     */
    protected $sMSNumber = null;

    /**
     * @var string
     */
    protected $emailAddress = null;

    /**
     * @var string
     */
    protected $alias = null;

    /**
     * @var string
     */
    protected $department = null;

    /**
     * @var string
     */
    protected $linkedInProfileLink = null;

    /**
     * @var \garethp\ews\API\Type\SkillInsightValueType[]
     */
    protected $skills = null;

    /**
     * @var string
     */
    protected $professionalBiography = null;

    /**
     * @var \garethp\ews\API\Type\ProfileInsightValueType[]
     */
    protected $managementChain = null;

    /**
     * @var \garethp\ews\API\Type\ProfileInsightValueType[]
     */
    protected $directReports = null;

    /**
     * @var \garethp\ews\API\Type\ProfileInsightValueType[]
     */
    protected $peers = null;

    /**
     * @var string
     */
    protected $teamSize = null;

    /**
     * @var \garethp\ews\API\Type\JobInsightValueType[]
     */
    protected $currentJob = null;

    /**
     * @var string
     */
    protected $birthday = null;

    /**
     * @var string
     */
    protected $hometown = null;

    /**
     * @var string
     */
    protected $currentLocation = null;

    /**
     * @var \garethp\ews\API\Type\CompanyInsightValueType[]
     */
    protected $companyProfile = null;

    /**
     * @var string
     */
    protected $office = null;

    /**
     * @var string
     */
    protected $headline = null;

    /**
     * @var \garethp\ews\API\Type\ProfileInsightValueType[]
     */
    protected $mutualConnections = null;

    /**
     * @var string
     */
    protected $title = null;

    /**
     * @var \garethp\ews\API\Type\ProfileInsightValueType
     */
    protected $mutualManager = null;

    /**
     * @var \garethp\ews\API\Type\InsightType[]
     */
    protected $insights = null;

    /**
     * @var \garethp\ews\API\Type\UserProfilePictureType
     */
    protected $userProfilePicture = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getFullName()
    {
        return $this->fullName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setFullName($value)
    {
        $this->fullName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getGivenName()
    {
        return $this->givenName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setGivenName($value)
    {
        $this->givenName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setSurname($value)
    {
        $this->surname = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setPhoneNumber($value)
    {
        $this->phoneNumber = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSMSNumber()
    {
        return $this->sMSNumber;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setSMSNumber($value)
    {
        $this->sMSNumber = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->emailAddress;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setEmailAddress($value)
    {
        $this->emailAddress = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setAlias($value)
    {
        $this->alias = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setDepartment($value)
    {
        $this->department = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getLinkedInProfileLink()
    {
        return $this->linkedInProfileLink;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setLinkedInProfileLink($value)
    {
        $this->linkedInProfileLink = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SkillInsightValueType
     * @return PersonType
     */
    public function addSkills(SkillInsightValueType $value)
    {
        if ($this->skills === null) {
                        $this->skills = array();
        }

        if (!is_array($this->skills)) {
            $this->skills = array($this->skills);
        }

        $this->skills[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return SkillInsightValueType[]
     */
    public function getSkills()
    {
        return $this->skills;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SkillInsightValueType[]|SkillInsightValueType
     * @return PersonType
     */
    public function setSkills(array|SkillInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->skills = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getProfessionalBiography()
    {
        return $this->professionalBiography;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setProfessionalBiography($value)
    {
        $this->professionalBiography = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType
     * @return PersonType
     */
    public function addManagementChain(ProfileInsightValueType $value)
    {
        if ($this->managementChain === null) {
                        $this->managementChain = array();
        }

        if (!is_array($this->managementChain)) {
            $this->managementChain = array($this->managementChain);
        }

        $this->managementChain[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ProfileInsightValueType[]
     */
    public function getManagementChain()
    {
        return $this->managementChain;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType[]|ProfileInsightValueType
     * @return PersonType
     */
    public function setManagementChain(array|ProfileInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->managementChain = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType
     * @return PersonType
     */
    public function addDirectReports(ProfileInsightValueType $value)
    {
        if ($this->directReports === null) {
                        $this->directReports = array();
        }

        if (!is_array($this->directReports)) {
            $this->directReports = array($this->directReports);
        }

        $this->directReports[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ProfileInsightValueType[]
     */
    public function getDirectReports()
    {
        return $this->directReports;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType[]|ProfileInsightValueType
     * @return PersonType
     */
    public function setDirectReports(array|ProfileInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->directReports = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType
     * @return PersonType
     */
    public function addPeers(ProfileInsightValueType $value)
    {
        if ($this->peers === null) {
                        $this->peers = array();
        }

        if (!is_array($this->peers)) {
            $this->peers = array($this->peers);
        }

        $this->peers[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ProfileInsightValueType[]
     */
    public function getPeers()
    {
        return $this->peers;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType[]|ProfileInsightValueType
     * @return PersonType
     */
    public function setPeers(array|ProfileInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->peers = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTeamSize()
    {
        return $this->teamSize;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setTeamSize($value)
    {
        $this->teamSize = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value JobInsightValueType
     * @return PersonType
     */
    public function addCurrentJob(JobInsightValueType $value)
    {
        if ($this->currentJob === null) {
                        $this->currentJob = array();
        }

        if (!is_array($this->currentJob)) {
            $this->currentJob = array($this->currentJob);
        }

        $this->currentJob[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return JobInsightValueType[]
     */
    public function getCurrentJob()
    {
        return $this->currentJob;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value JobInsightValueType[]|JobInsightValueType
     * @return PersonType
     */
    public function setCurrentJob(array|JobInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->currentJob = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setBirthday($value)
    {
        $this->birthday = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getHometown()
    {
        return $this->hometown;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setHometown($value)
    {
        $this->hometown = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getCurrentLocation()
    {
        return $this->currentLocation;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setCurrentLocation($value)
    {
        $this->currentLocation = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CompanyInsightValueType
     * @return PersonType
     */
    public function addCompanyProfile(CompanyInsightValueType $value)
    {
        if ($this->companyProfile === null) {
                        $this->companyProfile = array();
        }

        if (!is_array($this->companyProfile)) {
            $this->companyProfile = array($this->companyProfile);
        }

        $this->companyProfile[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return CompanyInsightValueType[]
     */
    public function getCompanyProfile()
    {
        return $this->companyProfile;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value CompanyInsightValueType[]|CompanyInsightValueType
     * @return PersonType
     */
    public function setCompanyProfile(array|CompanyInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->companyProfile = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOffice()
    {
        return $this->office;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setOffice($value)
    {
        $this->office = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getHeadline()
    {
        return $this->headline;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setHeadline($value)
    {
        $this->headline = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType
     * @return PersonType
     */
    public function addMutualConnections(ProfileInsightValueType $value)
    {
        if ($this->mutualConnections === null) {
                        $this->mutualConnections = array();
        }

        if (!is_array($this->mutualConnections)) {
            $this->mutualConnections = array($this->mutualConnections);
        }

        $this->mutualConnections[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ProfileInsightValueType[]
     */
    public function getMutualConnections()
    {
        return $this->mutualConnections;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType[]|ProfileInsightValueType
     * @return PersonType
     */
    public function setMutualConnections(array|ProfileInsightValueType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->mutualConnections = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PersonType
     */
    public function setTitle($value)
    {
        $this->title = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ProfileInsightValueType
     */
    public function getMutualManager()
    {
        return $this->mutualManager;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ProfileInsightValueType
     * @return PersonType
     */
    public function setMutualManager(ProfileInsightValueType $value)
    {
        $this->mutualManager = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value InsightType
     * @return PersonType
     */
    public function addInsights(InsightType $value)
    {
        if ($this->insights === null) {
                        $this->insights = array();
        }

        if (!is_array($this->insights)) {
            $this->insights = array($this->insights);
        }

        $this->insights[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return InsightType[]
     */
    public function getInsights()
    {
        return $this->insights;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value InsightType[]|InsightType
     * @return PersonType
     */
    public function setInsights(array|InsightType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->insights = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return UserProfilePictureType
     */
    public function getUserProfilePicture()
    {
        return $this->userProfilePicture;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value UserProfilePictureType
     * @return PersonType
     */
    public function setUserProfilePicture(UserProfilePictureType $value)
    {
        $this->userProfilePicture = $value;
        return $this;
    }
}
