<?php

namespace garethp\ews\API\Type;

/**
 * Class representing PhoneEntityType
 *
 *
 * XSD Type: PhoneEntityType
 */
class PhoneEntityType extends EntityType
{

    /**
     * @var string
     */
    protected $originalPhoneString = null;

    /**
     * @var string
     */
    protected $phoneString = null;

    /**
     * @var string
     */
    protected $type = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOriginalPhoneString()
    {
        return $this->originalPhoneString;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PhoneEntityType
     */
    public function setOriginalPhoneString($value)
    {
        $this->originalPhoneString = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPhoneString()
    {
        return $this->phoneString;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PhoneEntityType
     */
    public function setPhoneString($value)
    {
        $this->phoneString = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return PhoneEntityType
     */
    public function setType($value)
    {
        $this->type = $value;
        return $this;
    }
}
