<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing RecurrenceType
 *
 *
 * XSD Type: RecurrenceType
 */
class RecurrenceType extends Type
{

    /**
     * @var \garethp\ews\API\Type\RelativeYearlyRecurrencePatternType
     */
    protected $relativeYearlyRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\AbsoluteYearlyRecurrencePatternType
     */
    protected $absoluteYearlyRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\RelativeMonthlyRecurrencePatternType
     */
    protected $relativeMonthlyRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\AbsoluteMonthlyRecurrencePatternType
     */
    protected $absoluteMonthlyRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\WeeklyRecurrencePatternType
     */
    protected $weeklyRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\DailyRecurrencePatternType
     */
    protected $dailyRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\NoEndRecurrenceRangeType
     */
    protected $noEndRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\EndDateRecurrenceRangeType
     */
    protected $endDateRecurrence = null;

    /**
     * @var \garethp\ews\API\Type\NumberedRecurrenceRangeType
     */
    protected $numberedRecurrence = null;

    /**
     * @return RelativeYearlyRecurrencePatternType
     */
    public function getRelativeYearlyRecurrence()
    {
        return $this->relativeYearlyRecurrence;
    }

    /**
     * @return AbsoluteYearlyRecurrencePatternType
     */
    public function getAbsoluteYearlyRecurrence()
    {
        return $this->absoluteYearlyRecurrence;
    }

    /**
     * @return RelativeMonthlyRecurrencePatternType
     */
    public function getRelativeMonthlyRecurrence()
    {
        return $this->relativeMonthlyRecurrence;
    }

    /**
     * @return AbsoluteMonthlyRecurrencePatternType
     */
    public function getAbsoluteMonthlyRecurrence()
    {
        return $this->absoluteMonthlyRecurrence;
    }

    /**
     * @return WeeklyRecurrencePatternType
     */
    public function getWeeklyRecurrence()
    {
        return $this->weeklyRecurrence;
    }

    /**
     * @return DailyRecurrencePatternType
     */
    public function getDailyRecurrence()
    {
        return $this->dailyRecurrence;
    }

    /**
     * @return NoEndRecurrenceRangeType
     */
    public function getNoEndRecurrence()
    {
        return $this->noEndRecurrence;
    }

    /**
     * @return EndDateRecurrenceRangeType
     */
    public function getEndDateRecurrence()
    {
        return $this->endDateRecurrence;
    }

    /**
     * @return NumberedRecurrenceRangeType
     */
    public function getNumberedRecurrence()
    {
        return $this->numberedRecurrence;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value RelativeYearlyRecurrencePatternType
     * @return RecurrenceType
     */
    public function setRelativeYearlyRecurrence(RelativeYearlyRecurrencePatternType $value)
    {
        $this->relativeYearlyRecurrence = $this->castValueIfNeeded("relativeYearlyRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AbsoluteYearlyRecurrencePatternType
     * @return RecurrenceType
     */
    public function setAbsoluteYearlyRecurrence(AbsoluteYearlyRecurrencePatternType $value)
    {
        $this->absoluteYearlyRecurrence = $this->castValueIfNeeded("absoluteYearlyRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value RelativeMonthlyRecurrencePatternType
     * @return RecurrenceType
     */
    public function setRelativeMonthlyRecurrence(RelativeMonthlyRecurrencePatternType $value)
    {
        $this->relativeMonthlyRecurrence = $this->castValueIfNeeded("relativeMonthlyRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value AbsoluteMonthlyRecurrencePatternType
     * @return RecurrenceType
     */
    public function setAbsoluteMonthlyRecurrence(AbsoluteMonthlyRecurrencePatternType $value)
    {
        $this->absoluteMonthlyRecurrence = $this->castValueIfNeeded("absoluteMonthlyRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value WeeklyRecurrencePatternType
     * @return RecurrenceType
     */
    public function setWeeklyRecurrence(WeeklyRecurrencePatternType $value)
    {
        $this->weeklyRecurrence = $this->castValueIfNeeded("weeklyRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value DailyRecurrencePatternType
     * @return RecurrenceType
     */
    public function setDailyRecurrence(DailyRecurrencePatternType $value)
    {
        $this->dailyRecurrence = $this->castValueIfNeeded("dailyRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value NoEndRecurrenceRangeType
     * @return RecurrenceType
     */
    public function setNoEndRecurrence(NoEndRecurrenceRangeType $value)
    {
        $this->noEndRecurrence = $this->castValueIfNeeded("noEndRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value EndDateRecurrenceRangeType
     * @return RecurrenceType
     */
    public function setEndDateRecurrence(EndDateRecurrenceRangeType $value)
    {
        $this->endDateRecurrence = $this->castValueIfNeeded("endDateRecurrence", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value NumberedRecurrenceRangeType
     * @return RecurrenceType
     */
    public function setNumberedRecurrence(NumberedRecurrenceRangeType $value)
    {
        $this->numberedRecurrence = $this->castValueIfNeeded("numberedRecurrence", $value);
        return $this;
    }
}
