<?php

namespace garethp\ews\API\Type;

/**
 * Class representing RecurringMasterItemIdRangesType
 *
 *
 * XSD Type: RecurringMasterItemIdRangesType
 */
class RecurringMasterItemIdRangesType extends ItemIdType
{

    /**
     * @var \garethp\ews\API\Type\OccurrencesRangeType[]
     */
    protected $ranges = null;

    /**
     * @autogenerated This method is safe to replace
     * @param $value OccurrencesRangeType
     * @return RecurringMasterItemIdRangesType
     */
    public function addRanges(OccurrencesRangeType $value)
    {
        if ($this->ranges === null) {
                        $this->ranges = array();
        }

        if (!is_array($this->ranges)) {
            $this->ranges = array($this->ranges);
        }

        $this->ranges[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return OccurrencesRangeType[]
     */
    public function getRanges()
    {
        return $this->ranges;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value OccurrencesRangeType[]|OccurrencesRangeType
     * @return RecurringMasterItemIdRangesType
     */
    public function setRanges(array|OccurrencesRangeType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->ranges = $value;
        return $this;
    }
}
