<?php

namespace garethp\ews\API\Type;

/**
 * Class representing RelativeYearlyRecurrencePatternType
 *
 *
 * XSD Type: RelativeYearlyRecurrencePatternType
 */
class RelativeYearlyRecurrencePatternType extends RecurrencePatternBaseType
{

    /**
     * @var string
     */
    protected $daysOfWeek = null;

    /**
     * @var string
     */
    protected $dayOfWeekIndex = null;

    /**
     * @var string
     */
    protected $month = null;

    /**
     * @return string
     */
    public function getDaysOfWeek()
    {
        return $this->daysOfWeek;
    }

    /**
     * @return string
     */
    public function getDayOfWeekIndex()
    {
        return $this->dayOfWeekIndex;
    }

    /**
     * @return string
     */
    public function getMonth()
    {
        return $this->month;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RelativeYearlyRecurrencePatternType
     */
    public function setDaysOfWeek($value)
    {
        $this->daysOfWeek = $this->castValueIfNeeded("daysOfWeek", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RelativeYearlyRecurrencePatternType
     */
    public function setDayOfWeekIndex($value)
    {
        $this->dayOfWeekIndex = $this->castValueIfNeeded("dayOfWeekIndex", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RelativeYearlyRecurrencePatternType
     */
    public function setMonth($value)
    {
        $this->month = $this->castValueIfNeeded("month", $value);
        return $this;
    }
}
