<?php

namespace garethp\ews\API\Type;

/**
 * Class representing ReplyAllToItemType
 *
 *
 * XSD Type: ReplyAllToItemType
 */
class ReplyAllToItemType extends SmartResponseType
{

    /**
     * @var boolean
     */
    protected $isSpecificMessageReply = null;

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isSpecificMessageReply()
    {
        return ((bool) $this->isSpecificMessageReply);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIsSpecificMessageReply()
    {
        return $this->isSpecificMessageReply;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return ReplyAllToItemType
     */
    public function setIsSpecificMessageReply($value)
    {
        $this->isSpecificMessageReply = $value;
        return $this;
    }
}
