<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing RetentionPolicyTagType
 *
 * Retention policy tag.
 * XSD Type: RetentionPolicyTagType
 */
class RetentionPolicyTagType extends Type
{

    /**
     * @var string
     */
    protected $displayName = null;

    /**
     * @var string
     */
    protected $retentionId = null;

    /**
     * @var integer
     */
    protected $retentionPeriod = null;

    /**
     * @var string
     */
    protected $type = null;

    /**
     * @var string
     */
    protected $retentionAction = null;

    /**
     * @var string
     */
    protected $description = null;

    /**
     * @var boolean
     */
    protected $isVisible = null;

    /**
     * @var boolean
     */
    protected $optedInto = null;

    /**
     * @var boolean
     */
    protected $isArchive = null;

    /**
     * @var string
     */
    protected $parentLabelIdentity = null;

    /**
     * @var integer
     */
    protected $priority = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RetentionPolicyTagType
     */
    public function setDisplayName($value)
    {
        $this->displayName = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getRetentionId()
    {
        return $this->retentionId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RetentionPolicyTagType
     */
    public function setRetentionId($value)
    {
        $this->retentionId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getRetentionPeriod()
    {
        return $this->retentionPeriod;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return RetentionPolicyTagType
     */
    public function setRetentionPeriod($value)
    {
        $this->retentionPeriod = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RetentionPolicyTagType
     */
    public function setType($value)
    {
        $this->type = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getRetentionAction()
    {
        return $this->retentionAction;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RetentionPolicyTagType
     */
    public function setRetentionAction($value)
    {
        $this->retentionAction = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RetentionPolicyTagType
     */
    public function setDescription($value)
    {
        $this->description = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isVisible()
    {
        return ((bool) $this->isVisible);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIsVisible()
    {
        return $this->isVisible;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return RetentionPolicyTagType
     */
    public function setIsVisible($value)
    {
        $this->isVisible = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isOptedInto()
    {
        return ((bool) $this->optedInto);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getOptedInto()
    {
        return $this->optedInto;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return RetentionPolicyTagType
     */
    public function setOptedInto($value)
    {
        $this->optedInto = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isArchive()
    {
        return ((bool) $this->isArchive);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIsArchive()
    {
        return $this->isArchive;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return RetentionPolicyTagType
     */
    public function setIsArchive($value)
    {
        $this->isArchive = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getParentLabelIdentity()
    {
        return $this->parentLabelIdentity;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return RetentionPolicyTagType
     */
    public function setParentLabelIdentity($value)
    {
        $this->parentLabelIdentity = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return RetentionPolicyTagType
     */
    public function setPriority($value)
    {
        $this->priority = $value;
        return $this;
    }
}
