<?php

namespace garethp\ews\API\Type;

/**
 * Class representing SearchFolderType
 *
 *
 * XSD Type: SearchFolderType
 */
class SearchFolderType extends FolderType
{

    /**
     * @var \garethp\ews\API\Type\SearchParametersType
     */
    protected $searchParameters = null;

    /**
     * @return SearchParametersType
     */
    public function getSearchParameters()
    {
        return $this->searchParameters;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SearchParametersType
     * @return SearchFolderType
     */
    public function setSearchParameters(SearchParametersType $value)
    {
        $this->searchParameters = $this->castValueIfNeeded("searchParameters", $value);
        return $this;
    }
}
