<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing SearchPreviewItemType
 *
 * Mailbox search preview item.
 * XSD Type: SearchPreviewItemType
 */
class SearchPreviewItemType extends Type
{

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $id = null;

    /**
     * @var \garethp\ews\API\Type\PreviewItemMailboxType
     */
    protected $mailbox = null;

    /**
     * @var \garethp\ews\API\Type\ItemIdType
     */
    protected $parentId = null;

    /**
     * @var string
     */
    protected $itemClass = null;

    /**
     * @var string
     */
    protected $uniqueHash = null;

    /**
     * @var string
     */
    protected $sortValue = null;

    /**
     * @var string
     */
    protected $owaLink = null;

    /**
     * @var string
     */
    protected $sender = null;

    /**
     * @var string[]
     */
    protected $toRecipients = null;

    /**
     * @var string[]
     */
    protected $ccRecipients = null;

    /**
     * @var string[]
     */
    protected $bccRecipients = null;

    /**
     * @var \DateTime
     */
    protected $createdTime = null;

    /**
     * @var \DateTime
     */
    protected $receivedTime = null;

    /**
     * @var \DateTime
     */
    protected $sentTime = null;

    /**
     * @var string
     */
    protected $subject = null;

    /**
     * @var integer
     */
    protected $size = null;

    /**
     * @var string
     */
    protected $preview = null;

    /**
     * @var string
     */
    protected $importance = null;

    /**
     * @var boolean
     */
    protected $read = null;

    /**
     * @var boolean
     */
    protected $hasAttachment = null;

    /**
     * @var \garethp\ews\API\Type\ExtendedPropertyType[]
     */
    protected $extendedProperties = null;

    /**
     * @autogenerated This method is safe to replace
     * @return ItemIdType
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ItemIdType
     * @return SearchPreviewItemType
     */
    public function setId(ItemIdType $value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return PreviewItemMailboxType
     */
    public function getMailbox()
    {
        return $this->mailbox;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value PreviewItemMailboxType
     * @return SearchPreviewItemType
     */
    public function setMailbox(PreviewItemMailboxType $value)
    {
        $this->mailbox = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ItemIdType
     */
    public function getParentId()
    {
        return $this->parentId;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ItemIdType
     * @return SearchPreviewItemType
     */
    public function setParentId(ItemIdType $value)
    {
        $this->parentId = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getItemClass()
    {
        return $this->itemClass;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setItemClass($value)
    {
        $this->itemClass = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getUniqueHash()
    {
        return $this->uniqueHash;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setUniqueHash($value)
    {
        $this->uniqueHash = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSortValue()
    {
        return $this->sortValue;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setSortValue($value)
    {
        $this->sortValue = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOwaLink()
    {
        return $this->owaLink;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setOwaLink($value)
    {
        $this->owaLink = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setSender($value)
    {
        $this->sender = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function addToRecipients($value)
    {
        if ($this->toRecipients === null) {
                        $this->toRecipients = array();
        }

        if (!is_array($this->toRecipients)) {
            $this->toRecipients = array($this->toRecipients);
        }

        $this->toRecipients[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getToRecipients()
    {
        return $this->toRecipients;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return SearchPreviewItemType
     */
    public function setToRecipients(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->toRecipients = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function addCcRecipients($value)
    {
        if ($this->ccRecipients === null) {
                        $this->ccRecipients = array();
        }

        if (!is_array($this->ccRecipients)) {
            $this->ccRecipients = array($this->ccRecipients);
        }

        $this->ccRecipients[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getCcRecipients()
    {
        return $this->ccRecipients;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return SearchPreviewItemType
     */
    public function setCcRecipients(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->ccRecipients = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function addBccRecipients($value)
    {
        if ($this->bccRecipients === null) {
                        $this->bccRecipients = array();
        }

        if (!is_array($this->bccRecipients)) {
            $this->bccRecipients = array($this->bccRecipients);
        }

        $this->bccRecipients[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getBccRecipients()
    {
        return $this->bccRecipients;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return SearchPreviewItemType
     */
    public function setBccRecipients(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->bccRecipients = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getCreatedTime()
    {
        return $this->createdTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return SearchPreviewItemType
     */
    public function setCreatedTime(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->createdTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getReceivedTime()
    {
        return $this->receivedTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return SearchPreviewItemType
     */
    public function setReceivedTime(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->receivedTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \DateTime
     */
    public function getSentTime()
    {
        return $this->sentTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return SearchPreviewItemType
     */
    public function setSentTime(\DateTime|string $value)
    {
        if (is_string($value)) {
            $value = new \DateTime($value);
        }
        $this->sentTime = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setSubject($value)
    {
        $this->subject = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return SearchPreviewItemType
     */
    public function setSize($value)
    {
        $this->size = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getPreview()
    {
        return $this->preview;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setPreview($value)
    {
        $this->preview = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getImportance()
    {
        return $this->importance;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SearchPreviewItemType
     */
    public function setImportance($value)
    {
        $this->importance = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isRead()
    {
        return ((bool) $this->read);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getRead()
    {
        return $this->read;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return SearchPreviewItemType
     */
    public function setRead($value)
    {
        $this->read = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isHasAttachment()
    {
        return ((bool) $this->hasAttachment);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getHasAttachment()
    {
        return $this->hasAttachment;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return SearchPreviewItemType
     */
    public function setHasAttachment($value)
    {
        $this->hasAttachment = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ExtendedPropertyType
     * @return SearchPreviewItemType
     */
    public function addExtendedProperties(ExtendedPropertyType $value)
    {
        if ($this->extendedProperties === null) {
                        $this->extendedProperties = array();
        }

        if (!is_array($this->extendedProperties)) {
            $this->extendedProperties = array($this->extendedProperties);
        }

        $this->extendedProperties[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ExtendedPropertyType[]
     */
    public function getExtendedProperties()
    {
        return $this->extendedProperties;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ExtendedPropertyType[]|ExtendedPropertyType
     * @return SearchPreviewItemType
     */
    public function setExtendedProperties(array|ExtendedPropertyType $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->extendedProperties = $value;
        return $this;
    }
}
