<?php

namespace garethp\ews\API\Type;

/**
 * Class representing SeekToConditionPageViewType
 *
 *
 * XSD Type: SeekToConditionPageViewType
 */
class SeekToConditionPageViewType extends BasePagingType
{

    /**
     * @var string
     */
    protected $basePoint = null;

    /**
     * @var \garethp\ews\API\Type\RestrictionType
     */
    protected $condition = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getBasePoint()
    {
        return $this->basePoint;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SeekToConditionPageViewType
     */
    public function setBasePoint($value)
    {
        $this->basePoint = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return RestrictionType
     */
    public function getCondition()
    {
        return $this->condition;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value RestrictionType
     * @return SeekToConditionPageViewType
     */
    public function setCondition(RestrictionType $value)
    {
        $this->condition = $value;
        return $this;
    }
}
