<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing ServerVersionInfo
 */
class ServerVersionInfo extends Type
{

    /**
     * @var integer
     */
    protected $majorVersion = null;

    /**
     * @var integer
     */
    protected $minorVersion = null;

    /**
     * @var integer
     */
    protected $majorBuildNumber = null;

    /**
     * @var integer
     */
    protected $minorBuildNumber = null;

    /**
     * @var string
     */
    protected $version = null;

    /**
     * @return integer
     */
    public function getMajorVersion()
    {
        return $this->majorVersion;
    }

    /**
     * @return integer
     */
    public function getMinorVersion()
    {
        return $this->minorVersion;
    }

    /**
     * @return integer
     */
    public function getMajorBuildNumber()
    {
        return $this->majorBuildNumber;
    }

    /**
     * @return integer
     */
    public function getMinorBuildNumber()
    {
        return $this->minorBuildNumber;
    }

    /**
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ServerVersionInfo
     */
    public function setMajorVersion($value)
    {
        $this->majorVersion = $this->castValueIfNeeded("majorVersion", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ServerVersionInfo
     */
    public function setMinorVersion($value)
    {
        $this->minorVersion = $this->castValueIfNeeded("minorVersion", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ServerVersionInfo
     */
    public function setMajorBuildNumber($value)
    {
        $this->majorBuildNumber = $this->castValueIfNeeded("majorBuildNumber", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ServerVersionInfo
     */
    public function setMinorBuildNumber($value)
    {
        $this->minorBuildNumber = $this->castValueIfNeeded("minorBuildNumber", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ServerVersionInfo
     */
    public function setVersion($value)
    {
        $this->version = $this->castValueIfNeeded("version", $value);
        return $this;
    }
}
