<?php

namespace garethp\ews\API\Type;

/**
 * Class representing SharePointURLsServiceConfigurationType
 *
 *
 * XSD Type: SharePointURLsServiceConfiguration
 */
class SharePointURLsServiceConfigurationType extends ServiceConfigurationType
{

    /**
     * @var string
     */
    protected $internalSPMySiteHostURL = null;

    /**
     * @var string
     */
    protected $externalSPMySiteHostURL = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getInternalSPMySiteHostURL()
    {
        return $this->internalSPMySiteHostURL;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SharePointURLsServiceConfigurationType
     */
    public function setInternalSPMySiteHostURL($value)
    {
        $this->internalSPMySiteHostURL = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getExternalSPMySiteHostURL()
    {
        return $this->externalSPMySiteHostURL;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SharePointURLsServiceConfigurationType
     */
    public function setExternalSPMySiteHostURL($value)
    {
        $this->externalSPMySiteHostURL = $value;
        return $this;
    }
}
