<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing SingleLargeArchiveSearchScopeType
 *
 *
 * XSD Type: SingleLargeArchiveSearchScopeType
 */
class SingleLargeArchiveSearchScopeType extends Type
{

    /**
     * @var string
     */
    protected $mailboxGuid = null;

    /**
     * @var \garethp\ews\API\Type\SearchFolderScopeType
     */
    protected $folderScope = null;

    /**
     * @var boolean
     */
    protected $isDeepTraversal = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getMailboxGuid()
    {
        return $this->mailboxGuid;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SingleLargeArchiveSearchScopeType
     */
    public function setMailboxGuid($value)
    {
        $this->mailboxGuid = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return SearchFolderScopeType
     */
    public function getFolderScope()
    {
        return $this->folderScope;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value SearchFolderScopeType
     * @return SingleLargeArchiveSearchScopeType
     */
    public function setFolderScope(SearchFolderScopeType $value)
    {
        $this->folderScope = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isDeepTraversal()
    {
        return ((bool) $this->isDeepTraversal);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIsDeepTraversal()
    {
        return $this->isDeepTraversal;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return SingleLargeArchiveSearchScopeType
     */
    public function setIsDeepTraversal($value)
    {
        $this->isDeepTraversal = $value;
        return $this;
    }
}
