<?php

namespace garethp\ews\API\Type;

/**
 * Class representing SkillInsightValueType
 *
 *
 * XSD Type: SkillInsightValue
 */
class SkillInsightValueType extends InsightValueType
{

    /**
     * @var string
     */
    protected $name = null;

    /**
     * @var integer
     */
    protected $strength = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return SkillInsightValueType
     */
    public function setName($value)
    {
        $this->name = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getStrength()
    {
        return $this->strength;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return SkillInsightValueType
     */
    public function setStrength($value)
    {
        $this->strength = $value;
        return $this;
    }
}
