<?php

namespace garethp\ews\API\Type;

/**
 * Class representing StringInsightValueType
 *
 *
 * XSD Type: StringInsightValue
 */
class StringInsightValueType extends InsightValueType
{

    /**
     * @var string
     */
    protected $data = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return StringInsightValueType
     */
    public function setData($value)
    {
        $this->data = $value;
        return $this;
    }
}
