<?php

namespace garethp\ews\API\Type;

/**
 * Class representing TaskType
 *
 *
 * XSD Type: TaskType
 *
 * @method TaskType addCompanies(string $companies)
 * @method TaskType addContacts(string $contacts)
 */
class TaskType extends ItemType
{

    /**
     * @var integer
     */
    protected $actualWork = null;

    /**
     * @var \DateTime
     */
    protected $assignedTime = null;

    protected $_typeMap = array(
        'assignedTime' => 'dateTime',
        'completeDate' => 'dateTime',
        'dueDate' => 'dateTime',
        'startDate' => 'dateTime',
    );

    /**
     * @var string
     */
    protected $billingInformation = null;

    /**
     * @var integer
     */
    protected $changeCount = null;

    /**
     * @var string[]
     */
    protected $companies = null;

    /**
     * @var \DateTime
     */
    protected $completeDate = null;

    /**
     * @var string[]
     */
    protected $contacts = null;

    /**
     * @var string
     */
    protected $delegationState = null;

    /**
     * @var string
     */
    protected $delegator = null;

    /**
     * @var \DateTime
     */
    protected $dueDate = null;

    /**
     * @var integer
     */
    protected $isAssignmentEditable = null;

    /**
     * @var boolean
     */
    protected $isComplete = null;

    /**
     * @var boolean
     */
    protected $isRecurring = null;

    /**
     * @var boolean
     */
    protected $isTeamTask = null;

    /**
     * @var string
     */
    protected $mileage = null;

    /**
     * @var string
     */
    protected $owner = null;

    /**
     * @var float
     */
    protected $percentComplete = null;

    /**
     * @var \garethp\ews\API\Type\TaskRecurrenceType
     */
    protected $recurrence = null;

    /**
     * @var \DateTime
     */
    protected $startDate = null;

    /**
     * @var string
     */
    protected $status = null;

    /**
     * @var string
     */
    protected $statusDescription = null;

    /**
     * @var integer
     */
    protected $totalWork = null;

    /**
     * @return integer
     */
    public function getActualWork()
    {
        return $this->actualWork;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return TaskType
     */
    public function setActualWork($value)
    {
        $this->actualWork = $this->castValueIfNeeded("actualWork", $value);
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getAssignedTime()
    {
        return $this->assignedTime;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return TaskType
     */
    public function setAssignedTime(\DateTime|string $value)
    {
        $this->assignedTime = $this->castValueIfNeeded("assignedTime", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getBillingInformation()
    {
        return $this->billingInformation;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return TaskType
     */
    public function setBillingInformation($value)
    {
        $this->billingInformation = $this->castValueIfNeeded("billingInformation", $value);
        return $this;
    }

    /**
     * @return integer
     */
    public function getChangeCount()
    {
        return $this->changeCount;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return TaskType
     */
    public function setChangeCount($value)
    {
        $this->changeCount = $this->castValueIfNeeded("changeCount", $value);
        return $this;
    }

    /**
     * @return string[]
     */
    public function getCompanies()
    {
        return $this->companies;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return TaskType
     */
    public function setCompanies(array $value)
    {
        $this->companies = $this->castValueIfNeeded("companies", $value);
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCompleteDate()
    {
        return $this->completeDate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return TaskType
     */
    public function setCompleteDate(\DateTime|string $value)
    {
        $this->completeDate = $this->castValueIfNeeded("completeDate", $value);
        return $this;
    }

    /**
     * @return string[]
     */
    public function getContacts()
    {
        return $this->contacts;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return TaskType
     */
    public function setContacts(array $value)
    {
        $this->contacts = $this->castValueIfNeeded("contacts", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getDelegationState()
    {
        return $this->delegationState;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return TaskType
     */
    public function setDelegationState($value)
    {
        $this->delegationState = $this->castValueIfNeeded("delegationState", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getDelegator()
    {
        return $this->delegator;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return TaskType
     */
    public function setDelegator($value)
    {
        $this->delegator = $this->castValueIfNeeded("delegator", $value);
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return TaskType
     */
    public function setDueDate(\DateTime|string $value)
    {
        $this->dueDate = $this->castValueIfNeeded("dueDate", $value);
        return $this;
    }

    /**
     * @return integer
     */
    public function getIsAssignmentEditable()
    {
        return $this->isAssignmentEditable;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return TaskType
     */
    public function setIsAssignmentEditable($value)
    {
        $this->isAssignmentEditable = $this->castValueIfNeeded("isAssignmentEditable", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isComplete()
    {
        return ((bool) $this->isComplete);
    }

    /**
     * @return boolean
     */
    public function getIsComplete()
    {
        return $this->isComplete;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return TaskType
     */
    public function setIsComplete($value)
    {
        $this->isComplete = $this->castValueIfNeeded("isComplete", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isRecurring()
    {
        return ((bool) $this->isRecurring);
    }

    /**
     * @return boolean
     */
    public function getIsRecurring()
    {
        return $this->isRecurring;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return TaskType
     */
    public function setIsRecurring($value)
    {
        $this->isRecurring = $this->castValueIfNeeded("isRecurring", $value);
        return $this;
    }

    /**
     * @returns bool
     */
    public function isTeamTask()
    {
        return ((bool) $this->isTeamTask);
    }

    /**
     * @return boolean
     */
    public function getIsTeamTask()
    {
        return $this->isTeamTask;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return TaskType
     */
    public function setIsTeamTask($value)
    {
        $this->isTeamTask = $this->castValueIfNeeded("isTeamTask", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getMileage()
    {
        return $this->mileage;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return TaskType
     */
    public function setMileage($value)
    {
        $this->mileage = $this->castValueIfNeeded("mileage", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return TaskType
     */
    public function setOwner($value)
    {
        $this->owner = $this->castValueIfNeeded("owner", $value);
        return $this;
    }

    /**
     * @return float
     */
    public function getPercentComplete()
    {
        return $this->percentComplete;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value float
     * @return TaskType
     */
    public function setPercentComplete($value)
    {
        $this->percentComplete = $this->castValueIfNeeded("percentComplete", $value);
        return $this;
    }

    /**
     * @return TaskRecurrenceType
     */
    public function getRecurrence()
    {
        return $this->recurrence;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TaskRecurrenceType
     * @return TaskType
     */
    public function setRecurrence(TaskRecurrenceType $value)
    {
        $this->recurrence = $this->castValueIfNeeded("recurrence", $value);
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \DateTime|string
     * @return TaskType
     */
    public function setStartDate(\DateTime|string $value)
    {
        $this->startDate = $this->castValueIfNeeded("startDate", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return TaskType
     */
    public function setStatus($value)
    {
        $this->status = $this->castValueIfNeeded("status", $value);
        return $this;
    }

    /**
     * @return string
     */
    public function getStatusDescription()
    {
        return $this->statusDescription;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return TaskType
     */
    public function setStatusDescription($value)
    {
        $this->statusDescription = $this->castValueIfNeeded("statusDescription", $value);
        return $this;
    }

    /**
     * @return integer
     */
    public function getTotalWork()
    {
        return $this->totalWork;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return TaskType
     */
    public function setTotalWork($value)
    {
        $this->totalWork = $this->castValueIfNeeded("totalWork", $value);
        return $this;
    }
}
