<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing TransitionType
 *
 *
 * XSD Type: TransitionType
 */
class TransitionType extends Type
{

    /**
     * @var \garethp\ews\API\Type\TransitionTargetType
     */
    protected $to = null;

    /**
     * @return TransitionTargetType
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value TransitionTargetType
     * @return TransitionType
     */
    public function setTo(TransitionTargetType $value)
    {
        $this->to = $this->castValueIfNeeded("to", $value);
        return $this;
    }
}
