<?php

namespace garethp\ews\API\Type;

/**
 * Class representing TwoOperandExpressionType
 *
 *
 * XSD Type: TwoOperandExpressionType
 *
 * @method TwoOperandExpressionType addFieldURI(FieldURI $fieldURI)
 * @method TwoOperandExpressionType addIndexedFieldURI(IndexedFieldURI $indexedFieldURI)
 * @method TwoOperandExpressionType addExtendedFieldURI(ExtendedFieldURI $extendedFieldURI)
 */
class TwoOperandExpressionType extends SearchExpressionType
{

    /**
     * @var \garethp\ews\API\Type\FieldURI[]
     */
    protected $fieldURI = null;

    /**
     * @var \garethp\ews\API\Type\IndexedFieldURI[]
     */
    protected $indexedFieldURI = null;

    /**
     * @var \garethp\ews\API\Type\ExtendedFieldURI[]
     */
    protected $extendedFieldURI = null;

    /**
     * @var \garethp\ews\API\Type\FieldURIOrConstantType
     */
    protected $fieldURIOrConstant = null;

    /**
     * @return FieldURI[]
     */
    public function getFieldURI()
    {
        return $this->fieldURI;
    }

    /**
     * @return IndexedFieldURI[]
     */
    public function getIndexedFieldURI()
    {
        return $this->indexedFieldURI;
    }

    /**
     * @return ExtendedFieldURI[]
     */
    public function getExtendedFieldURI()
    {
        return $this->extendedFieldURI;
    }

    /**
     * @return FieldURIOrConstantType
     */
    public function getFieldURIOrConstant()
    {
        return $this->fieldURIOrConstant;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value FieldURI[]
     * @return TwoOperandExpressionType
     */
    public function setFieldURI(array $value)
    {
        $this->fieldURI = $this->castValueIfNeeded("fieldURI", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value IndexedFieldURI[]
     * @return TwoOperandExpressionType
     */
    public function setIndexedFieldURI(array $value)
    {
        $this->indexedFieldURI = $this->castValueIfNeeded("indexedFieldURI", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ExtendedFieldURI[]
     * @return TwoOperandExpressionType
     */
    public function setExtendedFieldURI(array $value)
    {
        $this->extendedFieldURI = $this->castValueIfNeeded("extendedFieldURI", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value FieldURIOrConstantType
     * @return TwoOperandExpressionType
     */
    public function setFieldURIOrConstant(FieldURIOrConstantType $value)
    {
        $this->fieldURIOrConstant = $this->castValueIfNeeded("fieldURIOrConstant", $value);
        return $this;
    }
}
