<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing UniqueBodyType
 *
 *
 * XSD Type: UniqueBodyType
 */
class UniqueBodyType extends Type
{

    /**
     * @var string
     */
    protected $uniqueBodyType = null;

    /**
     * @var boolean
     */
    protected $isTruncated = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getUniqueBodyType()
    {
        return $this->uniqueBodyType;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UniqueBodyType
     */
    public function setUniqueBodyType($value)
    {
        $this->uniqueBodyType = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isTruncated()
    {
        return ((bool) $this->isTruncated);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getIsTruncated()
    {
        return $this->isTruncated;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return UniqueBodyType
     */
    public function setIsTruncated($value)
    {
        $this->isTruncated = $value;
        return $this;
    }
}
