<?php

namespace garethp\ews\API\Type;

/**
 * Class representing UrlEntityType
 *
 *
 * XSD Type: UrlEntityType
 */
class UrlEntityType extends EntityType
{

    /**
     * @var string
     */
    protected $url = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UrlEntityType
     */
    public function setUrl($value)
    {
        $this->url = $value;
        return $this;
    }
}
