<?php

namespace garethp\ews\API\Type;

/**
 * Class representing UserConfigurationNameType
 *
 *
 * XSD Type: UserConfigurationNameType
 */
class UserConfigurationNameType extends TargetFolderIdType
{

    /**
     * @var string
     */
    protected $name = null;

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserConfigurationNameType
     */
    public function setName($value)
    {
        $this->name = $this->castValueIfNeeded("name", $value);
        return $this;
    }
}
