<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing UserOofSettingsType
 *
 *
 * XSD Type: UserOofSettings
 */
class UserOofSettingsType extends Type
{

    /**
     * @var string
     */
    protected $oofState = null;

    /**
     * @var string
     */
    protected $externalAudience = null;

    /**
     * @var \garethp\ews\API\Type\DurationType
     */
    protected $duration = null;

    /**
     * @var \garethp\ews\API\Type\ReplyBodyType
     */
    protected $internalReply = null;

    /**
     * @var \garethp\ews\API\Type\ReplyBodyType
     */
    protected $externalReply = null;

    /**
     * @var \garethp\ews\API\Type\ReplyBodyType
     */
    protected $declineMeetingReply = null;

    /**
     * @var boolean
     */
    protected $declineEventsForScheduledOOF = null;

    /**
     * @var boolean
     */
    protected $declineAllEventsForScheduledOOF = null;

    /**
     * @var boolean
     */
    protected $createOOFEvent = null;

    /**
     * @var string
     */
    protected $oOFEventSubject = null;

    /**
     * @var boolean
     */
    protected $autoDeclineFutureRequestsWhenOOF = null;

    /**
     * @var string
     */
    protected $oOFEventID = null;

    /**
     * @var string[]
     */
    protected $eventsToDeleteIDs = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOofState()
    {
        return $this->oofState;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserOofSettingsType
     */
    public function setOofState($value)
    {
        $this->oofState = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getExternalAudience()
    {
        return $this->externalAudience;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserOofSettingsType
     */
    public function setExternalAudience($value)
    {
        $this->externalAudience = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return DurationType
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value DurationType
     * @return UserOofSettingsType
     */
    public function setDuration(DurationType $value)
    {
        $this->duration = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ReplyBodyType
     */
    public function getInternalReply()
    {
        return $this->internalReply;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyBodyType
     * @return UserOofSettingsType
     */
    public function setInternalReply(ReplyBodyType $value)
    {
        $this->internalReply = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ReplyBodyType
     */
    public function getExternalReply()
    {
        return $this->externalReply;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyBodyType
     * @return UserOofSettingsType
     */
    public function setExternalReply(ReplyBodyType $value)
    {
        $this->externalReply = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return ReplyBodyType
     */
    public function getDeclineMeetingReply()
    {
        return $this->declineMeetingReply;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value ReplyBodyType
     * @return UserOofSettingsType
     */
    public function setDeclineMeetingReply(ReplyBodyType $value)
    {
        $this->declineMeetingReply = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isDeclineEventsForScheduledOOF()
    {
        return ((bool) $this->declineEventsForScheduledOOF);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getDeclineEventsForScheduledOOF()
    {
        return $this->declineEventsForScheduledOOF;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return UserOofSettingsType
     */
    public function setDeclineEventsForScheduledOOF($value)
    {
        $this->declineEventsForScheduledOOF = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isDeclineAllEventsForScheduledOOF()
    {
        return ((bool) $this->declineAllEventsForScheduledOOF);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getDeclineAllEventsForScheduledOOF()
    {
        return $this->declineAllEventsForScheduledOOF;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return UserOofSettingsType
     */
    public function setDeclineAllEventsForScheduledOOF($value)
    {
        $this->declineAllEventsForScheduledOOF = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isCreateOOFEvent()
    {
        return ((bool) $this->createOOFEvent);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getCreateOOFEvent()
    {
        return $this->createOOFEvent;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return UserOofSettingsType
     */
    public function setCreateOOFEvent($value)
    {
        $this->createOOFEvent = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOOFEventSubject()
    {
        return $this->oOFEventSubject;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserOofSettingsType
     */
    public function setOOFEventSubject($value)
    {
        $this->oOFEventSubject = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return bool
     */
    public function isAutoDeclineFutureRequestsWhenOOF()
    {
        return ((bool) $this->autoDeclineFutureRequestsWhenOOF);
    }

    /**
     * @autogenerated This method is safe to replace
     * @return boolean
     */
    public function getAutoDeclineFutureRequestsWhenOOF()
    {
        return $this->autoDeclineFutureRequestsWhenOOF;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value bool
     * @return UserOofSettingsType
     */
    public function setAutoDeclineFutureRequestsWhenOOF($value)
    {
        $this->autoDeclineFutureRequestsWhenOOF = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getOOFEventID()
    {
        return $this->oOFEventID;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserOofSettingsType
     */
    public function setOOFEventID($value)
    {
        $this->oOFEventID = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserOofSettingsType
     */
    public function addEventsToDeleteIDs($value)
    {
        if ($this->eventsToDeleteIDs === null) {
                        $this->eventsToDeleteIDs = array();
        }

        if (!is_array($this->eventsToDeleteIDs)) {
            $this->eventsToDeleteIDs = array($this->eventsToDeleteIDs);
        }

        $this->eventsToDeleteIDs[] = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string[]
     */
    public function getEventsToDeleteIDs()
    {
        return $this->eventsToDeleteIDs;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]|string
     * @return UserOofSettingsType
     */
    public function setEventsToDeleteIDs(array|string $value)
    {
        if (!is_array($value)) {
            $value = [$value];
        }
        $this->eventsToDeleteIDs = $value;
        return $this;
    }
}
