<?php

namespace garethp\ews\API\Type;

use garethp\ews\API\Type;

/**
 * Class representing UserIdType
 *
 *
 * XSD Type: UserIdType
 */
class UserIdType extends Type
{

    /**
     * @var string
     */
    protected $sID = null;

    /**
     * @var string
     */
    protected $primarySmtpAddress = null;

    /**
     * @var string
     */
    protected $displayName = null;

    /**
     * @var string
     */
    protected $distinguishedUser = null;

    /**
     * @var string
     */
    protected $externalUserIdentity = null;

    /**
     * @return string
     */
    public function getSID()
    {
        return $this->sID;
    }

    /**
     * @return string
     */
    public function getPrimarySmtpAddress()
    {
        return $this->primarySmtpAddress;
    }

    /**
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * @return string
     */
    public function getDistinguishedUser()
    {
        return $this->distinguishedUser;
    }

    /**
     * @return string
     */
    public function getExternalUserIdentity()
    {
        return $this->externalUserIdentity;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserIdType
     */
    public function setSID($value)
    {
        $this->sID = $this->castValueIfNeeded("sID", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserIdType
     */
    public function setPrimarySmtpAddress($value)
    {
        $this->primarySmtpAddress = $this->castValueIfNeeded("primarySmtpAddress", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserIdType
     */
    public function setDisplayName($value)
    {
        $this->displayName = $this->castValueIfNeeded("displayName", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserIdType
     */
    public function setDistinguishedUser($value)
    {
        $this->distinguishedUser = $this->castValueIfNeeded("distinguishedUser", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return UserIdType
     */
    public function setExternalUserIdentity($value)
    {
        $this->externalUserIdentity = $this->castValueIfNeeded("externalUserIdentity", $value);
        return $this;
    }
}
