<?php

namespace garethp\ews\API\Type;

/**
 * Class representing WeeklyRecurrencePatternType
 *
 *
 * XSD Type: WeeklyRecurrencePatternType
 *
 * @method WeeklyRecurrencePatternType addDaysOfWeek(string $daysOfWeek)
 */
class WeeklyRecurrencePatternType extends IntervalRecurrencePatternBaseType
{

    /**
     * @var string[]
     */
    protected $daysOfWeek = null;

    /**
     * @var string
     */
    protected $firstDayOfWeek = null;

    /**
     * @return string[]
     */
    public function getDaysOfWeek()
    {
        return $this->daysOfWeek;
    }

    /**
     * @return string
     */
    public function getFirstDayOfWeek()
    {
        return $this->firstDayOfWeek;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string[]
     * @return WeeklyRecurrencePatternType
     */
    public function setDaysOfWeek(array $value)
    {
        $this->daysOfWeek = $this->castValueIfNeeded("daysOfWeek", $value);
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return WeeklyRecurrencePatternType
     */
    public function setFirstDayOfWeek($value)
    {
        $this->firstDayOfWeek = $this->castValueIfNeeded("firstDayOfWeek", $value);
        return $this;
    }
}
