name: Run Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.0', '7.4', '8.0']
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, soap, libxml, dom, simplexml
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug

      - name: Codestyle Check
        run: composer cs

      - name: PHPUnit
        run: ./vendor/bin/phpunit
